[project]
name = "pysnmp-mibs"
version = "1.17.8"
description = ""
authors = [{ name = "rfaircloth-splunk", email = "rfaircloth@splunk.com" }]
license = "BSD-2-Clause"
requires-python = ">=3.10,<3.12"
dependencies = [
    "pysnmp-pysmi>=2.3.0,<3",
    "pyyaml!=6.0.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.6.2,<5",
]

[tool.uv]
package = false
