#
# PySNMP MIB module CISCO-C12000-IF-HC-COUNTERS-MIB (http://snmplabs.com/pysmi)
# ASN.1 source CISCO-C12000-IF-HC-COUNTERS-MIB
# Source digest sha256:ae4f1d03c5d641f05f0199c4fedb09e9e3d65acd95cf614eb247c26d5eaf92a2
# Produced by pysmi-2.3.0
#
Integer, ObjectIdentifier, OctetString = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
NamedValues, = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
ciscoExperiment, = mibBuilder.importSymbols("CISCO-SMI", "ciscoExperiment")
ifIndex, = mibBuilder.importSymbols("IF-MIB", "ifIndex")
ModuleCompliance, NotificationGroup, ObjectGroup = mibBuilder.importSymbols("SNMPv2-CONF", "ModuleCompliance", "NotificationGroup", "ObjectGroup")
Bits, Counter32, Counter64, Gauge32, Integer32, IpAddress, ModuleIdentity, MibIdentifier, NotificationType, ObjectIdentity, MibScalar, MibTable, MibTableRow, MibTableColumn, TimeTicks, Unsigned32, iso = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Counter32", "Counter64", "Gauge32", "Integer32", "IpAddress", "ModuleIdentity", "MibIdentifier", "NotificationType", "ObjectIdentity", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "TimeTicks", "Unsigned32", "iso")
DisplayString, TextualConvention = mibBuilder.importSymbols("SNMPv2-TC", "DisplayString", "TextualConvention")
ciscoC12000IfHcCountersMIB = ModuleIdentity((1, 3, 6, 1, 4, 1, 9, 10, 31))
if mibBuilder.loadTexts: ciscoC12000IfHcCountersMIB.setLastUpdated('1998-05-27 00:00')
if mibBuilder.loadTexts: ciscoC12000IfHcCountersMIB.setOrganization('Cisco Systems, Inc.')
if mibBuilder.loadTexts: ciscoC12000IfHcCountersMIB.setContactInfo('       Cisco Systems\n                        Customer Service\n \n                Postal: 170 W Tasman Drive\n                        San Jose, CA  95134\n                        USA\n \n                   Tel: +1 800 553-NETS\n \n                E-mail: cs-snmp@cisco.com')
if mibBuilder.loadTexts: ciscoC12000IfHcCountersMIB.setDescription('A MIB module to describe and store IF-MIB High \n\t\tCapacity (ie 64 bit) Counters as two 32 bit \n\t\tobjects. This mib will ONLY be supported in the \n\t\t11.2GS version of IOS and will NOT be ported to \n\t\tany later versions.')
cHCCounterMIBObjects = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 10, 31, 1))
cHCCounterTable = MibTable((1, 3, 6, 1, 4, 1, 9, 10, 31, 1, 1), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cHCCounterTable.setStatus('current')
if mibBuilder.loadTexts: cHCCounterTable.setDescription('A table containing the High Capacity Counter \n\t\tinformation in the IF-MIB in two 32 bit fields.')
cHCCounterEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 10, 31, 1, 1, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "IF-MIB", "ifIndex"))
if mibBuilder.loadTexts: cHCCounterEntry.setStatus('current')
if mibBuilder.loadTexts: cHCCounterEntry.setDescription('High Capacity Counter information for each \n\t\tinterface in the IF-MIB.')
cHCCounterIfInOctetsUpper = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 31, 1, 1, 1, 1), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cHCCounterIfInOctetsUpper.setStatus('current')
if mibBuilder.loadTexts: cHCCounterIfInOctetsUpper.setDescription('The upper 32 bits of ifHCInOctets as described in the \n\t    IF-MIB.')
cHCCounterIfInOctetsLower = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 31, 1, 1, 1, 2), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cHCCounterIfInOctetsLower.setStatus('current')
if mibBuilder.loadTexts: cHCCounterIfInOctetsLower.setDescription('The lower 32 bits of ifHCInOctets as described in the \n\t    IF-MIB.')
cHCCounterIfInUcastPktsUpper = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 31, 1, 1, 1, 3), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cHCCounterIfInUcastPktsUpper.setStatus('current')
if mibBuilder.loadTexts: cHCCounterIfInUcastPktsUpper.setDescription('The upper 32 bits of ifHCInUcastPkts as described in the \n\t    IF-MIB.')
cHCCounterIfInUcastPktsLower = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 31, 1, 1, 1, 4), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cHCCounterIfInUcastPktsLower.setStatus('current')
if mibBuilder.loadTexts: cHCCounterIfInUcastPktsLower.setDescription('The lower 32 bits of ifHCInUcastPkts as described in the \n\t    IF-MIB.')
cHCCounterIfOutOctetsUpper = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 31, 1, 1, 1, 5), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cHCCounterIfOutOctetsUpper.setStatus('current')
if mibBuilder.loadTexts: cHCCounterIfOutOctetsUpper.setDescription('The upper 32 bits of ifHCOutOctets as described in the \n\t    IF-MIB.')
cHCCounterIfOutOctetsLower = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 31, 1, 1, 1, 6), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cHCCounterIfOutOctetsLower.setStatus('current')
if mibBuilder.loadTexts: cHCCounterIfOutOctetsLower.setDescription('The lower 32 bits of ifHCOutOctets as described in the \n\t    IF-MIB.')
cHCCounterIfOutUcastPktsUpper = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 31, 1, 1, 1, 7), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cHCCounterIfOutUcastPktsUpper.setStatus('current')
if mibBuilder.loadTexts: cHCCounterIfOutUcastPktsUpper.setDescription('The upper 32 bits of ifHCOutUcastPkts as described in the \n\t    IF-MIB.')
cHCCounterIfOutUcastPktsLower = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 31, 1, 1, 1, 8), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cHCCounterIfOutUcastPktsLower.setStatus('current')
if mibBuilder.loadTexts: cHCCounterIfOutUcastPktsLower.setDescription('The lower 32 bits of ifHCOutUcastPkts as described in the \n\t    IF-MIB.')
ciscoHCCountersMIBNotifications = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 10, 31, 2))
ciscoHCCountersMIBConformance = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 10, 31, 3))
ciscoHCCountersMIBCompliances = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 10, 31, 3, 1))
ciscoHCCountersMIBGroups = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 10, 31, 3, 2))
ciscoHCCountersMIBCompliance = ModuleCompliance((1, 3, 6, 1, 4, 1, 9, 10, 31, 3, 1, 1)).setObjects(("CISCO-C12000-IF-HC-COUNTERS-MIB", "ciscoHCCountersMIBGroup"))

if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    ciscoHCCountersMIBCompliance = ciscoHCCountersMIBCompliance.setStatus('current')
if mibBuilder.loadTexts: ciscoHCCountersMIBCompliance.setDescription('The compliance statement for entities which implement\n                the Cisco HC Counter MIB. This mib will ONLY be \n\t\tsupported in the 11.2GS version of IOS and will NOT be \n\t\tported to any later versions.')
ciscoHCCountersMIBGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 9, 10, 31, 3, 2, 1)).setObjects(("CISCO-C12000-IF-HC-COUNTERS-MIB", "cHCCounterIfInOctetsUpper"), ("CISCO-C12000-IF-HC-COUNTERS-MIB", "cHCCounterIfInOctetsLower"), ("CISCO-C12000-IF-HC-COUNTERS-MIB", "cHCCounterIfInUcastPktsUpper"), ("CISCO-C12000-IF-HC-COUNTERS-MIB", "cHCCounterIfInUcastPktsLower"), ("CISCO-C12000-IF-HC-COUNTERS-MIB", "cHCCounterIfOutOctetsUpper"), ("CISCO-C12000-IF-HC-COUNTERS-MIB", "cHCCounterIfOutOctetsLower"), ("CISCO-C12000-IF-HC-COUNTERS-MIB", "cHCCounterIfOutUcastPktsUpper"), ("CISCO-C12000-IF-HC-COUNTERS-MIB", "cHCCounterIfOutUcastPktsLower"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    ciscoHCCountersMIBGroup = ciscoHCCountersMIBGroup.setStatus('current')
if mibBuilder.loadTexts: ciscoHCCountersMIBGroup.setDescription('A collection of objects providing the HC Counter capability.\n\tThese objects will ONLY be supported in the 11.2GS version of \n\tIOS and will NOT be ported to any later versions.')
mibBuilder.exportSymbols("CISCO-C12000-IF-HC-COUNTERS-MIB", PYSNMP_MODULE_ID=ciscoC12000IfHcCountersMIB, cHCCounterEntry=cHCCounterEntry, cHCCounterIfInOctetsLower=cHCCounterIfInOctetsLower, cHCCounterIfInOctetsUpper=cHCCounterIfInOctetsUpper, cHCCounterIfInUcastPktsLower=cHCCounterIfInUcastPktsLower, cHCCounterIfInUcastPktsUpper=cHCCounterIfInUcastPktsUpper, cHCCounterIfOutOctetsLower=cHCCounterIfOutOctetsLower, cHCCounterIfOutOctetsUpper=cHCCounterIfOutOctetsUpper, cHCCounterIfOutUcastPktsLower=cHCCounterIfOutUcastPktsLower, cHCCounterIfOutUcastPktsUpper=cHCCounterIfOutUcastPktsUpper, cHCCounterMIBObjects=cHCCounterMIBObjects, cHCCounterTable=cHCCounterTable, ciscoC12000IfHcCountersMIB=ciscoC12000IfHcCountersMIB, ciscoHCCountersMIBCompliance=ciscoHCCountersMIBCompliance, ciscoHCCountersMIBCompliances=ciscoHCCountersMIBCompliances, ciscoHCCountersMIBConformance=ciscoHCCountersMIBConformance, ciscoHCCountersMIBGroup=ciscoHCCountersMIBGroup, ciscoHCCountersMIBGroups=ciscoHCCountersMIBGroups, ciscoHCCountersMIBNotifications=ciscoHCCountersMIBNotifications)
