#
# PySNMP MIB module CISCO-EPC-GATEWAY-MIB (http://snmplabs.com/pysmi)
# ASN.1 source CISCO-EPC-GATEWAY-MIB
# Source digest sha256:e7e2d878791550d38d507612ef43c3091ec3502ee54b01fde2f91cba76e24ecc
# Produced by pysmi-2.3.0
#
Integer, ObjectIdentifier, OctetString = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
NamedValues, = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
ciscoMgmt, = mibBuilder.importSymbols("CISCO-SMI", "ciscoMgmt")
SnmpAdminString, = mibBuilder.importSymbols("SNMP-FRAMEWORK-MIB", "SnmpAdminString")
ModuleCompliance, NotificationGroup, ObjectGroup = mibBuilder.importSymbols("SNMPv2-CONF", "ModuleCompliance", "NotificationGroup", "ObjectGroup")
Bits, Counter32, Counter64, Gauge32, Integer32, IpAddress, ModuleIdentity, MibIdentifier, NotificationType, ObjectIdentity, MibScalar, MibTable, MibTableRow, MibTableColumn, TimeTicks, Unsigned32, iso = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Counter32", "Counter64", "Gauge32", "Integer32", "IpAddress", "ModuleIdentity", "MibIdentifier", "NotificationType", "ObjectIdentity", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "TimeTicks", "Unsigned32", "iso")
DisplayString, TextualConvention, TimeInterval, TimeStamp, TruthValue = mibBuilder.importSymbols("SNMPv2-TC", "DisplayString", "TextualConvention", "TimeInterval", "TimeStamp", "TruthValue")
ciscoEpcGatewayMIB = ModuleIdentity((1, 3, 6, 1, 4, 1, 9, 9, 731))
ciscoEpcGatewayMIB.setRevisions(('2012-02-08 00:00', '2011-05-10 00:00', '2011-03-04 00:00', '2010-06-28 00:00', '2010-05-06 00:00', '2010-04-21 00:00',))

if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    if mibBuilder.loadTexts: ciscoEpcGatewayMIB.setRevisionsDescriptions(('Added the following object to ciscoEPCGatewayStatus\n        cegTotalIdleSessions.\n\n        Added the following objects to cegBufferStats\n        cegPacketDropDueToMaxPacketLimit,\n        cegPacketDropDueToMaxBufferLimit.\n\n        Added cegSystemStatusGrpSup3 group.\n        Added cegPacketDropLimitStatsGrp.\n        Deprecated ciscoEpcGatewayMIBComplianceRev2 and\n        replaced it with ciscoEpcGatewayMIBComplianceRev3.', 'Added the following objects to ciscoEpcGatewayStatus\n        cegActivatedBearers,\n        cegActivatedDedicatedBearers ,\n        cegActivatedIpv4DedicatedBearers,\n        cegActivatedIpv6DedicatedBearers.\n\n        Added cegSystemStatusGrpSup2 group.\n        Deprecated ciscoEpcGatewayMIBComplianceRev1 and\n        replaced it with ciscoEpcGatewayMIBComplianceRev2.', 'Added cegActivatedIpv4v6Bearers,\n        cegActivatedGtpv2SgwSessions,\n        cegActivatedGtpv2PgwSessions,\n        cegActivatedGtpv2SPgwSessions\n        to ciscoEpcGatewayStatus.\n\n        Added units for cegActivatedIpv4v6Sessions.\n\n        Added cegSystemStatusGrpSup1 to supplement \n        cegSystemStatusGrp.\n\n        Added ciscoEpcGatewayMIBComplianceRev1 and\n        deprecated ciscoEpcGatewayMIBCompliance.', 'Modified default values for the following objects\n        cegCongestionLowThreshold\n        cegCongestionHighThreshold', 'Modified Default values for the follwing\n        objects cegBufferMaxSize, \n        cegBufferDiscardDataTime, \n        cegBufferMaxPacketsPerBuffer. \n\n        Modified range for the following objects \n        cegBufferDiscardDataTime,\n        cegBufferMaxPacketsPerBuffer.', 'Initial version of this MIB module.',))
if mibBuilder.loadTexts: ciscoEpcGatewayMIB.setLastUpdated('2012-02-08 00:00')
if mibBuilder.loadTexts: ciscoEpcGatewayMIB.setOrganization('Cisco Systems, Inc.')
if mibBuilder.loadTexts: ciscoEpcGatewayMIB.setContactInfo('Cisco Systems\n            Customer Service\n\n            Postal: 170 W Tasman Drive\n            San Jose, CA  95134\n            USA\n\n            Tel: +1 800 553-NETS\n\n            E-mail: cs-lte@cisco.com')
if mibBuilder.loadTexts: ciscoEpcGatewayMIB.setDescription('This MIB module manages the features and configuration\n        for PDN Gateway(PGW) and Serving Gateway(SGW) in Evolved\n        Packet Core(EPC) architecture.\n\n        The PGW is the permanent IP point-of-attachment for \n        access via the E-UTRAN. The PGW performs IP policy and\n        charging enforcement on packet flows to and from mobile \n        devices.\n\n        The SGW is a local mobility anchor for E-UTRAN mobility,\n        switching packets between the S5 interface and the GTP\n        based S1-U interface for mobiles in connected mode.\n\n        +------------------------------------------------+  \n        |                                                |\n        |                                                |\n        |           +=======+__________                  |\n        |           | UTRAN |          |S12              | \n        |           |      +======+    |                 | \n        |           +======|      |    |                 |\n        |           +======| SGSN |___ |                 |\n        |           |      +======+   ||                 |\n        |           | GERAN |  |    S4||                 |\n        |           +=======+  |(GTP-C||                 |\n        |                    S3| VO,V1||                 |\n        |                      |  GTPU||                 |   \n        |                      |VO,V1)||                 |\n        |                  +======+   ||                 | \n        |              ____| MME  |__ ||                 |\n        |              |   +======+  |||                 |\n        |        S1-MME|      S11    |||                 |\n        |              |     GTP-C   |||                 |\n        |              |  (V0,V1,V2) |||                 |\n        |+====+ +========+        +======+     +======+  |  +===+\n        || UE |-|E-Utran |        | SGW  |     | PGW  |-SGi-|PDN|\n        ||    | |(EnodeB)|        |      |     |      |  |  |   |\n        |+====+ +========+        +======+     +======+  |  +===+\n        |              |            |  |  GTP-C   |      | \n        |              |            |  |(vo,v1,v2)|      | \n        |              |            |  |GTP-C     |      |  \n        |              |            |  |  (vo,v1) |      | \n        |              |  GTP v2-u  |  |          |      |\n        |               ------------   -----------       |\n        |                  (S1-U)          S5            |\n        |                                                |\n        +------------------------------------------------+\n\n        This architecture supports the non-roaming and roaming\n        architectures using GTP based protocol on the PGW and SGW\n        with a number of functions. It support high number of\n        subscribers with their associated control messages and\n        data traffic. Each of this association forms an entry in\n        PGW and SGW and is commonly know as bearers.\n\n        The various features used by this architecture and their\n        attributes are captured in this MIB:\n\n        1. Overload protection, handles congestion control, SGW and\n        PGW represent congestion as a DFP metric considering the\n        current CPU, memory usage and number of bearers open. On\n        reaching the low congestion threshold, based on the ARP, high\n        priority calls are accepted and those with a lower priority\n        are rejected. Once the high threshold is reached all new\n        calls are rejected.\n\n        2. Buffering agent, the SGW buffers the data packets in the\n        downlink direction till the downlink path/peer information is\n        ready. It buffers all packets coming from any gateway based\n        on the default/configured values of the buffer size, discard\n        period and number of packets. Packets will be buffered on a\n        per bearer basis and retrieved in the order it was buffered\n        using the handle given by the buffering agent initially. If\n        the buffer is full then no more bearers will be accepted. \n\n        Acronyms and terms:\n\n         3GPP     3rd Generation Partnership Project\n         DFP      Dynamic Feedback Protocol\n         EDGE     Enhanced Data rates for GSM Evolution\n         EPC      Evolved Packet Core\n         E-UTRAN  Evolved UTRAN\n         GERAN    GSM EDGE Radio Access Network\n         GPRS     General Packet Radio Service\n         GSM      Global System for Mobile communications\n         GTP      GPRS Tunneling Protocol\n         PDN      Public Data Network\n         PGW      PDN Gateway\n         SAE      System Architecture Evolution\n         SGW      Serving Gateway\n         SP GW    An integrated SGW and PGW Gateway\n         UE       User Equipment\n         UMTS     Universal Mobile Telecommunications System\n         UTRAN    UMTS Radio Access Network\n\n\n        REFERENCE\n\n        [1] 3GPP: Evolved GPRS Tunneling Protocol for Control\n            Plane (GTPv2-C). 3GPP TS 29.274 V1.3.1.\n\n        [2] 3GPP: GPRS enhancements for E-UTRAN access.\n            3GPP TS 23.401 V8.3.0.\n\n        [3] 3GPP: Circuit Switched fallback in Evolved\n            Packet System(EPS). 3GPP TS 23.272.')
ciscoEpcGatewayMIBNotifications = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 731, 0))
ciscoEpcGatewayMIBObjects = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 731, 1))
ciscoEpcGatewayStatistics = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 1))
cegOverloadProtectionStats = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 1, 1))
cegBufferStats = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 1, 2))
ciscoEpcGatewayConfig = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 2))
cegOverloadProtectionConfig = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 2, 1))
cegBufferingAgentConfig = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 2, 2))
ciscoEpcGatewayStatus = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 3))
ciscoEpcGatewayNotifMgmt = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 4))
cegCongestionIncomingReqDrops = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 1, 1, 1), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cegCongestionIncomingReqDrops.setStatus('current')
if mibBuilder.loadTexts: cegCongestionIncomingReqDrops.setDescription('This object represents the total number of\n        incoming calls dropped at the gateway.\n\n        This counter is incremented when the gateway\n        receives an incoming call request at high\n        congestion level, and the request is dropped.')
cegCongestionLowThresholdReached = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 1, 1, 2), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cegCongestionLowThresholdReached.setStatus('current')
if mibBuilder.loadTexts: cegCongestionLowThresholdReached.setDescription('This object represents the number of times\n        low congestion occurred on the gateway. \n\n        The value is equal to the number of times \n        the gateway exceeded the congestion threshold\n        cegCongestionLowThreshold.')
cegCongestionHighThresholdReached = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 1, 1, 3), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cegCongestionHighThresholdReached.setStatus('current')
if mibBuilder.loadTexts: cegCongestionHighThresholdReached.setDescription('This object represents the number of times\n        high congestion occurred on the gateway. \n\n        The value is equal to the number of times \n        the gateway exceeded the congestion threshold\n        cegCongestionHighThreshold.')
cegBuffersCreated = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 1, 2, 1), Counter32()).setUnits('buffer').setMaxAccess("readonly")
if mibBuilder.loadTexts: cegBuffersCreated.setStatus('current')
if mibBuilder.loadTexts: cegBuffersCreated.setDescription('This object represents the total number of\n        buffers allocated by buffering agent.')
cegBuffersDeleted = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 1, 2, 2), Counter32()).setUnits('buffer').setMaxAccess("readonly")
if mibBuilder.loadTexts: cegBuffersDeleted.setStatus('current')
if mibBuilder.loadTexts: cegBuffersDeleted.setDescription('This object represents the total number of\n        buffers deallocated by buffering agent.')
cegBuffersTimedOut = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 1, 2, 3), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cegBuffersTimedOut.setStatus('current')
if mibBuilder.loadTexts: cegBuffersTimedOut.setDescription('This object represents the total number of\n        buffers that got timed out, at buffering agent.\n\n        A buffer is timed out when the discard timer\n        cegBufferDiscardDataTime expires.')
cegBufferPacketsEnqueued = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 1, 2, 4), Counter32()).setUnits('packet').setMaxAccess("readonly")
if mibBuilder.loadTexts: cegBufferPacketsEnqueued.setStatus('current')
if mibBuilder.loadTexts: cegBufferPacketsEnqueued.setDescription('This object represents the total number of\n        packets enqueued to the buffering agent.')
cegBufferPacketsDequeued = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 1, 2, 5), Counter32()).setUnits('packet').setMaxAccess("readonly")
if mibBuilder.loadTexts: cegBufferPacketsDequeued.setStatus('current')
if mibBuilder.loadTexts: cegBufferPacketsDequeued.setDescription('This object represents the total number of\n        packets dequeued from the buffering agent.')
cegBufferBytesEnqueued = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 1, 2, 6), Counter32()).setUnits('Bytes').setMaxAccess("readonly")
if mibBuilder.loadTexts: cegBufferBytesEnqueued.setStatus('current')
if mibBuilder.loadTexts: cegBufferBytesEnqueued.setDescription('This object represents the total bytes of\n        data enqueued to the buffering agent.')
cegBufferBytesDequeued = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 1, 2, 7), Counter32()).setUnits('Bytes').setMaxAccess("readonly")
if mibBuilder.loadTexts: cegBufferBytesDequeued.setStatus('current')
if mibBuilder.loadTexts: cegBufferBytesDequeued.setDescription('This object represents the total bytes of\n        data dequeued from the buffering agent.')
cegBufferRejMemUnavailable = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 1, 2, 8), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cegBufferRejMemUnavailable.setStatus('current')
if mibBuilder.loadTexts: cegBufferRejMemUnavailable.setDescription('This object represents the total number of times, buffer\n        allocation is rejected by gateway due to, requested memory\n        is greater than cegTotalBufferAvailable.')
cegBufferRejLowMem = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 1, 2, 9), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cegBufferRejLowMem.setStatus('current')
if mibBuilder.loadTexts: cegBufferRejLowMem.setDescription('This object represents the total number of times, buffer\n        allocation is rejected due to, low memory availability in\n        the gateway.')
cegPacketDropDueToMaxPacketLimit = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 1, 2, 10), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cegPacketDropDueToMaxPacketLimit.setStatus('current')
if mibBuilder.loadTexts: cegPacketDropDueToMaxPacketLimit.setDescription('This object represents the number of packet drops due to bearer\n        maximum packet limit.')
cegPacketDropDueToMaxBufferLimit = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 1, 2, 11), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cegPacketDropDueToMaxBufferLimit.setStatus('current')
if mibBuilder.loadTexts: cegPacketDropDueToMaxBufferLimit.setDescription('This object represents the number of packet drops due to bearer\n        maximum buffer limit.')
cegCongestionLowThreshold = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 2, 1, 1), Unsigned32().subtype(subtypeSpec=ValueRangeConstraint(0, 100)).clone(95)).setUnits('percent').setMaxAccess("readwrite")
if mibBuilder.loadTexts: cegCongestionLowThreshold.setStatus('current')
if mibBuilder.loadTexts: cegCongestionLowThreshold.setDescription('This object specifies the low threshold\n        for congestion. Congestion DFP metric\n        considers the current CPU memory usage\n        and number of bearers open. On reaching\n        the low congestion threshold, based on the\n        ARP, high priority calls are accepted and\n        those with a lower priority are rejected.')
cegCongestionHighThreshold = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 2, 1, 2), Unsigned32().subtype(subtypeSpec=ValueRangeConstraint(0, 100)).clone(100)).setUnits('percent').setMaxAccess("readwrite")
if mibBuilder.loadTexts: cegCongestionHighThreshold.setStatus('current')
if mibBuilder.loadTexts: cegCongestionHighThreshold.setDescription('This object specifies the high threshold\n        for congestion. Congestion DFP metric\n        considers the current CPU memory usage\n        and number of bearers open. Once the\n        high threshold is reached all new calls\n        are rejected.')
cegBufferingAgentEnabled = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 2, 2, 1), TruthValue().clone('false')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: cegBufferingAgentEnabled.setStatus('current')
if mibBuilder.loadTexts: cegBufferingAgentEnabled.setDescription("This object specifies the state of\n        the buffering agent. \n\n        'true' - indicates that the buffering agent\n                 is enabled.\n        'false' - indicates that the buffering agent\n                  is disabled.")
cegBufferMaxSize = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 2, 2, 2), Unsigned32().subtype(subtypeSpec=ValueRangeConstraint(400, 12000)).clone(1024)).setUnits('Bytes').setMaxAccess("readwrite")
if mibBuilder.loadTexts: cegBufferMaxSize.setStatus('current')
if mibBuilder.loadTexts: cegBufferMaxSize.setDescription("This object represents the maximum size of a\n        buffer that can be allocated for a bearer.\n\n        This object is directly dependent on object\n        cegBufferingAgentEnabled and is applicable\n        only when buffering agent is enabled, that is\n        when cegBufferingAgentEnabled is 'true'.")
cegBufferDiscardDataTime = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 2, 2, 3), Unsigned32().subtype(subtypeSpec=ValueRangeConstraint(1, 300)).clone(30)).setUnits('second').setMaxAccess("readwrite")
if mibBuilder.loadTexts: cegBufferDiscardDataTime.setStatus('current')
if mibBuilder.loadTexts: cegBufferDiscardDataTime.setDescription('This object specifies the duration for which\n        the buffering agent waits before discarding a\n        buffer.\n\n        The discard timer begins when a packet is\n        enqueued in the allocated buffer for a bearer.\n        Whenever a packet is enqueued for a bearer, the\n        discard timer is reset. If the timer expires,\n        then the buffer is freed.')
cegBufferMaxPacketsPerBuffer = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 2, 2, 4), Unsigned32().subtype(subtypeSpec=ValueRangeConstraint(1, 15)).clone(5)).setUnits('packet').setMaxAccess("readwrite")
if mibBuilder.loadTexts: cegBufferMaxPacketsPerBuffer.setStatus('current')
if mibBuilder.loadTexts: cegBufferMaxPacketsPerBuffer.setDescription('This object specifies the maximum\n        number of packets allowed per buffer in\n        buffering agent.\n\n        Any new incoming packet after this\n        value has reached its maximum will be\n        dropped.')
cegVersion = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 3, 1), SnmpAdminString().subtype(subtypeSpec=ValueSizeConstraint(1, 100))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cegVersion.setStatus('current')
if mibBuilder.loadTexts: cegVersion.setDescription('This object represents the current\n        version of the PGW or SGW software\n        running on the gateway.\n\n        Display format: \n        <software> : <version>:<release>.')
cegActivatedIpv4Bearers = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 3, 2), Gauge32()).setUnits('bearer').setMaxAccess("readonly")
if mibBuilder.loadTexts: cegActivatedIpv4Bearers.setStatus('current')
if mibBuilder.loadTexts: cegActivatedIpv4Bearers.setDescription('This object represents the total\n        activated IPv4 GTPv2 bearers.')
cegActivatedIpv6Bearers = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 3, 3), Gauge32()).setUnits('bearer').setMaxAccess("readonly")
if mibBuilder.loadTexts: cegActivatedIpv6Bearers.setStatus('current')
if mibBuilder.loadTexts: cegActivatedIpv6Bearers.setDescription('This object represents the total\n        activated IPv6 GTPv2 bearers.')
cegTotalUsers = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 3, 4), Gauge32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cegTotalUsers.setStatus('current')
if mibBuilder.loadTexts: cegTotalUsers.setDescription('This object represents the total number of\n        users connected to the gateway.')
cegTotalIdleUsers = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 3, 5), Gauge32()).setUnits('Users').setMaxAccess("readonly")
if mibBuilder.loadTexts: cegTotalIdleUsers.setStatus('current')
if mibBuilder.loadTexts: cegTotalIdleUsers.setDescription('This object represents the total number of users\n        currently in ISR state in the gateway.')
cegTotalSuspendedUsers = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 3, 6), Gauge32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cegTotalSuspendedUsers.setStatus('current')
if mibBuilder.loadTexts: cegTotalSuspendedUsers.setDescription('This object represents the total number of users\n        suspended by the gateway.\n\n        A user would be suspended when E-UTRAN coverage is\n        overlapped by either GERAN or UTRAN coverage leading\n        to a Circuit Switch fallback from E-UTRAN. The Circuit\n        Switch fallback enables reuse of voice and other Circuit\n        Switch services by reuse of the Circuit Switch\n        infrastructure.')
cegActivatedIpv4v6Sessions = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 3, 7), Gauge32()).setUnits('sessions').setMaxAccess("readonly")
if mibBuilder.loadTexts: cegActivatedIpv4v6Sessions.setStatus('current')
if mibBuilder.loadTexts: cegActivatedIpv4v6Sessions.setDescription('This object represents the total number of activated\n        IPv4v6 sessions.')
cegActivatedIpv4v6Bearers = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 3, 10), Gauge32()).setUnits('bearers').setMaxAccess("readonly")
if mibBuilder.loadTexts: cegActivatedIpv4v6Bearers.setStatus('current')
if mibBuilder.loadTexts: cegActivatedIpv4v6Bearers.setDescription('This object represents the total number of activated\n        IPv4v6 bearers.')
cegActivatedGtpv2SgwSessions = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 3, 11), Gauge32()).setUnits('sessions').setMaxAccess("readonly")
if mibBuilder.loadTexts: cegActivatedGtpv2SgwSessions.setStatus('current')
if mibBuilder.loadTexts: cegActivatedGtpv2SgwSessions.setDescription('This object represents the total number of activated\n        GTPV2 sessions in SGW mode.')
cegActivatedGtpv2PgwSessions = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 3, 12), Gauge32()).setUnits('sessions').setMaxAccess("readonly")
if mibBuilder.loadTexts: cegActivatedGtpv2PgwSessions.setStatus('current')
if mibBuilder.loadTexts: cegActivatedGtpv2PgwSessions.setDescription('This object represents the total number of activated\n        GTPV2 sessions in PGW mode.')
cegActivatedGtpv2SPgwSessions = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 3, 13), Gauge32()).setUnits('sessions').setMaxAccess("readonly")
if mibBuilder.loadTexts: cegActivatedGtpv2SPgwSessions.setStatus('current')
if mibBuilder.loadTexts: cegActivatedGtpv2SPgwSessions.setDescription('This object represents the total number of activated\n        GTPV2 sessions in SP GW mode.')
cegOverloadProtectionStatus = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 3, 8))
cegCongestionDfpWeight = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 3, 8, 1), Unsigned32().subtype(subtypeSpec=ValueRangeConstraint(0, 65535))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cegCongestionDfpWeight.setStatus('current')
if mibBuilder.loadTexts: cegCongestionDfpWeight.setDescription('This object represents the DFP weight value, which\n        is the measure of the load on CPU in the gateway.')
cegCongestionStatus = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 3, 8, 2), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3))).clone(namedValues=NamedValues(("normal", 1), ("low", 2), ("high", 3)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cegCongestionStatus.setStatus('current')
if mibBuilder.loadTexts: cegCongestionStatus.setDescription('This object represents the gateway congestion\n        status.\n\n        normal - The gateway is not in a congestion state.\n                 At this state, the value of cegCongestionDfpWeight\n                 is less than value of cegCongestionLowThreshold.\n        low - The gateway is running in low congestion state.\n              At this state, the value of cegCongestionDfpWeight\n              is more than value of cegCongestionLowThreshold but \n              less than value of cegCongestionHighThreshold.\n        high - The gateway is running in high congestion state.\n              At this state, the value of cegCongestionDfpWeight\n              is more than value of cegCongestionHighThreshold.')
cegCongestionLowLastOccurTime = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 3, 8, 3), TimeStamp()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cegCongestionLowLastOccurTime.setStatus('current')
if mibBuilder.loadTexts: cegCongestionLowLastOccurTime.setDescription('This object represents the timestamp at\n        which low congestion last occurred on the\n        gateway.')
cegCongestionLowLastDuration = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 3, 8, 4), TimeInterval()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cegCongestionLowLastDuration.setStatus('current')
if mibBuilder.loadTexts: cegCongestionLowLastDuration.setDescription('This object represents the duration of\n        last low congestion.')
cegCongestionHighLastOccurTime = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 3, 8, 5), TimeStamp()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cegCongestionHighLastOccurTime.setStatus('current')
if mibBuilder.loadTexts: cegCongestionHighLastOccurTime.setDescription('This object represents the timestamp at\n        which high congestion last occurred on the\n        gateway.')
cegCongestionHighLastDuration = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 3, 8, 6), TimeInterval()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cegCongestionHighLastDuration.setStatus('current')
if mibBuilder.loadTexts: cegCongestionHighLastDuration.setDescription('This object represents the duration of\n        the last high congestion.')
cegBufferStatus = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 3, 9))
cegActivatedBearers = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 3, 14), Gauge32()).setUnits('Bearers').setMaxAccess("readonly")
if mibBuilder.loadTexts: cegActivatedBearers.setStatus('current')
if mibBuilder.loadTexts: cegActivatedBearers.setDescription('This object represents the total number of default and\n        dedicated bearers currently active in the Gateway.')
cegActivatedDedicatedBearers = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 3, 15), Gauge32()).setUnits('Bearers').setMaxAccess("readonly")
if mibBuilder.loadTexts: cegActivatedDedicatedBearers.setStatus('current')
if mibBuilder.loadTexts: cegActivatedDedicatedBearers.setDescription('This object represents the total number of\n        dedicated bearers currently active in the Gateway.')
cegActivatedIpv4DedicatedBearers = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 3, 16), Gauge32()).setUnits('Bearers').setMaxAccess("readonly")
if mibBuilder.loadTexts: cegActivatedIpv4DedicatedBearers.setStatus('current')
if mibBuilder.loadTexts: cegActivatedIpv4DedicatedBearers.setDescription('This object represents the total number of IPv4\n        dedicated bearers currently active in the Gateway.')
cegActivatedIpv6DedicatedBearers = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 3, 17), Gauge32()).setUnits('Bearers').setMaxAccess("readonly")
if mibBuilder.loadTexts: cegActivatedIpv6DedicatedBearers.setStatus('current')
if mibBuilder.loadTexts: cegActivatedIpv6DedicatedBearers.setDescription('This object represents the total number of IPv6\n        dedicated bearers currently active in the Gateway.')
cegTotalIdleSessions = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 3, 18), Gauge32()).setUnits('Sessions').setMaxAccess("readonly")
if mibBuilder.loadTexts: cegTotalIdleSessions.setStatus('current')
if mibBuilder.loadTexts: cegTotalIdleSessions.setDescription('This object represents the total number of sessions\n        currently in Idle state in the gateway.')
cegTotalInUseBuffers = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 3, 9, 1), Gauge32()).setUnits('buffer').setMaxAccess("readonly")
if mibBuilder.loadTexts: cegTotalInUseBuffers.setStatus('current')
if mibBuilder.loadTexts: cegTotalInUseBuffers.setDescription('This object represents the total\n        number of buffers currently allocated\n        for the bearers, by buffering agents.')
cegTotalBufferedPackets = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 3, 9, 2), Gauge32()).setUnits('packet').setMaxAccess("readonly")
if mibBuilder.loadTexts: cegTotalBufferedPackets.setStatus('current')
if mibBuilder.loadTexts: cegTotalBufferedPackets.setDescription('This object represents the total\n        number of packets buffered at present\n        in the buffers of buffering agents.')
cegTotalBufferedBytes = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 3, 9, 3), Gauge32()).setUnits('Bytes').setMaxAccess("readonly")
if mibBuilder.loadTexts: cegTotalBufferedBytes.setStatus('current')
if mibBuilder.loadTexts: cegTotalBufferedBytes.setDescription('This object represents the total\n        number of bytes buffered at present\n        in the buffers of buffering agents.')
cegTotalBufferAvailable = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 3, 9, 4), Gauge32()).setUnits('Bytes').setMaxAccess("readonly")
if mibBuilder.loadTexts: cegTotalBufferAvailable.setStatus('current')
if mibBuilder.loadTexts: cegTotalBufferAvailable.setDescription('This object represents the total\n        unallocated bytes at buffering agents.')
cegCongestionHighNotifEnable = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 4, 1), TruthValue().clone('false')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: cegCongestionHighNotifEnable.setStatus('current')
if mibBuilder.loadTexts: cegCongestionHighNotifEnable.setDescription("The object controls the generation of\n        cegCongestionHighThresholdNotif as follows:\n         'true(1)' - the generation of cegCongestionHighThresholdNotif \n                     notifications is enabled.\n         'false(2)' - the generation of cegCongestionHighThresholdNotif \n                     notifications is disabled.")
cegCongestionLowNotifEnable = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 4, 2), TruthValue().clone('false')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: cegCongestionLowNotifEnable.setStatus('current')
if mibBuilder.loadTexts: cegCongestionLowNotifEnable.setDescription("The object controls the generation of\n        cegCongestionLowThresholdNotif as follows:\n         'true(1)' - the generation of cegCongestionLowThresholdNotif \n                     notifications is enabled.\n         'false(2)' - the generation of cegCongestionLowThresholdNotif \n                     notifications is disabled.")
cegCongestionClearNotifEnable = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 731, 1, 4, 3), TruthValue().clone('false')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: cegCongestionClearNotifEnable.setStatus('current')
if mibBuilder.loadTexts: cegCongestionClearNotifEnable.setDescription("The object controls the generation of\n        cegCongestionClearedNotif as follows:\n         'true(1)' - the generation of cegCongestionClearedNotif \n                     notifications is enabled.\n         'false(2)' - the generation of cegCongestionClearedNotif \n                     notifications is disabled.")
cegCongestionHighThresholdNotif = NotificationType((1, 3, 6, 1, 4, 1, 9, 9, 731, 0, 1)).setObjects(("CISCO-EPC-GATEWAY-MIB", "cegVersion"), ("CISCO-EPC-GATEWAY-MIB", "cegCongestionDfpWeight"), ("CISCO-EPC-GATEWAY-MIB", "cegCongestionStatus"), ("CISCO-EPC-GATEWAY-MIB", "cegCongestionHighThreshold"))
if mibBuilder.loadTexts: cegCongestionHighThresholdNotif.setStatus('current')
if mibBuilder.loadTexts: cegCongestionHighThresholdNotif.setDescription('This notification will be sent when\n        the gateway congestion level goes above\n        cegCongestionHighThreshold value.\n\n        This gives an indication that the gateway\n        is running at high congestion and at this\n        state it would reject all new calls.')
cegCongestionLowThresholdNotif = NotificationType((1, 3, 6, 1, 4, 1, 9, 9, 731, 0, 2)).setObjects(("CISCO-EPC-GATEWAY-MIB", "cegVersion"), ("CISCO-EPC-GATEWAY-MIB", "cegCongestionDfpWeight"), ("CISCO-EPC-GATEWAY-MIB", "cegCongestionStatus"), ("CISCO-EPC-GATEWAY-MIB", "cegCongestionLowThreshold"), ("CISCO-EPC-GATEWAY-MIB", "cegCongestionHighThreshold"))
if mibBuilder.loadTexts: cegCongestionLowThresholdNotif.setStatus('current')
if mibBuilder.loadTexts: cegCongestionLowThresholdNotif.setDescription('This notification will be sent when\n        the gateway congestion level goes above\n        cegCongestionLowThreshold value.\n\n        This gives an indication that the gateway\n        is running at low congestion at this\n        state it can accept only the high priority\n        calls and those with a lower priority would\n        be rejected.')
cegCongestionClearedNotif = NotificationType((1, 3, 6, 1, 4, 1, 9, 9, 731, 0, 3)).setObjects(("CISCO-EPC-GATEWAY-MIB", "cegVersion"), ("CISCO-EPC-GATEWAY-MIB", "cegCongestionDfpWeight"), ("CISCO-EPC-GATEWAY-MIB", "cegCongestionStatus"), ("CISCO-EPC-GATEWAY-MIB", "cegCongestionLowThreshold"))
if mibBuilder.loadTexts: cegCongestionClearedNotif.setStatus('current')
if mibBuilder.loadTexts: cegCongestionClearedNotif.setDescription('This notification will be sent when\n        the gateway congestion level goes below\n        cegCongestionLowThreshold value.\n\n        This gives an indication that the gateway\n        has recovered from congestion and it can\n        accept all calls.')
ciscoEpcGatewayMIBConformance = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 731, 3))
ciscoEpcGatewayMIBCompliances = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 731, 3, 1))
ciscoEpcGatewayMIBGroups = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 731, 3, 2))
ciscoEpcGatewayMIBCompliance = ModuleCompliance((1, 3, 6, 1, 4, 1, 9, 9, 731, 3, 1, 1)).setObjects(("CISCO-EPC-GATEWAY-MIB", "cegSystemStatusGrp"), ("CISCO-EPC-GATEWAY-MIB", "cegOverloadProtectionStatsGrp"), ("CISCO-EPC-GATEWAY-MIB", "cegOverloadProtectionConfigGrp"), ("CISCO-EPC-GATEWAY-MIB", "cegOverloadProtectionStatusGrp"), ("CISCO-EPC-GATEWAY-MIB", "cegOverloadProtectionNotifMgmtGrp"), ("CISCO-EPC-GATEWAY-MIB", "cegOverloadProtectionNotifGrp"), ("CISCO-EPC-GATEWAY-MIB", "cegBufferingAgentStatsGrp"), ("CISCO-EPC-GATEWAY-MIB", "cegBufferingAgentConfigGrp"), ("CISCO-EPC-GATEWAY-MIB", "cegBufferingAgentStatusGrp"))

if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    ciscoEpcGatewayMIBCompliance = ciscoEpcGatewayMIBCompliance.setStatus('deprecated')
if mibBuilder.loadTexts: ciscoEpcGatewayMIBCompliance.setDescription('The compliance statement is for the entities\n        which implement CISCO-EPC-GATEWAY-MIB.\n        This is deprecated by ciscoEpcGatewayMIBComplianceRev1.')
ciscoEpcGatewayMIBComplianceRev1 = ModuleCompliance((1, 3, 6, 1, 4, 1, 9, 9, 731, 3, 1, 2)).setObjects(("CISCO-EPC-GATEWAY-MIB", "cegSystemStatusGrp"), ("CISCO-EPC-GATEWAY-MIB", "cegOverloadProtectionStatsGrp"), ("CISCO-EPC-GATEWAY-MIB", "cegOverloadProtectionConfigGrp"), ("CISCO-EPC-GATEWAY-MIB", "cegOverloadProtectionStatusGrp"), ("CISCO-EPC-GATEWAY-MIB", "cegOverloadProtectionNotifMgmtGrp"), ("CISCO-EPC-GATEWAY-MIB", "cegOverloadProtectionNotifGrp"), ("CISCO-EPC-GATEWAY-MIB", "cegSystemStatusGrpSup1"), ("CISCO-EPC-GATEWAY-MIB", "cegBufferingAgentStatsGrp"), ("CISCO-EPC-GATEWAY-MIB", "cegBufferingAgentConfigGrp"), ("CISCO-EPC-GATEWAY-MIB", "cegBufferingAgentStatusGrp"))

if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    ciscoEpcGatewayMIBComplianceRev1 = ciscoEpcGatewayMIBComplianceRev1.setStatus('deprecated')
if mibBuilder.loadTexts: ciscoEpcGatewayMIBComplianceRev1.setDescription('The compliance statement is for the entities\n        which implement CISCO-EPC-GATEWAY-MIB.\n        This is deprecated by ciscoEpcGatewayMIBComplianceRev2.')
ciscoEPCGatewayMIBComplianceRev2 = ModuleCompliance((1, 3, 6, 1, 4, 1, 9, 9, 731, 3, 1, 3)).setObjects(("CISCO-EPC-GATEWAY-MIB", "cegSystemStatusGrp"), ("CISCO-EPC-GATEWAY-MIB", "cegOverloadProtectionConfigGrp"), ("CISCO-EPC-GATEWAY-MIB", "cegOverloadProtectionNotifMgmtGrp"), ("CISCO-EPC-GATEWAY-MIB", "cegOverloadProtectionStatsGrp"), ("CISCO-EPC-GATEWAY-MIB", "cegOverloadProtectionStatusGrp"), ("CISCO-EPC-GATEWAY-MIB", "cegOverloadProtectionNotifGrp"), ("CISCO-EPC-GATEWAY-MIB", "cegSystemStatusGrpSup1"), ("CISCO-EPC-GATEWAY-MIB", "cegSystemStatusGrpSup2"), ("CISCO-EPC-GATEWAY-MIB", "cegBufferingAgentStatsGrp"), ("CISCO-EPC-GATEWAY-MIB", "cegBufferingAgentConfigGrp"), ("CISCO-EPC-GATEWAY-MIB", "cegBufferingAgentStatusGrp"))

if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    ciscoEPCGatewayMIBComplianceRev2 = ciscoEPCGatewayMIBComplianceRev2.setStatus('deprecated')
if mibBuilder.loadTexts: ciscoEPCGatewayMIBComplianceRev2.setDescription('The compliance statement is for the entities\n        which implement CISCO-EPC-GATEWAY-MIB. \n        This is superceded by ciscoEpcGatewayMIBComplianceRev3.')
ciscoEpcGatewayMIBComplianceRev3 = ModuleCompliance((1, 3, 6, 1, 4, 1, 9, 9, 731, 3, 1, 4)).setObjects(("CISCO-EPC-GATEWAY-MIB", "cegSystemStatusGrp"), ("CISCO-EPC-GATEWAY-MIB", "cegOverloadProtectionStatsGrp"), ("CISCO-EPC-GATEWAY-MIB", "cegOverloadProtectionConfigGrp"), ("CISCO-EPC-GATEWAY-MIB", "cegOverloadProtectionStatusGrp"), ("CISCO-EPC-GATEWAY-MIB", "cegOverloadProtectionNotifMgmtGrp"), ("CISCO-EPC-GATEWAY-MIB", "cegOverloadProtectionNotifGrp"), ("CISCO-EPC-GATEWAY-MIB", "cegSystemStatusGrpSup1"), ("CISCO-EPC-GATEWAY-MIB", "cegSystemStatusGrpSup2"), ("CISCO-EPC-GATEWAY-MIB", "cegSystemStatusGrpSup3"), ("CISCO-EPC-GATEWAY-MIB", "cegBufferingAgentStatsGrp"), ("CISCO-EPC-GATEWAY-MIB", "cegBufferingAgentConfigGrp"), ("CISCO-EPC-GATEWAY-MIB", "cegBufferingAgentStatusGrp"), ("CISCO-EPC-GATEWAY-MIB", "cegBufferingAgentStatsGrpSup1"))

if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    ciscoEpcGatewayMIBComplianceRev3 = ciscoEpcGatewayMIBComplianceRev3.setStatus('current')
if mibBuilder.loadTexts: ciscoEpcGatewayMIBComplianceRev3.setDescription('The compliance statement is for the entities\n        which implement CISCO-EPC-GATEWAY-MIB.')
cegSystemStatusGrp = ObjectGroup((1, 3, 6, 1, 4, 1, 9, 9, 731, 3, 2, 1)).setObjects(("CISCO-EPC-GATEWAY-MIB", "cegVersion"), ("CISCO-EPC-GATEWAY-MIB", "cegActivatedIpv4Bearers"), ("CISCO-EPC-GATEWAY-MIB", "cegActivatedIpv6Bearers"), ("CISCO-EPC-GATEWAY-MIB", "cegTotalUsers"), ("CISCO-EPC-GATEWAY-MIB", "cegTotalSuspendedUsers"), ("CISCO-EPC-GATEWAY-MIB", "cegActivatedIpv4v6Sessions"), ("CISCO-EPC-GATEWAY-MIB", "cegTotalIdleUsers"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    cegSystemStatusGrp = cegSystemStatusGrp.setStatus('current')
if mibBuilder.loadTexts: cegSystemStatusGrp.setDescription('This group has a collection of objects to provide the\n        system status.')
cegOverloadProtectionStatsGrp = ObjectGroup((1, 3, 6, 1, 4, 1, 9, 9, 731, 3, 2, 2)).setObjects(("CISCO-EPC-GATEWAY-MIB", "cegCongestionIncomingReqDrops"), ("CISCO-EPC-GATEWAY-MIB", "cegCongestionHighThresholdReached"), ("CISCO-EPC-GATEWAY-MIB", "cegCongestionLowThresholdReached"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    cegOverloadProtectionStatsGrp = cegOverloadProtectionStatsGrp.setStatus('current')
if mibBuilder.loadTexts: cegOverloadProtectionStatsGrp.setDescription('This group has a collection of objects to provide the\n        overload protection statistics.')
cegBufferingAgentStatsGrp = ObjectGroup((1, 3, 6, 1, 4, 1, 9, 9, 731, 3, 2, 3)).setObjects(("CISCO-EPC-GATEWAY-MIB", "cegBuffersCreated"), ("CISCO-EPC-GATEWAY-MIB", "cegBufferPacketsEnqueued"), ("CISCO-EPC-GATEWAY-MIB", "cegBufferBytesEnqueued"), ("CISCO-EPC-GATEWAY-MIB", "cegBufferPacketsDequeued"), ("CISCO-EPC-GATEWAY-MIB", "cegBufferBytesDequeued"), ("CISCO-EPC-GATEWAY-MIB", "cegBuffersDeleted"), ("CISCO-EPC-GATEWAY-MIB", "cegBuffersTimedOut"), ("CISCO-EPC-GATEWAY-MIB", "cegBufferRejMemUnavailable"), ("CISCO-EPC-GATEWAY-MIB", "cegBufferRejLowMem"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    cegBufferingAgentStatsGrp = cegBufferingAgentStatsGrp.setStatus('current')
if mibBuilder.loadTexts: cegBufferingAgentStatsGrp.setDescription('This group has a collection of objects to provide the\n        buffering agent statistics.')
cegOverloadProtectionConfigGrp = ObjectGroup((1, 3, 6, 1, 4, 1, 9, 9, 731, 3, 2, 4)).setObjects(("CISCO-EPC-GATEWAY-MIB", "cegCongestionLowThreshold"), ("CISCO-EPC-GATEWAY-MIB", "cegCongestionHighThreshold"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    cegOverloadProtectionConfigGrp = cegOverloadProtectionConfigGrp.setStatus('current')
if mibBuilder.loadTexts: cegOverloadProtectionConfigGrp.setDescription('This group has a collection of objects which configures\n        attributes for overload protection.')
cegBufferingAgentConfigGrp = ObjectGroup((1, 3, 6, 1, 4, 1, 9, 9, 731, 3, 2, 5)).setObjects(("CISCO-EPC-GATEWAY-MIB", "cegBufferingAgentEnabled"), ("CISCO-EPC-GATEWAY-MIB", "cegBufferMaxSize"), ("CISCO-EPC-GATEWAY-MIB", "cegBufferDiscardDataTime"), ("CISCO-EPC-GATEWAY-MIB", "cegBufferMaxPacketsPerBuffer"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    cegBufferingAgentConfigGrp = cegBufferingAgentConfigGrp.setStatus('current')
if mibBuilder.loadTexts: cegBufferingAgentConfigGrp.setDescription('This group has a collection of objects which configures\n        the buffering agent.')
cegBufferingAgentStatusGrp = ObjectGroup((1, 3, 6, 1, 4, 1, 9, 9, 731, 3, 2, 6)).setObjects(("CISCO-EPC-GATEWAY-MIB", "cegTotalInUseBuffers"), ("CISCO-EPC-GATEWAY-MIB", "cegTotalBufferedPackets"), ("CISCO-EPC-GATEWAY-MIB", "cegTotalBufferedBytes"), ("CISCO-EPC-GATEWAY-MIB", "cegTotalBufferAvailable"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    cegBufferingAgentStatusGrp = cegBufferingAgentStatusGrp.setStatus('current')
if mibBuilder.loadTexts: cegBufferingAgentStatusGrp.setDescription('This group has a collection of objects to provide the\n        buffering agent status.')
cegOverloadProtectionStatusGrp = ObjectGroup((1, 3, 6, 1, 4, 1, 9, 9, 731, 3, 2, 7)).setObjects(("CISCO-EPC-GATEWAY-MIB", "cegCongestionDfpWeight"), ("CISCO-EPC-GATEWAY-MIB", "cegCongestionStatus"), ("CISCO-EPC-GATEWAY-MIB", "cegCongestionLowLastOccurTime"), ("CISCO-EPC-GATEWAY-MIB", "cegCongestionLowLastDuration"), ("CISCO-EPC-GATEWAY-MIB", "cegCongestionHighLastOccurTime"), ("CISCO-EPC-GATEWAY-MIB", "cegCongestionHighLastDuration"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    cegOverloadProtectionStatusGrp = cegOverloadProtectionStatusGrp.setStatus('current')
if mibBuilder.loadTexts: cegOverloadProtectionStatusGrp.setDescription('This group has a collection of objects to provide the\n        overload protection status.')
cegOverloadProtectionNotifMgmtGrp = ObjectGroup((1, 3, 6, 1, 4, 1, 9, 9, 731, 3, 2, 8)).setObjects(("CISCO-EPC-GATEWAY-MIB", "cegCongestionHighNotifEnable"), ("CISCO-EPC-GATEWAY-MIB", "cegCongestionLowNotifEnable"), ("CISCO-EPC-GATEWAY-MIB", "cegCongestionClearNotifEnable"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    cegOverloadProtectionNotifMgmtGrp = cegOverloadProtectionNotifMgmtGrp.setStatus('current')
if mibBuilder.loadTexts: cegOverloadProtectionNotifMgmtGrp.setDescription('This group has a collection of objects which controls\n        the generation of congestion notification in the system.')
cegOverloadProtectionNotifGrp = NotificationGroup((1, 3, 6, 1, 4, 1, 9, 9, 731, 3, 2, 9)).setObjects(("CISCO-EPC-GATEWAY-MIB", "cegCongestionHighThresholdNotif"), ("CISCO-EPC-GATEWAY-MIB", "cegCongestionLowThresholdNotif"), ("CISCO-EPC-GATEWAY-MIB", "cegCongestionClearedNotif"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    cegOverloadProtectionNotifGrp = cegOverloadProtectionNotifGrp.setStatus('current')
if mibBuilder.loadTexts: cegOverloadProtectionNotifGrp.setDescription('This group has a collection of notification which informs\n        about the congestion level in the system.')
cegSystemStatusGrpSup1 = ObjectGroup((1, 3, 6, 1, 4, 1, 9, 9, 731, 3, 2, 10)).setObjects(("CISCO-EPC-GATEWAY-MIB", "cegActivatedIpv4v6Bearers"), ("CISCO-EPC-GATEWAY-MIB", "cegActivatedGtpv2SgwSessions"), ("CISCO-EPC-GATEWAY-MIB", "cegActivatedGtpv2PgwSessions"), ("CISCO-EPC-GATEWAY-MIB", "cegActivatedGtpv2SPgwSessions"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    cegSystemStatusGrpSup1 = cegSystemStatusGrpSup1.setStatus('current')
if mibBuilder.loadTexts: cegSystemStatusGrpSup1.setDescription('This group has objects to supplement the cegSystemStatusGrp.')
cegSystemStatusGrpSup2 = ObjectGroup((1, 3, 6, 1, 4, 1, 9, 9, 731, 3, 2, 11)).setObjects(("CISCO-EPC-GATEWAY-MIB", "cegActivatedBearers"), ("CISCO-EPC-GATEWAY-MIB", "cegActivatedDedicatedBearers"), ("CISCO-EPC-GATEWAY-MIB", "cegActivatedIpv4DedicatedBearers"), ("CISCO-EPC-GATEWAY-MIB", "cegActivatedIpv6DedicatedBearers"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    cegSystemStatusGrpSup2 = cegSystemStatusGrpSup2.setStatus('current')
if mibBuilder.loadTexts: cegSystemStatusGrpSup2.setDescription('This group has objects to supplement the cegSystemStatusGrp')
cegSystemStatusGrpSup3 = ObjectGroup((1, 3, 6, 1, 4, 1, 9, 9, 731, 3, 2, 12)).setObjects(("CISCO-EPC-GATEWAY-MIB", "cegTotalIdleSessions"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    cegSystemStatusGrpSup3 = cegSystemStatusGrpSup3.setStatus('current')
if mibBuilder.loadTexts: cegSystemStatusGrpSup3.setDescription('This group has a collection of objects which provides the\n        details of the EPC Gateway status and supplements the\n        cegSystemStatusGrp.')
cegBufferingAgentStatsGrpSup1 = ObjectGroup((1, 3, 6, 1, 4, 1, 9, 9, 731, 3, 2, 13)).setObjects(("CISCO-EPC-GATEWAY-MIB", "cegPacketDropDueToMaxPacketLimit"), ("CISCO-EPC-GATEWAY-MIB", "cegPacketDropDueToMaxBufferLimit"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    cegBufferingAgentStatsGrpSup1 = cegBufferingAgentStatsGrpSup1.setStatus('current')
if mibBuilder.loadTexts: cegBufferingAgentStatsGrpSup1.setDescription('This group has a collection of objects to provide the buffering\n        agent statistics related to packet drops based on max limit.')
mibBuilder.exportSymbols("CISCO-EPC-GATEWAY-MIB", PYSNMP_MODULE_ID=ciscoEpcGatewayMIB, cegActivatedBearers=cegActivatedBearers, cegActivatedDedicatedBearers=cegActivatedDedicatedBearers, cegActivatedGtpv2PgwSessions=cegActivatedGtpv2PgwSessions, cegActivatedGtpv2SPgwSessions=cegActivatedGtpv2SPgwSessions, cegActivatedGtpv2SgwSessions=cegActivatedGtpv2SgwSessions, cegActivatedIpv4Bearers=cegActivatedIpv4Bearers, cegActivatedIpv4DedicatedBearers=cegActivatedIpv4DedicatedBearers, cegActivatedIpv4v6Bearers=cegActivatedIpv4v6Bearers, cegActivatedIpv4v6Sessions=cegActivatedIpv4v6Sessions, cegActivatedIpv6Bearers=cegActivatedIpv6Bearers, cegActivatedIpv6DedicatedBearers=cegActivatedIpv6DedicatedBearers, cegBufferBytesDequeued=cegBufferBytesDequeued, cegBufferBytesEnqueued=cegBufferBytesEnqueued, cegBufferDiscardDataTime=cegBufferDiscardDataTime, cegBufferMaxPacketsPerBuffer=cegBufferMaxPacketsPerBuffer, cegBufferMaxSize=cegBufferMaxSize, cegBufferPacketsDequeued=cegBufferPacketsDequeued, cegBufferPacketsEnqueued=cegBufferPacketsEnqueued, cegBufferRejLowMem=cegBufferRejLowMem, cegBufferRejMemUnavailable=cegBufferRejMemUnavailable, cegBufferStats=cegBufferStats, cegBufferStatus=cegBufferStatus, cegBufferingAgentConfig=cegBufferingAgentConfig, cegBufferingAgentConfigGrp=cegBufferingAgentConfigGrp, cegBufferingAgentEnabled=cegBufferingAgentEnabled, cegBufferingAgentStatsGrp=cegBufferingAgentStatsGrp, cegBufferingAgentStatsGrpSup1=cegBufferingAgentStatsGrpSup1, cegBufferingAgentStatusGrp=cegBufferingAgentStatusGrp, cegBuffersCreated=cegBuffersCreated, cegBuffersDeleted=cegBuffersDeleted, cegBuffersTimedOut=cegBuffersTimedOut, cegCongestionClearNotifEnable=cegCongestionClearNotifEnable, cegCongestionClearedNotif=cegCongestionClearedNotif, cegCongestionDfpWeight=cegCongestionDfpWeight, cegCongestionHighLastDuration=cegCongestionHighLastDuration, cegCongestionHighLastOccurTime=cegCongestionHighLastOccurTime, cegCongestionHighNotifEnable=cegCongestionHighNotifEnable, cegCongestionHighThreshold=cegCongestionHighThreshold, cegCongestionHighThresholdNotif=cegCongestionHighThresholdNotif, cegCongestionHighThresholdReached=cegCongestionHighThresholdReached, cegCongestionIncomingReqDrops=cegCongestionIncomingReqDrops, cegCongestionLowLastDuration=cegCongestionLowLastDuration, cegCongestionLowLastOccurTime=cegCongestionLowLastOccurTime, cegCongestionLowNotifEnable=cegCongestionLowNotifEnable, cegCongestionLowThreshold=cegCongestionLowThreshold, cegCongestionLowThresholdNotif=cegCongestionLowThresholdNotif, cegCongestionLowThresholdReached=cegCongestionLowThresholdReached, cegCongestionStatus=cegCongestionStatus, cegOverloadProtectionConfig=cegOverloadProtectionConfig, cegOverloadProtectionConfigGrp=cegOverloadProtectionConfigGrp, cegOverloadProtectionNotifGrp=cegOverloadProtectionNotifGrp, cegOverloadProtectionNotifMgmtGrp=cegOverloadProtectionNotifMgmtGrp, cegOverloadProtectionStats=cegOverloadProtectionStats, cegOverloadProtectionStatsGrp=cegOverloadProtectionStatsGrp, cegOverloadProtectionStatus=cegOverloadProtectionStatus, cegOverloadProtectionStatusGrp=cegOverloadProtectionStatusGrp, cegPacketDropDueToMaxBufferLimit=cegPacketDropDueToMaxBufferLimit, cegPacketDropDueToMaxPacketLimit=cegPacketDropDueToMaxPacketLimit, cegSystemStatusGrp=cegSystemStatusGrp, cegSystemStatusGrpSup1=cegSystemStatusGrpSup1, cegSystemStatusGrpSup2=cegSystemStatusGrpSup2, cegSystemStatusGrpSup3=cegSystemStatusGrpSup3, cegTotalBufferAvailable=cegTotalBufferAvailable, cegTotalBufferedBytes=cegTotalBufferedBytes, cegTotalBufferedPackets=cegTotalBufferedPackets, cegTotalIdleSessions=cegTotalIdleSessions, cegTotalIdleUsers=cegTotalIdleUsers, cegTotalInUseBuffers=cegTotalInUseBuffers, cegTotalSuspendedUsers=cegTotalSuspendedUsers, cegTotalUsers=cegTotalUsers, cegVersion=cegVersion, ciscoEPCGatewayMIBComplianceRev2=ciscoEPCGatewayMIBComplianceRev2, ciscoEpcGatewayConfig=ciscoEpcGatewayConfig, ciscoEpcGatewayMIB=ciscoEpcGatewayMIB, ciscoEpcGatewayMIBCompliance=ciscoEpcGatewayMIBCompliance, ciscoEpcGatewayMIBComplianceRev1=ciscoEpcGatewayMIBComplianceRev1, ciscoEpcGatewayMIBComplianceRev3=ciscoEpcGatewayMIBComplianceRev3, ciscoEpcGatewayMIBCompliances=ciscoEpcGatewayMIBCompliances, ciscoEpcGatewayMIBConformance=ciscoEpcGatewayMIBConformance, ciscoEpcGatewayMIBGroups=ciscoEpcGatewayMIBGroups, ciscoEpcGatewayMIBNotifications=ciscoEpcGatewayMIBNotifications, ciscoEpcGatewayMIBObjects=ciscoEpcGatewayMIBObjects, ciscoEpcGatewayNotifMgmt=ciscoEpcGatewayNotifMgmt, ciscoEpcGatewayStatistics=ciscoEpcGatewayStatistics, ciscoEpcGatewayStatus=ciscoEpcGatewayStatus)
