#
# PySNMP MIB module CISCO-IETF-NAT-MIB (http://snmplabs.com/pysmi)
# ASN.1 source CISCO-IETF-NAT-MIB
# Source digest sha256:822b567dfd3399d957ca000f0d87badece810c33365989c4ff08c444e41b5812
# Produced by pysmi-2.3.0
#
Integer, ObjectIdentifier, OctetString = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
NamedValues, = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
ciscoExperiment, = mibBuilder.importSymbols("CISCO-SMI", "ciscoExperiment")
InterfaceIndex, = mibBuilder.importSymbols("IF-MIB", "InterfaceIndex")
SnmpAdminString, = mibBuilder.importSymbols("SNMP-FRAMEWORK-MIB", "SnmpAdminString")
ModuleCompliance, NotificationGroup, ObjectGroup = mibBuilder.importSymbols("SNMPv2-CONF", "ModuleCompliance", "NotificationGroup", "ObjectGroup")
Bits, Counter32, Counter64, Gauge32, Integer32, IpAddress, ModuleIdentity, MibIdentifier, NotificationType, ObjectIdentity, MibScalar, MibTable, MibTableRow, MibTableColumn, TimeTicks, Unsigned32, iso, mib_2 = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Counter32", "Counter64", "Gauge32", "Integer32", "IpAddress", "ModuleIdentity", "MibIdentifier", "NotificationType", "ObjectIdentity", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "TimeTicks", "Unsigned32", "iso", "mib-2")
DisplayString, RowStatus, StorageType, TextualConvention = mibBuilder.importSymbols("SNMPv2-TC", "DisplayString", "RowStatus", "StorageType", "TextualConvention")
ciscoIetfNatMIB = ModuleIdentity((1, 3, 6, 1, 4, 1, 9, 10, 77))
ciscoIetfNatMIB.setRevisions(('2001-03-01 00:00',))

if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    if mibBuilder.loadTexts: ciscoIetfNatMIB.setRevisionsDescriptions(('Initial version of this MIB module.',))
if mibBuilder.loadTexts: ciscoIetfNatMIB.setLastUpdated('2001-03-01 00:00')
if mibBuilder.loadTexts: ciscoIetfNatMIB.setOrganization('Cisco Systems, Inc')
if mibBuilder.loadTexts: ciscoIetfNatMIB.setContactInfo('       Cisco Systems\n                Customer Service\n\n        Postal:  170 West Tasman Drive\n                     San Jose, CA  95134\n                     USA\n\n            Tel:    +1 800 553-NETS\n\n            E-mail: cs-nat@cisco.com')
if mibBuilder.loadTexts: ciscoIetfNatMIB.setDescription('This MIB module defines the generic managed objects\n              for NAT.')
ciscoNatMIBObjects = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 10, 77, 1))
cnatConfig = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1))
cnatBind = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2))
cnatStatistics = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 3))
class NATProtocolType(TextualConvention, Integer32):
    description = 'A list of protocols that are affected by NAT.\n                Inclusion of values is not intended to imply that\n                those protocols need be supported.'
    status = 'current'
    subtypeSpec = Integer32.subtypeSpec + ConstraintsUnion(SingleValueConstraint(1, 2, 3, 4))
    namedValues = NamedValues(("other", 1), ("icmp", 2), ("udp", 3), ("tcp", 4))

cnatConfTable = MibTable((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 1), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cnatConfTable.setStatus('current')
if mibBuilder.loadTexts: cnatConfTable.setDescription('This table specifies the configuration attributes for a\n             device supporting NAT function.')
cnatConfEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 1, 1), ).setMaxAccess("notaccessible").setIndexNames((1, "CISCO-IETF-NAT-MIB", "cnatConfName"))
if mibBuilder.loadTexts: cnatConfEntry.setStatus('current')
if mibBuilder.loadTexts: cnatConfEntry.setDescription('Each entry in the cnatConfTable holds a set of\n             configuration parameters associated with an instance\n             of NAT.\n             Entries in the cnatConfTable are created and deleted\n             using the cnatConfStatus object.')
cnatConfName = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 1, 1, 1), SnmpAdminString().subtype(subtypeSpec=ValueSizeConstraint(1, 32))).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cnatConfName.setStatus('current')
if mibBuilder.loadTexts: cnatConfName.setDescription('The locally arbitrary, but unique identifier\n             associated with this cnatConfEntry.')
cnatConfServiceType = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 1, 1, 2), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3, 4, 5))).clone(namedValues=NamedValues(("basicNat", 1), ("napt", 2), ("bidirectionalNat", 3), ("twiceNat", 4), ("multihomedNat", 5)))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: cnatConfServiceType.setStatus('current')
if mibBuilder.loadTexts: cnatConfServiceType.setDescription('An indication of the direction in which new sessions\n             are permitted and the extent of translation done within\n             the IP and transport headers.')
cnatConfTimeoutIcmpIdle = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 1, 1, 3), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 2147483647)).clone(60)).setUnits('seconds').setMaxAccess("readcreate")
if mibBuilder.loadTexts: cnatConfTimeoutIcmpIdle.setStatus('current')
if mibBuilder.loadTexts: cnatConfTimeoutIcmpIdle.setDescription('The interval of time for which an ICMP protocol session,\n             associated with this configuration, is allowed to remain\n             valid without any activity.')
cnatConfTimeoutUdpIdle = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 1, 1, 4), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 2147483647)).clone(300)).setUnits('seconds').setMaxAccess("readcreate")
if mibBuilder.loadTexts: cnatConfTimeoutUdpIdle.setStatus('current')
if mibBuilder.loadTexts: cnatConfTimeoutUdpIdle.setDescription('The interval of time for which a UDP protocol session,\n             associated with this configuration, is allowed to remain\n             valid without any activity.')
cnatConfTimeoutTcpIdle = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 1, 1, 5), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 2147483647)).clone(86400)).setUnits('seconds').setMaxAccess("readcreate")
if mibBuilder.loadTexts: cnatConfTimeoutTcpIdle.setStatus('current')
if mibBuilder.loadTexts: cnatConfTimeoutTcpIdle.setDescription('The interval of time for which a TCP protocol session,\n             associated with this configuration, is allowed to remain\n             valid without any activity. This timeout value applies\n             to a TCP session during its data transfer phase.')
cnatConfTimeoutTcpNeg = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 1, 1, 6), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 2147483647)).clone(60)).setUnits('seconds').setMaxAccess("readcreate")
if mibBuilder.loadTexts: cnatConfTimeoutTcpNeg.setStatus('current')
if mibBuilder.loadTexts: cnatConfTimeoutTcpNeg.setDescription('The interval of time for which a TCP protocol session,\n             associated with this configuration, is allowed to remain\n             valid without any activity. This timeout value applies\n             to a TCP session during its establishment and termination\n             phases.')
cnatConfTimeoutOther = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 1, 1, 7), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 2147483647))).setUnits('seconds').setMaxAccess("readcreate")
if mibBuilder.loadTexts: cnatConfTimeoutOther.setStatus('current')
if mibBuilder.loadTexts: cnatConfTimeoutOther.setDescription('The interval of time for which a protocol session\n             other than ICMP, UDP and TCP, associated with this\n             configuration, is allowed to remain valid, without\n             any activity.')
cnatConfMaxBindLeaseTime = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 1, 1, 8), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 2147483647)).clone(0)).setUnits('seconds').setMaxAccess("readcreate")
if mibBuilder.loadTexts: cnatConfMaxBindLeaseTime.setStatus('current')
if mibBuilder.loadTexts: cnatConfMaxBindLeaseTime.setDescription('The maximum lease time for the BIND, associated with\n             this configuration. Unless the lease time is renewed, a\n             BIND will not be valid past the lease time. As a special\n             case, a value of 0 may be assumed to indicate no lease\n             time limit. Typically, this attribute is of relevance\n             only in conjunction with Realm-Specific-IP (RSIP)\n             operation.')
cnatConfMaxBindIdleTime = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 1, 1, 9), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 2147483647)).clone(0)).setUnits('seconds').setMaxAccess("readcreate")
if mibBuilder.loadTexts: cnatConfMaxBindIdleTime.setStatus('current')
if mibBuilder.loadTexts: cnatConfMaxBindIdleTime.setDescription('The maximum time, associated with this configuration,\n             to allow a dynamic BIND to remain valid with no NAT\n             session hanging off this BIND. By default for NATIVE\n             NAT maximum Idle time is 0. External agents could\n             control this parameter differently. Static Binds and\n             lease time limited BINDs are not affected by this\n             parameter.')
cnatConfStorageType = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 1, 1, 10), StorageType().clone('nonVolatile')).setMaxAccess("readcreate")
if mibBuilder.loadTexts: cnatConfStorageType.setReference('Textual Conventions for SMIv2, Section 2.')
if mibBuilder.loadTexts: cnatConfStorageType.setStatus('current')
if mibBuilder.loadTexts: cnatConfStorageType.setDescription('The storage type for this conceptual row.')
cnatConfStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 1, 1, 11), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: cnatConfStatus.setStatus('current')
if mibBuilder.loadTexts: cnatConfStatus.setDescription('The status of this conceptual row.')
cnatConfStaticAddrMapTable = MibTable((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 2), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cnatConfStaticAddrMapTable.setStatus('current')
if mibBuilder.loadTexts: cnatConfStaticAddrMapTable.setDescription('This table lists configuration for static NAT\n             entries. This table has an expansion dependent\n             relationship on the cnatConfTable. When an SNMP entity\n             deletes a conceptual row from the cnatConfTable, then\n             the corresponding entries are deleted from\n             cnatConfStaticAddrMapTable.')
cnatConfStaticAddrMapEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 2, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "CISCO-IETF-NAT-MIB", "cnatConfName"), (0, "CISCO-IETF-NAT-MIB", "cnatConfStaticAddrMapName"))
if mibBuilder.loadTexts: cnatConfStaticAddrMapEntry.setStatus('current')
if mibBuilder.loadTexts: cnatConfStaticAddrMapEntry.setDescription('A description of a static NAT entry. This entry\n             contributes to the static NAT table of the device.')
cnatConfStaticAddrMapName = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 2, 1, 1), SnmpAdminString().subtype(subtypeSpec=ValueSizeConstraint(1, 32))).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cnatConfStaticAddrMapName.setStatus('current')
if mibBuilder.loadTexts: cnatConfStaticAddrMapName.setDescription('An arbitrary, but unique identifier associated with this\n             cnatConfStaticAddrMapEntry. The value of this object is\n             unique across both the static address map and the dynamic\n             address map tables.')
cnatConfStaticAddrMapType = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 2, 1, 2), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3))).clone(namedValues=NamedValues(("inbound", 1), ("outbound", 2), ("both", 3)))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: cnatConfStaticAddrMapType.setStatus('current')
if mibBuilder.loadTexts: cnatConfStaticAddrMapType.setDescription('Address (and Transport-ID) maps may be defined for both\n             inbound and outbound direction. Outbound address map\n             refers to mapping a selected set of addresses from\n             private realm to a selected set of addresses in external\n             realm; whereas inbound address map refers to mapping a\n             set of addresses from the external realm to private\n             realm.')
cnatConfStaticLocalAddrFrom = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 2, 1, 3), IpAddress()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: cnatConfStaticLocalAddrFrom.setStatus('current')
if mibBuilder.loadTexts: cnatConfStaticLocalAddrFrom.setDescription('This object specifies the first IP address of the range\n             of IP addresses mapped by this translation entry.')
cnatConfStaticLocalAddrTo = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 2, 1, 4), IpAddress()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: cnatConfStaticLocalAddrTo.setStatus('current')
if mibBuilder.loadTexts: cnatConfStaticLocalAddrTo.setDescription('This object specifies the last IP address of the range of\n             IP addresses mapped by this translation entry. If only\n             a single address being mapped, the value of this object\n             is equal to the value of cnatConfStaticLocalAddrFrom. The\n             number addresses in the range defined by\n             cnatConfStaticLocalAddrFrom and cnatConfStaticLocalAddrTo\n             should be equal to the number of addresses in the range\n             defined by cnatConfStaticGlobalAddrFrom and\n             cnatConfStaticGlobalAddrTo.')
cnatConfStaticLocalPortFrom = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 2, 1, 5), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 65535))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: cnatConfStaticLocalPortFrom.setStatus('current')
if mibBuilder.loadTexts: cnatConfStaticLocalPortFrom.setDescription("If this conceptual row describes a basic NAT, then the\n             value of this object is '0'. If this conceptual row\n             describes NAPT, then the value of this object specifies\n             the first port number in the range of ports being\n             mapped. If the translation specifies a single port, then\n             the value of this object is equal to the value of\n             cnatConfStaticLocalPortTo.")
cnatConfStaticLocalPortTo = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 2, 1, 6), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 65535))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: cnatConfStaticLocalPortTo.setStatus('current')
if mibBuilder.loadTexts: cnatConfStaticLocalPortTo.setDescription("If this conceptual row describes a basic NAT, then the\n             value of this object is '0'. If this conceptual row\n             describes NAPT, then the value of this object specifies\n             the last port number in the range of ports being mapped.\n             If the translation specifies a single port, then the\n             value of this object is equal to the value of\n             cnatConfStaticLocalPortFrom.")
cnatConfStaticGlobalAddrFrom = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 2, 1, 7), IpAddress()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: cnatConfStaticGlobalAddrFrom.setStatus('current')
if mibBuilder.loadTexts: cnatConfStaticGlobalAddrFrom.setDescription('This object specifies the first IP address of the range of\n             IP addresses being mapped to.')
cnatConfStaticGlobalAddrTo = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 2, 1, 8), IpAddress()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: cnatConfStaticGlobalAddrTo.setStatus('current')
if mibBuilder.loadTexts: cnatConfStaticGlobalAddrTo.setDescription('This object specifies the last IP address of the range of\n             IP addresses being mapped to. If only a single address is\n             being mapped to, the value of this object is equal to the\n             value of cnatConfStaticGlobalAddrFrom.The number addresses\n             in the range defined by cnatConfStaticGlobalAddrFrom and\n             cnatConfStaticGlobalAddrTo should be equal to the number\n             of addresses in the range defined by\n             cnatConfStaticLocalAddrFrom and\n             cnatConfStaticLocalAddrTo. ')
cnatConfStaticGlobalPortFrom = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 2, 1, 9), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 65535))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: cnatConfStaticGlobalPortFrom.setStatus('current')
if mibBuilder.loadTexts: cnatConfStaticGlobalPortFrom.setDescription("If this conceptual row describes a basic  NAT, then the\n             value of this object is '0'. If this conceptual row\n             describes NAPT, then the value of this object specifies\n             the first port number in the range of ports being mapped\n             to. If the translation specifies a single port, then the\n             value of this object is equal to the value\n             cnatConfStaticGlobalPortTo.")
cnatConfStaticGlobalPortTo = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 2, 1, 10), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 65535))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: cnatConfStaticGlobalPortTo.setStatus('current')
if mibBuilder.loadTexts: cnatConfStaticGlobalPortTo.setDescription("If this conceptual row describes a basic NAT, then the\n             value of this object is '0'. If this conceptual describes\n             NAPT, then the value of this object specifies the last\n             port number in the range of ports being to. If the\n             translation specifies a single port, then the value of\n             this object is equal to the value of\n             cnatConfStaticGlobalPortFrom.")
cnatConfStaticProtocol = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 2, 1, 11), Bits().clone(namedValues=NamedValues(("all", 0), ("other", 1), ("icmp", 2), ("udp", 3), ("tcp", 4)))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: cnatConfStaticProtocol.setStatus('current')
if mibBuilder.loadTexts: cnatConfStaticProtocol.setDescription("This object specifies a protocol identifier. If the\n             value of this object is '0', then this basic NAT entry\n             applies to all IP traffic. If the value of this object\n             is non-zero, then this NAT entry only applies to IP\n             traffic with the specified protocol.")
cnatConfStaticAddrMapStorageType = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 2, 1, 12), StorageType().clone('nonVolatile')).setMaxAccess("readcreate")
if mibBuilder.loadTexts: cnatConfStaticAddrMapStorageType.setReference('Textual Conventions for SMIv2, Section 2.')
if mibBuilder.loadTexts: cnatConfStaticAddrMapStorageType.setStatus('current')
if mibBuilder.loadTexts: cnatConfStaticAddrMapStorageType.setDescription('The storage type for this conceptual row.')
cnatConfStaticAddrMapStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 2, 1, 13), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: cnatConfStaticAddrMapStatus.setStatus('current')
if mibBuilder.loadTexts: cnatConfStaticAddrMapStatus.setDescription('The status of this conceptual row.\n\n             To create a row in this table, a manager must set this\n             object to either createAndGo(4) or createAndWait(5).')
cnatConfDynAddrMapTable = MibTable((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 3), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cnatConfDynAddrMapTable.setStatus('current')
if mibBuilder.loadTexts: cnatConfDynAddrMapTable.setDescription('This table lists dynamic NAT entries. This table has an\n             expansion dependent relationship on the cnatConfTable.\n             When an SNMP entity deletes a conceptual row from the\n             cnatConfTable, then the corresponding entries are deleted\n             from cnatConfDynAddrMapTable.')
cnatConfDynAddrMapEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 3, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "CISCO-IETF-NAT-MIB", "cnatConfName"), (0, "CISCO-IETF-NAT-MIB", "cnatConfDynAddrMapName"))
if mibBuilder.loadTexts: cnatConfDynAddrMapEntry.setStatus('current')
if mibBuilder.loadTexts: cnatConfDynAddrMapEntry.setDescription('A description of a dynamic NAT entry. This entry\n             contributes to the dynamic NAT table of the device.')
cnatConfDynAddrMapName = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 3, 1, 1), SnmpAdminString().subtype(subtypeSpec=ValueSizeConstraint(1, 32))).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cnatConfDynAddrMapName.setStatus('current')
if mibBuilder.loadTexts: cnatConfDynAddrMapName.setDescription('An arbitrary, but unique identifier associated with this\n             cnatConfDynAddrMapEntry. The value of this object is\n             unique across both the static address map and the dynamic\n             address map tables.')
cnatConfDynAddressMapType = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 3, 1, 2), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3))).clone(namedValues=NamedValues(("inbound", 1), ("outbound", 2), ("both", 3)))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: cnatConfDynAddressMapType.setStatus('current')
if mibBuilder.loadTexts: cnatConfDynAddressMapType.setDescription('Address (and Transport-ID) maps may be defined for both\n             inbound and outbound direction. Outbound address map\n             refers to mapping a selected set of addresses from\n             private realm to a selected set of addresses in external\n             realm; whereas inbound address map refers to mapping a\n             set of addresses from the external realm to private\n             realm.')
cnatConfDynLocalAddrFrom = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 3, 1, 3), IpAddress()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: cnatConfDynLocalAddrFrom.setStatus('current')
if mibBuilder.loadTexts: cnatConfDynLocalAddrFrom.setDescription('This object specifies the first IP address of the range\n             of IP addresses mapped by this translation entry.')
cnatConfDynLocalAddrTo = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 3, 1, 4), IpAddress()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: cnatConfDynLocalAddrTo.setStatus('current')
if mibBuilder.loadTexts: cnatConfDynLocalAddrTo.setDescription('This object specifies the last IP address of the range of\n             IP addresses mapped by this translation entry.')
cnatConfDynLocalPortFrom = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 3, 1, 5), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 65535))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: cnatConfDynLocalPortFrom.setStatus('current')
if mibBuilder.loadTexts: cnatConfDynLocalPortFrom.setDescription("If this conceptual row describes a basic NAT, then the\n             value of this object is '0'. If this conceptual row\n             describes NAPT, then the value of this object specifies\n             the first port number in the range of ports being mapped.\n             If the translation specifies a single port, then the\n             value of this object is equal to the value of\n             cnatConfDynLocalPortTo.")
cnatConfDynLocalPortTo = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 3, 1, 6), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 65535))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatConfDynLocalPortTo.setStatus('current')
if mibBuilder.loadTexts: cnatConfDynLocalPortTo.setDescription("If this conceptual row describes a basic NAT, then the\n             value of this object is '0'. If this conceptual row\n             describes NAPT, then the value of this object specifies\n             the last port number in the range of ports being mapped.\n             If the translation specifies a single port, then the\n             value of this object is equal to the value of\n             cnatConfDynLocalPortFrom.")
cnatConfDynGlobalAddrFrom = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 3, 1, 7), IpAddress()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: cnatConfDynGlobalAddrFrom.setStatus('current')
if mibBuilder.loadTexts: cnatConfDynGlobalAddrFrom.setDescription('This object specifies the first IP address of the range\n             of IP addresses being mapped to.')
cnatConfDynGlobalAddrTo = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 3, 1, 8), IpAddress()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: cnatConfDynGlobalAddrTo.setStatus('current')
if mibBuilder.loadTexts: cnatConfDynGlobalAddrTo.setDescription('This object specifies the last IP address of the range of\n             IP addresses being mapped to.')
cnatConfDynGlobalPortFrom = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 3, 1, 9), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 65535))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: cnatConfDynGlobalPortFrom.setStatus('current')
if mibBuilder.loadTexts: cnatConfDynGlobalPortFrom.setDescription("If this conceptual row describes a basic  NAT, then the\n             value of this object is '0'. If this conceptual row\n             describes NAPT, then the value of this object specifies\n             the first port number in the range of ports being mapped\n             to. If the translation specifies a single port, then the\n             value of this object is equal to the value of\n             cnatConfDynGlobalPortTo.")
cnatConfDynGlobalPortTo = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 3, 1, 10), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 65535))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: cnatConfDynGlobalPortTo.setStatus('current')
if mibBuilder.loadTexts: cnatConfDynGlobalPortTo.setDescription("If this conceptual row describes a basic NAT, then the\n             value of this object is '0'. If this conceptual row\n             describes NAPT, then the value of this object specifies\n             the last port number in the range of ports being mapped\n             to. If the translation specifies a single port, then the\n             value of this object is equal to the value of\n             cnatConfDynGlobalPortFrom.")
cnatConfDynProtocol = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 3, 1, 11), Bits().clone(namedValues=NamedValues(("all", 0), ("other", 1), ("icmp", 2), ("udp", 3), ("tcp", 4)))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: cnatConfDynProtocol.setStatus('current')
if mibBuilder.loadTexts: cnatConfDynProtocol.setDescription("This object specifies a protocol identifier. If the\n             value of this object is '0', then this basic NAT entry\n             applies to all IP traffic. If the value of this object is\n             non-zero, then this NAT entry only applies to IP traffic\n             with the specified protocol.")
cnatConfDynAddrMapStorageType = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 3, 1, 12), StorageType().clone('nonVolatile')).setMaxAccess("readcreate")
if mibBuilder.loadTexts: cnatConfDynAddrMapStorageType.setReference('Textual Conventions for SMIv2, Section 2.')
if mibBuilder.loadTexts: cnatConfDynAddrMapStorageType.setStatus('current')
if mibBuilder.loadTexts: cnatConfDynAddrMapStorageType.setDescription('The storage type for this conceptual row.')
cnatConfDynAddrMapStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 3, 1, 13), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: cnatConfDynAddrMapStatus.setStatus('current')
if mibBuilder.loadTexts: cnatConfDynAddrMapStatus.setDescription('The status of this conceptual row.\n\n             To create a row in this table, a manager must set this\n             object to either createAndGo(4) or createAndWait(5).')
cnatInterfaceTable = MibTable((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 4), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cnatInterfaceTable.setStatus('current')
if mibBuilder.loadTexts: cnatInterfaceTable.setDescription('This table holds information regarding the interface\n             on which NAT is enabled.')
cnatInterfaceEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 4, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "CISCO-IETF-NAT-MIB", "cnatInterfaceIndex"))
if mibBuilder.loadTexts: cnatInterfaceEntry.setStatus('current')
if mibBuilder.loadTexts: cnatInterfaceEntry.setDescription('Each entry in the NAT Interface Table holds\n             information regarding an interface on which NAT is\n             enabled.')
cnatInterfaceIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 4, 1, 1), InterfaceIndex()).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cnatInterfaceIndex.setStatus('current')
if mibBuilder.loadTexts: cnatInterfaceIndex.setDescription('The ifIndex of the interface on which NAT is enabled.')
cnatInterfaceRealm = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 4, 1, 2), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("private", 1), ("public", 2))).clone('public')).setMaxAccess("readcreate")
if mibBuilder.loadTexts: cnatInterfaceRealm.setStatus('current')
if mibBuilder.loadTexts: cnatInterfaceRealm.setDescription('This object identifies whether this interface is\n             connected to the private or the public realm.')
cnatInterfaceStorageType = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 4, 1, 3), StorageType().clone('nonVolatile')).setMaxAccess("readcreate")
if mibBuilder.loadTexts: cnatInterfaceStorageType.setReference('Textual Conventions for SMIv2, Section 2.')
if mibBuilder.loadTexts: cnatInterfaceStorageType.setStatus('current')
if mibBuilder.loadTexts: cnatInterfaceStorageType.setDescription('The storage type for this conceptual row.')
cnatInterfaceStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 1, 4, 1, 4), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: cnatInterfaceStatus.setStatus('current')
if mibBuilder.loadTexts: cnatInterfaceStatus.setDescription('Status of NAT on this interface. An active status\n             indicates that NAT is enabled on this interface.')
cnatAddrBindNumberOfEntries = MibScalar((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 1), Gauge32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatAddrBindNumberOfEntries.setStatus('current')
if mibBuilder.loadTexts: cnatAddrBindNumberOfEntries.setDescription('This object maintains a count of the number of entries\n             that currently exist in the cnatAddrBindTable.')
cnatAddrBindTable = MibTable((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 2), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cnatAddrBindTable.setStatus('current')
if mibBuilder.loadTexts: cnatAddrBindTable.setDescription('This table holds information about the currently\n             active NAT BINDs.')
cnatAddrBindEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 2, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "CISCO-IETF-NAT-MIB", "cnatAddrBindLocalAddr"))
if mibBuilder.loadTexts: cnatAddrBindEntry.setStatus('current')
if mibBuilder.loadTexts: cnatAddrBindEntry.setDescription('Each entry in the NAT BIND table holds information\n             about a NAT BIND that is currently active.')
cnatAddrBindLocalAddr = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 2, 1, 1), IpAddress()).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cnatAddrBindLocalAddr.setStatus('current')
if mibBuilder.loadTexts: cnatAddrBindLocalAddr.setDescription('This object represents the private-realm specific network\n             layer address, which maps to the public-realm address\n             represented by cnatAddrBindGlobalAddr.')
cnatAddrBindGlobalAddr = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 2, 1, 2), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatAddrBindGlobalAddr.setStatus('current')
if mibBuilder.loadTexts: cnatAddrBindGlobalAddr.setDescription('This object represents the public-realm network layer\n             address that maps to the private-realm network layer\n             address represented by cnatAddrBindLocalAddr.')
cnatAddrBindId = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 2, 1, 3), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatAddrBindId.setStatus('current')
if mibBuilder.loadTexts: cnatAddrBindId.setDescription('This object represents a BIND id that is dynamically\n             assigned to each BIND by a NAT enabled device. Each\n             BIND is represented by a unique BIND id across both,\n             the Address bind and Address-Port bind tables.')
cnatAddrBindDirection = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 2, 1, 4), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("uniDirectional", 1), ("biDirectional", 2)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatAddrBindDirection.setStatus('current')
if mibBuilder.loadTexts: cnatAddrBindDirection.setDescription('This object represents the direction of the BIND. A\n             BIND may be either uni-directional or bi-directional,\n             same as the orientation of the address map, based on\n             which this bind is formed. The direction of this bind\n             is with reference to the private realm.')
cnatAddrBindType = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 2, 1, 5), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("static", 1), ("dynamic", 2)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatAddrBindType.setStatus('current')
if mibBuilder.loadTexts: cnatAddrBindType.setDescription('This object indicates whether the BIND is static or\n             dynamic.')
cnatAddrBindConfName = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 2, 1, 6), SnmpAdminString().subtype(subtypeSpec=ValueSizeConstraint(1, 32))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatAddrBindConfName.setStatus('current')
if mibBuilder.loadTexts: cnatAddrBindConfName.setDescription('This object is a pointer to the cnatConfTable entry (and\n             the parameters of that entry) which was used in creating\n             this BIND.')
cnatAddrBindSessionCount = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 2, 1, 7), Gauge32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatAddrBindSessionCount.setStatus('current')
if mibBuilder.loadTexts: cnatAddrBindSessionCount.setDescription('Number of sessions currently using this BIND.')
cnatAddrBindCurrentIdleTime = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 2, 1, 8), TimeTicks()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatAddrBindCurrentIdleTime.setStatus('current')
if mibBuilder.loadTexts: cnatAddrBindCurrentIdleTime.setDescription('At any given instance of time, this object indicates the\n             time that this BIND has been idle with no sessions\n             attached to it. The value represented by this object is\n             of relevance only when the value of Maximum Idle time\n             (cnatConfMaxBindIdleTime) is non-zero.')
cnatAddrBindInTranslate = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 2, 1, 9), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatAddrBindInTranslate.setStatus('current')
if mibBuilder.loadTexts: cnatAddrBindInTranslate.setDescription('The number of inbound packets that were translated as per\n             this BIND entry.')
cnatAddrBindOutTranslate = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 2, 1, 10), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatAddrBindOutTranslate.setStatus('current')
if mibBuilder.loadTexts: cnatAddrBindOutTranslate.setDescription('The number of outbound packets that were translated as\n             per this BIND entry.')
cnatAddrPortBindNumberOfEntries = MibScalar((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 3), Gauge32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatAddrPortBindNumberOfEntries.setStatus('current')
if mibBuilder.loadTexts: cnatAddrPortBindNumberOfEntries.setDescription('This object maintains a count of the number of entries\n             that currently exist in the cnatAddrPortBindTable.')
cnatAddrPortBindTable = MibTable((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 4), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cnatAddrPortBindTable.setStatus('current')
if mibBuilder.loadTexts: cnatAddrPortBindTable.setDescription('This table holds information about the currently\n             active NAPT BINDs.')
cnatAddrPortBindEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 4, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "CISCO-IETF-NAT-MIB", "cnatAddrPortBindLocalAddr"), (0, "CISCO-IETF-NAT-MIB", "cnatAddrPortBindLocalPort"), (0, "CISCO-IETF-NAT-MIB", "cnatAddrPortBindProtocol"))
if mibBuilder.loadTexts: cnatAddrPortBindEntry.setStatus('current')
if mibBuilder.loadTexts: cnatAddrPortBindEntry.setDescription('Each entry in the this table holds information\n             a NAPT BIND that is currently active.')
cnatAddrPortBindLocalAddr = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 4, 1, 1), IpAddress()).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cnatAddrPortBindLocalAddr.setStatus('current')
if mibBuilder.loadTexts: cnatAddrPortBindLocalAddr.setDescription('This object represents the private-realm specific network\n             layer address which, in conjunction with\n             cnatAddrPortBindLocalPort, maps to the public-realm\n             network layer address and transport id represented by\n             cnatAddrPortBindGlobalAddr and cnatAddrPortBindGlobalPort\n             respectively.')
cnatAddrPortBindLocalPort = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 4, 1, 2), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 65535))).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cnatAddrPortBindLocalPort.setStatus('current')
if mibBuilder.loadTexts: cnatAddrPortBindLocalPort.setDescription('This object represents the private-realm specific port\n             number (or query ID in case of ICMP messages) which, in\n             conjunction with cnatAddrPortBindLocalAddr, maps to the\n             public-realm network layer address and transport id\n             represented by cnatAddrPortBindGlobalAddr and\n             cnatAddrPortBindGlobalPort respectively.')
cnatAddrPortBindProtocol = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 4, 1, 3), Bits().clone(namedValues=NamedValues(("all", 0), ("other", 1), ("icmp", 2), ("udp", 3), ("tcp", 4)))).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cnatAddrPortBindProtocol.setStatus('current')
if mibBuilder.loadTexts: cnatAddrPortBindProtocol.setDescription("This object specifies a protocol identifier. If the\n             value of this object is '0', then this BIND entry\n             applies to all IP traffic. If the value of this object is\n             non-zero, then this NAT entry only applies to IP traffic\n             with the specified protocol.")
cnatAddrPortBindGlobalAddr = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 4, 1, 4), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatAddrPortBindGlobalAddr.setStatus('current')
if mibBuilder.loadTexts: cnatAddrPortBindGlobalAddr.setDescription('This object represents the public-realm specific network\n             layer address that, in conjunction with\n             cnatAddrPortBindGlobalPort, maps to the private-realm\n             network layer address and transport id represented by\n             cnatAddrPortBindLocalAddr and cnatAddrPortBindLocalPort\n             respectively.')
cnatAddrPortBindGlobalPort = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 4, 1, 5), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 65535))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatAddrPortBindGlobalPort.setStatus('current')
if mibBuilder.loadTexts: cnatAddrPortBindGlobalPort.setDescription('This object represents the port number (or query id in\n             case of ICMP) that, in conjunction with\n             cnatAddrPortBindGlobalAddr, maps to the private-realm\n             network layer address and transport id represented by\n             cnatAddrPortBindLocalAddr and cnatAddrPortBindLocalPort\n             respectively.')
cnatAddrPortBindId = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 4, 1, 6), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatAddrPortBindId.setStatus('current')
if mibBuilder.loadTexts: cnatAddrPortBindId.setDescription('This object represents a BIND id that is dynamically\n             assigned to each BIND by a NAT enabled device. Each\n             BIND is represented by a unique BIND id across both,\n             the Address Bind and Address-Port Bind tables.')
cnatAddrPortBindDirection = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 4, 1, 7), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("uniDirectional", 1), ("biDirectional", 2)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatAddrPortBindDirection.setStatus('current')
if mibBuilder.loadTexts: cnatAddrPortBindDirection.setDescription('This object represents the direction of the BIND. A\n             BIND may be either uni-directional or bi-directional,\n             same as the orientation of the address map, based on\n             which this bind is formed. The direction of this bind\n             is with reference to the private realm.')
cnatAddrPortBindType = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 4, 1, 8), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("static", 1), ("dynamic", 2)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatAddrPortBindType.setStatus('current')
if mibBuilder.loadTexts: cnatAddrPortBindType.setDescription('This object indicates whether the BIND is static or\n             dynamic.')
cnatAddrPortBindConfName = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 4, 1, 9), SnmpAdminString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatAddrPortBindConfName.setStatus('current')
if mibBuilder.loadTexts: cnatAddrPortBindConfName.setDescription('This object is a pointer to the cnatConfTable entry (and\n             the parameters of that entry) which was used in creating\n             this BIND.')
cnatAddrPortBindSessionCount = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 4, 1, 10), Gauge32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatAddrPortBindSessionCount.setStatus('current')
if mibBuilder.loadTexts: cnatAddrPortBindSessionCount.setDescription('Number of sessions currently using this BIND.')
cnatAddrPortBindCurrentIdleTime = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 4, 1, 11), TimeTicks()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatAddrPortBindCurrentIdleTime.setStatus('current')
if mibBuilder.loadTexts: cnatAddrPortBindCurrentIdleTime.setDescription('At any given instance of time, this object indicates the\n             time that this BIND has been idle with no sessions\n             attached to it. The value represented by this object is\n             of relevance only when the value of Maximum Idle time\n             (cnatConfMaxBindIdleTime) is non-zero.')
cnatAddrPortBindInTranslate = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 4, 1, 12), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatAddrPortBindInTranslate.setStatus('current')
if mibBuilder.loadTexts: cnatAddrPortBindInTranslate.setDescription('The number of inbound packets that were translated as per\n             this BIND entry.')
cnatAddrPortBindOutTranslate = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 4, 1, 13), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatAddrPortBindOutTranslate.setStatus('current')
if mibBuilder.loadTexts: cnatAddrPortBindOutTranslate.setDescription('The number of outbound packets that were translated as per\n             this BIND entry.')
cnatSessionTable = MibTable((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 5), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cnatSessionTable.setStatus('current')
if mibBuilder.loadTexts: cnatSessionTable.setDescription('The (conceptual) table containing one entry for each\n             NAT session currently active on this NAT device.')
cnatSessionEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 5, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "CISCO-IETF-NAT-MIB", "cnatSessionBindId"), (0, "CISCO-IETF-NAT-MIB", "cnatSessionId"))
if mibBuilder.loadTexts: cnatSessionEntry.setStatus('current')
if mibBuilder.loadTexts: cnatSessionEntry.setDescription('An entry (conceptual row) containing information\n             about an active NAT session on this NAT device.')
cnatSessionBindId = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 5, 1, 1), Unsigned32()).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cnatSessionBindId.setStatus('current')
if mibBuilder.loadTexts: cnatSessionBindId.setDescription('This object represents a BIND id that is dynamically\n             assigned to each BIND by a NAT enabled device. This\n             bind id is that same as represented by the BindId\n             objects in the Address bind and Address-Port bind\n             tables.')
cnatSessionId = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 5, 1, 2), Unsigned32()).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cnatSessionId.setStatus('current')
if mibBuilder.loadTexts: cnatSessionId.setDescription('The session ID for this NAT session.')
cnatSessionDirection = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 5, 1, 3), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("inbound", 1), ("outbound", 2)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatSessionDirection.setStatus('current')
if mibBuilder.loadTexts: cnatSessionDirection.setDescription("The direction of this session with respect to the\n             local network. 'inbound' indicates that this session\n             was initiated from the public network into the private\n             network. 'outbound' indicates that this session was\n             initiated from the private network into the public\n             network.")
cnatSessionUpTime = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 5, 1, 4), TimeTicks()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatSessionUpTime.setStatus('current')
if mibBuilder.loadTexts: cnatSessionUpTime.setDescription('The up time of this session in one-hundredths of a\n             second.')
cnatSessionProtocolType = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 5, 1, 5), NATProtocolType()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatSessionProtocolType.setStatus('current')
if mibBuilder.loadTexts: cnatSessionProtocolType.setDescription('The protocol type of this session.\n\n             TCP and UDP sessions are uniquely identified by the\n             tuple of (source IP address, source UDP/TCP port,\n             destination IP address, destination TCP/UCP port).\n             ICMP query sessions are identified by the tuple of\n             (source IP address, ICMP query ID, destination IP\n             address).')
cnatSessionOrigPrivateAddr = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 5, 1, 6), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatSessionOrigPrivateAddr.setStatus('current')
if mibBuilder.loadTexts: cnatSessionOrigPrivateAddr.setDescription('The original IP address of the session endpoint that\n             lies in the private network.')
cnatSessionTransPrivateAddr = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 5, 1, 7), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatSessionTransPrivateAddr.setStatus('current')
if mibBuilder.loadTexts: cnatSessionTransPrivateAddr.setDescription('The translated IP address of the session endpoint that\n             lies in the private network. The value of this object\n             is equal to that of the original public IP Address\n             (cnatSessionOrigPrivateAddr) when there is no\n             translation.')
cnatSessionOrigPrivatePort = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 5, 1, 8), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 65535))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatSessionOrigPrivatePort.setStatus('current')
if mibBuilder.loadTexts: cnatSessionOrigPrivatePort.setDescription('The original transport port of the session endpoint that\n             belongs to the private network. If this is an ICMP session\n             then the value is the ICMP request ID.')
cnatSessionTransPrivatePort = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 5, 1, 9), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 65535))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatSessionTransPrivatePort.setStatus('current')
if mibBuilder.loadTexts: cnatSessionTransPrivatePort.setDescription('The translated transport port of the session that lies in\n             the private network. The value of this object is equal to\n             that of the original transport port\n             (cnatSessionOrigPrivatePort) when there is no translation.')
cnatSessionOrigPublicAddr = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 5, 1, 10), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatSessionOrigPublicAddr.setStatus('current')
if mibBuilder.loadTexts: cnatSessionOrigPublicAddr.setDescription('The original IP address of the session endpoint that lies\n             in the public network.')
cnatSessionTransPublicAddr = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 5, 1, 11), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatSessionTransPublicAddr.setStatus('current')
if mibBuilder.loadTexts: cnatSessionTransPublicAddr.setDescription('The translated IP address of the session endpoint that\n             belongs to the public network. The value of this object\n             is equal to that of the original public IP Address\n             (cnatSessionOrigPublicAddr) when there is no\n             translation.')
cnatSessionOrigPublicPort = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 5, 1, 12), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 65535))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatSessionOrigPublicPort.setStatus('current')
if mibBuilder.loadTexts: cnatSessionOrigPublicPort.setDescription('The original transport port of the session endpoint that\n             belongs to the public network. If this is an ICMP\n             session then the value contains the ICMP request ID.')
cnatSessionTransPublicPort = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 5, 1, 13), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 65535))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatSessionTransPublicPort.setStatus('current')
if mibBuilder.loadTexts: cnatSessionTransPublicPort.setDescription('The translated transport port of the session endpoint\n             that belongs to the public network. The value of this\n             object is equal to that of the original transport port\n             (cnatSessionOrigPublicPort) when there is no\n             translation.')
cnatSessionCurrentIdletime = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 5, 1, 14), TimeTicks()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatSessionCurrentIdletime.setStatus('current')
if mibBuilder.loadTexts: cnatSessionCurrentIdletime.setDescription('The time in one-hundredths of a second since a packet\n             belonging to this session was last detected.')
cnatSessionSecondBindId = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 5, 1, 15), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatSessionSecondBindId.setStatus('current')
if mibBuilder.loadTexts: cnatSessionSecondBindId.setDescription("The natBindId of the 'other' NAT binding incase of Twice\n             NAT. An instance of this object contains a valid value\n             only if the binding type for this session is TwiceNAT.")
cnatSessionInTranslate = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 5, 1, 16), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatSessionInTranslate.setStatus('current')
if mibBuilder.loadTexts: cnatSessionInTranslate.setDescription('The number of inbound packets that were translated by\n             this session.')
cnatSessionOutTranslate = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 2, 5, 1, 17), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatSessionOutTranslate.setStatus('current')
if mibBuilder.loadTexts: cnatSessionOutTranslate.setDescription('The number of outbound packets that were translated by\n             this session.')
cnatProtocolStatsTable = MibTable((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 3, 1), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cnatProtocolStatsTable.setStatus('current')
if mibBuilder.loadTexts: cnatProtocolStatsTable.setDescription('The (conceptual) table containing per protocol NAT\n             statistics.')
cnatProtocolStatsEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 3, 1, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "CISCO-IETF-NAT-MIB", "cnatProtocolStatsName"))
if mibBuilder.loadTexts: cnatProtocolStatsEntry.setStatus('current')
if mibBuilder.loadTexts: cnatProtocolStatsEntry.setDescription('An entry (conceptual row) containing NAT statistics\n             pertaining to a particular protocol.')
cnatProtocolStatsName = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 3, 1, 1, 1), NATProtocolType()).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cnatProtocolStatsName.setStatus('current')
if mibBuilder.loadTexts: cnatProtocolStatsName.setDescription('This object represents the protocol pertaining to which\n             statistics are reported.')
cnatProtocolStatsInTranslate = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 3, 1, 1, 2), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatProtocolStatsInTranslate.setStatus('current')
if mibBuilder.loadTexts: cnatProtocolStatsInTranslate.setDescription('The number of inbound packets, pertaining to the protocol\n             identified by cnatProtocolStatsName, that underwent NAT.')
cnatProtocolStatsOutTranslate = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 3, 1, 1, 3), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatProtocolStatsOutTranslate.setStatus('current')
if mibBuilder.loadTexts: cnatProtocolStatsOutTranslate.setDescription('The number of outbound packets, pertaining to the protocol\n             identified by cnatProtocolStatsName, that underwent NAT.')
cnatProtocolStatsRejectCount = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 3, 1, 1, 4), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatProtocolStatsRejectCount.setStatus('current')
if mibBuilder.loadTexts: cnatProtocolStatsRejectCount.setDescription('The number of packets, pertaining to the protocol\n             identified by cnatProtocolStatsName, that had to be\n             rejected/dropped due to lack of resources. These\n             rejections could be due to session timeout, resource\n             unavailability etc.')
cnatAddrMapStatsTable = MibTable((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 3, 2), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cnatAddrMapStatsTable.setStatus('current')
if mibBuilder.loadTexts: cnatAddrMapStatsTable.setDescription('The (conceptual) table containing per address map NAT\n             statistics.')
cnatAddrMapStatsEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 3, 2, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "CISCO-IETF-NAT-MIB", "cnatAddrMapStatsConfName"), (0, "CISCO-IETF-NAT-MIB", "cnatAddrMapStatsMapName"))
if mibBuilder.loadTexts: cnatAddrMapStatsEntry.setStatus('current')
if mibBuilder.loadTexts: cnatAddrMapStatsEntry.setDescription('An entry (conceptual row) containing NAT statistics per\n             address map.')
cnatAddrMapStatsConfName = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 3, 2, 1, 1), SnmpAdminString().subtype(subtypeSpec=ValueSizeConstraint(1, 32))).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cnatAddrMapStatsConfName.setStatus('current')
if mibBuilder.loadTexts: cnatAddrMapStatsConfName.setDescription('The name of the configuration (from the cnatConfTable),\n             regarding which statistics are being reported. The\n             configuration name along with Map name uniquely\n             identifies an entry across both (static and dynamic)\n             Address Map tables.')
cnatAddrMapStatsMapName = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 3, 2, 1, 2), SnmpAdminString().subtype(subtypeSpec=ValueSizeConstraint(1, 32))).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cnatAddrMapStatsMapName.setStatus('current')
if mibBuilder.loadTexts: cnatAddrMapStatsMapName.setDescription('The name of the Address Map (from the\n             cnatConfStaticAddrMapTable/cnatConfDynAddrMapTable),\n             regarding which statistics are being reported. The\n             configuration name along with Map name uniquely\n             identifies an entry across both (static and dynamic)\n             Address Map tables.')
cnatAddrMapStatsInTranslate = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 3, 2, 1, 3), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatAddrMapStatsInTranslate.setStatus('current')
if mibBuilder.loadTexts: cnatAddrMapStatsInTranslate.setDescription('The number of inbound packets, pertaining to this address\n             map entry, that were translated.')
cnatAddrMapStatsOutTranslate = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 3, 2, 1, 4), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatAddrMapStatsOutTranslate.setStatus('current')
if mibBuilder.loadTexts: cnatAddrMapStatsOutTranslate.setDescription('The number of outbound packets, pertaining to this\n             address map entry, that were translated.')
cnatAddrMapStatsNoResource = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 3, 2, 1, 5), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatAddrMapStatsNoResource.setStatus('current')
if mibBuilder.loadTexts: cnatAddrMapStatsNoResource.setDescription('The number of packets, pertaining to this address map\n             entry, that were dropped due to lack of addresses in the\n             address pool identified by this address map. The value of\n             this object should always be zero in case of static\n             address map.')
cnatAddrMapStatsAddrUsed = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 3, 2, 1, 6), Gauge32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatAddrMapStatsAddrUsed.setStatus('current')
if mibBuilder.loadTexts: cnatAddrMapStatsAddrUsed.setDescription('The number of addresses, pertaining to this address map,\n             that are currently being used from the nat pool. The\n             value of this object is irrelevant if the address map in\n             question is a static address map.')
cnatInterfaceStatsTable = MibTable((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 3, 3), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cnatInterfaceStatsTable.setStatus('current')
if mibBuilder.loadTexts: cnatInterfaceStatsTable.setDescription('This table augments the cnatInterfaceTable and provides\n             statistics information pertaining to the specified\n             interface.')
cnatInterfaceStatsEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 3, 3, 1), ).setMaxAccess("notaccessible")
cnatInterfaceEntry.registerAugmentions(("CISCO-IETF-NAT-MIB", "cnatInterfaceStatsEntry"))
cnatInterfaceStatsEntry.setIndexNames(*cnatInterfaceEntry.getIndexNames())
if mibBuilder.loadTexts: cnatInterfaceStatsEntry.setStatus('current')
if mibBuilder.loadTexts: cnatInterfaceStatsEntry.setDescription('Each entry of the cnatInterfaceStatsTable represents stats\n             pertaining to one interface, which is identified by its\n             ifIndex.')
cnatInterfacePktsIn = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 3, 3, 1, 1), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatInterfacePktsIn.setStatus('current')
if mibBuilder.loadTexts: cnatInterfacePktsIn.setDescription('Number of packets received on this interface that\n             were translated.')
cnatInterfacePktsOut = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 10, 77, 1, 3, 3, 1, 2), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cnatInterfacePktsOut.setStatus('current')
if mibBuilder.loadTexts: cnatInterfacePktsOut.setDescription('Number of translated packets that were sent out this\n             interface.')
ciscoNatMIBNotificationPrefix = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 10, 77, 2))
ciscoNatMIBNotifications = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 10, 77, 2, 0))
ciscoNatMIBConformance = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 10, 77, 3))
ciscoNatMIBCompliances = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 10, 77, 3, 1))
ciscoNatMIBGroups = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 10, 77, 3, 2))
ciscoNatMIBCompliance = ModuleCompliance((1, 3, 6, 1, 4, 1, 9, 10, 77, 3, 1, 1)).setObjects(("CISCO-IETF-NAT-MIB", "cnatConfigGroup"), ("CISCO-IETF-NAT-MIB", "cnatBindGroup"))

if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    ciscoNatMIBCompliance = ciscoNatMIBCompliance.setStatus('current')
if mibBuilder.loadTexts: ciscoNatMIBCompliance.setDescription('The compliance statement for devices running NAT.')
cnatConfigGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 9, 10, 77, 3, 2, 1)).setObjects(("CISCO-IETF-NAT-MIB", "cnatConfServiceType"), ("CISCO-IETF-NAT-MIB", "cnatConfTimeoutIcmpIdle"), ("CISCO-IETF-NAT-MIB", "cnatConfTimeoutUdpIdle"), ("CISCO-IETF-NAT-MIB", "cnatConfTimeoutTcpIdle"), ("CISCO-IETF-NAT-MIB", "cnatConfTimeoutTcpNeg"), ("CISCO-IETF-NAT-MIB", "cnatConfTimeoutOther"), ("CISCO-IETF-NAT-MIB", "cnatConfMaxBindLeaseTime"), ("CISCO-IETF-NAT-MIB", "cnatConfMaxBindIdleTime"), ("CISCO-IETF-NAT-MIB", "cnatConfStorageType"), ("CISCO-IETF-NAT-MIB", "cnatConfStatus"), ("CISCO-IETF-NAT-MIB", "cnatConfStaticAddrMapType"), ("CISCO-IETF-NAT-MIB", "cnatConfStaticLocalAddrFrom"), ("CISCO-IETF-NAT-MIB", "cnatConfStaticLocalAddrTo"), ("CISCO-IETF-NAT-MIB", "cnatConfStaticLocalPortFrom"), ("CISCO-IETF-NAT-MIB", "cnatConfStaticLocalPortTo"), ("CISCO-IETF-NAT-MIB", "cnatConfStaticGlobalAddrFrom"), ("CISCO-IETF-NAT-MIB", "cnatConfStaticGlobalAddrTo"), ("CISCO-IETF-NAT-MIB", "cnatConfStaticGlobalPortFrom"), ("CISCO-IETF-NAT-MIB", "cnatConfStaticGlobalPortTo"), ("CISCO-IETF-NAT-MIB", "cnatConfStaticProtocol"), ("CISCO-IETF-NAT-MIB", "cnatConfStaticAddrMapStorageType"), ("CISCO-IETF-NAT-MIB", "cnatConfStaticAddrMapStatus"), ("CISCO-IETF-NAT-MIB", "cnatConfDynAddressMapType"), ("CISCO-IETF-NAT-MIB", "cnatConfDynLocalAddrFrom"), ("CISCO-IETF-NAT-MIB", "cnatConfDynLocalAddrTo"), ("CISCO-IETF-NAT-MIB", "cnatConfDynLocalPortFrom"), ("CISCO-IETF-NAT-MIB", "cnatConfDynLocalPortTo"), ("CISCO-IETF-NAT-MIB", "cnatConfDynGlobalAddrFrom"), ("CISCO-IETF-NAT-MIB", "cnatConfDynGlobalAddrTo"), ("CISCO-IETF-NAT-MIB", "cnatConfDynGlobalPortFrom"), ("CISCO-IETF-NAT-MIB", "cnatConfDynGlobalPortTo"), ("CISCO-IETF-NAT-MIB", "cnatConfDynProtocol"), ("CISCO-IETF-NAT-MIB", "cnatConfDynAddrMapStorageType"), ("CISCO-IETF-NAT-MIB", "cnatConfDynAddrMapStatus"), ("CISCO-IETF-NAT-MIB", "cnatInterfaceRealm"), ("CISCO-IETF-NAT-MIB", "cnatInterfaceStorageType"), ("CISCO-IETF-NAT-MIB", "cnatInterfaceStatus"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    cnatConfigGroup = cnatConfigGroup.setStatus('current')
if mibBuilder.loadTexts: cnatConfigGroup.setDescription('A collection of configuration-related information\n             required to support management of devices supporting\n             NAT.')
cnatBindGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 9, 10, 77, 3, 2, 2)).setObjects(("CISCO-IETF-NAT-MIB", "cnatAddrBindNumberOfEntries"), ("CISCO-IETF-NAT-MIB", "cnatAddrBindGlobalAddr"), ("CISCO-IETF-NAT-MIB", "cnatAddrBindId"), ("CISCO-IETF-NAT-MIB", "cnatAddrBindDirection"), ("CISCO-IETF-NAT-MIB", "cnatAddrBindType"), ("CISCO-IETF-NAT-MIB", "cnatAddrBindConfName"), ("CISCO-IETF-NAT-MIB", "cnatAddrBindSessionCount"), ("CISCO-IETF-NAT-MIB", "cnatAddrBindCurrentIdleTime"), ("CISCO-IETF-NAT-MIB", "cnatAddrBindInTranslate"), ("CISCO-IETF-NAT-MIB", "cnatAddrBindOutTranslate"), ("CISCO-IETF-NAT-MIB", "cnatAddrPortBindNumberOfEntries"), ("CISCO-IETF-NAT-MIB", "cnatAddrPortBindGlobalAddr"), ("CISCO-IETF-NAT-MIB", "cnatAddrPortBindGlobalPort"), ("CISCO-IETF-NAT-MIB", "cnatAddrPortBindId"), ("CISCO-IETF-NAT-MIB", "cnatAddrPortBindDirection"), ("CISCO-IETF-NAT-MIB", "cnatAddrPortBindType"), ("CISCO-IETF-NAT-MIB", "cnatAddrPortBindConfName"), ("CISCO-IETF-NAT-MIB", "cnatAddrPortBindSessionCount"), ("CISCO-IETF-NAT-MIB", "cnatAddrPortBindCurrentIdleTime"), ("CISCO-IETF-NAT-MIB", "cnatAddrPortBindInTranslate"), ("CISCO-IETF-NAT-MIB", "cnatAddrPortBindOutTranslate"), ("CISCO-IETF-NAT-MIB", "cnatSessionDirection"), ("CISCO-IETF-NAT-MIB", "cnatSessionUpTime"), ("CISCO-IETF-NAT-MIB", "cnatSessionProtocolType"), ("CISCO-IETF-NAT-MIB", "cnatSessionOrigPrivateAddr"), ("CISCO-IETF-NAT-MIB", "cnatSessionTransPrivateAddr"), ("CISCO-IETF-NAT-MIB", "cnatSessionOrigPrivatePort"), ("CISCO-IETF-NAT-MIB", "cnatSessionTransPrivatePort"), ("CISCO-IETF-NAT-MIB", "cnatSessionOrigPublicAddr"), ("CISCO-IETF-NAT-MIB", "cnatSessionTransPublicAddr"), ("CISCO-IETF-NAT-MIB", "cnatSessionOrigPublicPort"), ("CISCO-IETF-NAT-MIB", "cnatSessionTransPublicPort"), ("CISCO-IETF-NAT-MIB", "cnatSessionCurrentIdletime"), ("CISCO-IETF-NAT-MIB", "cnatSessionSecondBindId"), ("CISCO-IETF-NAT-MIB", "cnatSessionInTranslate"), ("CISCO-IETF-NAT-MIB", "cnatSessionOutTranslate"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    cnatBindGroup = cnatBindGroup.setStatus('current')
if mibBuilder.loadTexts: cnatBindGroup.setDescription('A collection of BIND-related objects required to support\n             management of devices supporting NAT.')
cnatStatsGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 9, 10, 77, 3, 2, 3)).setObjects(("CISCO-IETF-NAT-MIB", "cnatProtocolStatsInTranslate"), ("CISCO-IETF-NAT-MIB", "cnatProtocolStatsOutTranslate"), ("CISCO-IETF-NAT-MIB", "cnatProtocolStatsRejectCount"), ("CISCO-IETF-NAT-MIB", "cnatAddrMapStatsInTranslate"), ("CISCO-IETF-NAT-MIB", "cnatAddrMapStatsOutTranslate"), ("CISCO-IETF-NAT-MIB", "cnatAddrMapStatsNoResource"), ("CISCO-IETF-NAT-MIB", "cnatAddrMapStatsAddrUsed"), ("CISCO-IETF-NAT-MIB", "cnatInterfacePktsIn"), ("CISCO-IETF-NAT-MIB", "cnatInterfacePktsOut"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    cnatStatsGroup = cnatStatsGroup.setStatus('current')
if mibBuilder.loadTexts: cnatStatsGroup.setDescription('A collection of NAT statistics related objects required\n             to support troubleshooting/monitoring NAT operation.')
mibBuilder.exportSymbols("CISCO-IETF-NAT-MIB", NATProtocolType=NATProtocolType, PYSNMP_MODULE_ID=ciscoIetfNatMIB, ciscoIetfNatMIB=ciscoIetfNatMIB, ciscoNatMIBCompliance=ciscoNatMIBCompliance, ciscoNatMIBCompliances=ciscoNatMIBCompliances, ciscoNatMIBConformance=ciscoNatMIBConformance, ciscoNatMIBGroups=ciscoNatMIBGroups, ciscoNatMIBNotificationPrefix=ciscoNatMIBNotificationPrefix, ciscoNatMIBNotifications=ciscoNatMIBNotifications, ciscoNatMIBObjects=ciscoNatMIBObjects, cnatAddrBindConfName=cnatAddrBindConfName, cnatAddrBindCurrentIdleTime=cnatAddrBindCurrentIdleTime, cnatAddrBindDirection=cnatAddrBindDirection, cnatAddrBindEntry=cnatAddrBindEntry, cnatAddrBindGlobalAddr=cnatAddrBindGlobalAddr, cnatAddrBindId=cnatAddrBindId, cnatAddrBindInTranslate=cnatAddrBindInTranslate, cnatAddrBindLocalAddr=cnatAddrBindLocalAddr, cnatAddrBindNumberOfEntries=cnatAddrBindNumberOfEntries, cnatAddrBindOutTranslate=cnatAddrBindOutTranslate, cnatAddrBindSessionCount=cnatAddrBindSessionCount, cnatAddrBindTable=cnatAddrBindTable, cnatAddrBindType=cnatAddrBindType, cnatAddrMapStatsAddrUsed=cnatAddrMapStatsAddrUsed, cnatAddrMapStatsConfName=cnatAddrMapStatsConfName, cnatAddrMapStatsEntry=cnatAddrMapStatsEntry, cnatAddrMapStatsInTranslate=cnatAddrMapStatsInTranslate, cnatAddrMapStatsMapName=cnatAddrMapStatsMapName, cnatAddrMapStatsNoResource=cnatAddrMapStatsNoResource, cnatAddrMapStatsOutTranslate=cnatAddrMapStatsOutTranslate, cnatAddrMapStatsTable=cnatAddrMapStatsTable, cnatAddrPortBindConfName=cnatAddrPortBindConfName, cnatAddrPortBindCurrentIdleTime=cnatAddrPortBindCurrentIdleTime, cnatAddrPortBindDirection=cnatAddrPortBindDirection, cnatAddrPortBindEntry=cnatAddrPortBindEntry, cnatAddrPortBindGlobalAddr=cnatAddrPortBindGlobalAddr, cnatAddrPortBindGlobalPort=cnatAddrPortBindGlobalPort, cnatAddrPortBindId=cnatAddrPortBindId, cnatAddrPortBindInTranslate=cnatAddrPortBindInTranslate, cnatAddrPortBindLocalAddr=cnatAddrPortBindLocalAddr, cnatAddrPortBindLocalPort=cnatAddrPortBindLocalPort, cnatAddrPortBindNumberOfEntries=cnatAddrPortBindNumberOfEntries, cnatAddrPortBindOutTranslate=cnatAddrPortBindOutTranslate, cnatAddrPortBindProtocol=cnatAddrPortBindProtocol, cnatAddrPortBindSessionCount=cnatAddrPortBindSessionCount, cnatAddrPortBindTable=cnatAddrPortBindTable, cnatAddrPortBindType=cnatAddrPortBindType, cnatBind=cnatBind, cnatBindGroup=cnatBindGroup, cnatConfDynAddrMapEntry=cnatConfDynAddrMapEntry, cnatConfDynAddrMapName=cnatConfDynAddrMapName, cnatConfDynAddrMapStatus=cnatConfDynAddrMapStatus, cnatConfDynAddrMapStorageType=cnatConfDynAddrMapStorageType, cnatConfDynAddrMapTable=cnatConfDynAddrMapTable, cnatConfDynAddressMapType=cnatConfDynAddressMapType, cnatConfDynGlobalAddrFrom=cnatConfDynGlobalAddrFrom, cnatConfDynGlobalAddrTo=cnatConfDynGlobalAddrTo, cnatConfDynGlobalPortFrom=cnatConfDynGlobalPortFrom, cnatConfDynGlobalPortTo=cnatConfDynGlobalPortTo, cnatConfDynLocalAddrFrom=cnatConfDynLocalAddrFrom, cnatConfDynLocalAddrTo=cnatConfDynLocalAddrTo, cnatConfDynLocalPortFrom=cnatConfDynLocalPortFrom, cnatConfDynLocalPortTo=cnatConfDynLocalPortTo, cnatConfDynProtocol=cnatConfDynProtocol, cnatConfEntry=cnatConfEntry, cnatConfMaxBindIdleTime=cnatConfMaxBindIdleTime, cnatConfMaxBindLeaseTime=cnatConfMaxBindLeaseTime, cnatConfName=cnatConfName, cnatConfServiceType=cnatConfServiceType, cnatConfStaticAddrMapEntry=cnatConfStaticAddrMapEntry, cnatConfStaticAddrMapName=cnatConfStaticAddrMapName, cnatConfStaticAddrMapStatus=cnatConfStaticAddrMapStatus, cnatConfStaticAddrMapStorageType=cnatConfStaticAddrMapStorageType, cnatConfStaticAddrMapTable=cnatConfStaticAddrMapTable, cnatConfStaticAddrMapType=cnatConfStaticAddrMapType, cnatConfStaticGlobalAddrFrom=cnatConfStaticGlobalAddrFrom, cnatConfStaticGlobalAddrTo=cnatConfStaticGlobalAddrTo, cnatConfStaticGlobalPortFrom=cnatConfStaticGlobalPortFrom, cnatConfStaticGlobalPortTo=cnatConfStaticGlobalPortTo, cnatConfStaticLocalAddrFrom=cnatConfStaticLocalAddrFrom, cnatConfStaticLocalAddrTo=cnatConfStaticLocalAddrTo, cnatConfStaticLocalPortFrom=cnatConfStaticLocalPortFrom, cnatConfStaticLocalPortTo=cnatConfStaticLocalPortTo, cnatConfStaticProtocol=cnatConfStaticProtocol, cnatConfStatus=cnatConfStatus, cnatConfStorageType=cnatConfStorageType, cnatConfTable=cnatConfTable, cnatConfTimeoutIcmpIdle=cnatConfTimeoutIcmpIdle, cnatConfTimeoutOther=cnatConfTimeoutOther, cnatConfTimeoutTcpIdle=cnatConfTimeoutTcpIdle, cnatConfTimeoutTcpNeg=cnatConfTimeoutTcpNeg, cnatConfTimeoutUdpIdle=cnatConfTimeoutUdpIdle, cnatConfig=cnatConfig, cnatConfigGroup=cnatConfigGroup, cnatInterfaceEntry=cnatInterfaceEntry, cnatInterfaceIndex=cnatInterfaceIndex, cnatInterfacePktsIn=cnatInterfacePktsIn, cnatInterfacePktsOut=cnatInterfacePktsOut, cnatInterfaceRealm=cnatInterfaceRealm, cnatInterfaceStatsEntry=cnatInterfaceStatsEntry, cnatInterfaceStatsTable=cnatInterfaceStatsTable, cnatInterfaceStatus=cnatInterfaceStatus, cnatInterfaceStorageType=cnatInterfaceStorageType, cnatInterfaceTable=cnatInterfaceTable, cnatProtocolStatsEntry=cnatProtocolStatsEntry, cnatProtocolStatsInTranslate=cnatProtocolStatsInTranslate, cnatProtocolStatsName=cnatProtocolStatsName, cnatProtocolStatsOutTranslate=cnatProtocolStatsOutTranslate, cnatProtocolStatsRejectCount=cnatProtocolStatsRejectCount, cnatProtocolStatsTable=cnatProtocolStatsTable, cnatSessionBindId=cnatSessionBindId, cnatSessionCurrentIdletime=cnatSessionCurrentIdletime, cnatSessionDirection=cnatSessionDirection, cnatSessionEntry=cnatSessionEntry, cnatSessionId=cnatSessionId, cnatSessionInTranslate=cnatSessionInTranslate, cnatSessionOrigPrivateAddr=cnatSessionOrigPrivateAddr, cnatSessionOrigPrivatePort=cnatSessionOrigPrivatePort, cnatSessionOrigPublicAddr=cnatSessionOrigPublicAddr, cnatSessionOrigPublicPort=cnatSessionOrigPublicPort, cnatSessionOutTranslate=cnatSessionOutTranslate, cnatSessionProtocolType=cnatSessionProtocolType, cnatSessionSecondBindId=cnatSessionSecondBindId, cnatSessionTable=cnatSessionTable, cnatSessionTransPrivateAddr=cnatSessionTransPrivateAddr, cnatSessionTransPrivatePort=cnatSessionTransPrivatePort, cnatSessionTransPublicAddr=cnatSessionTransPublicAddr, cnatSessionTransPublicPort=cnatSessionTransPublicPort, cnatSessionUpTime=cnatSessionUpTime, cnatStatistics=cnatStatistics, cnatStatsGroup=cnatStatsGroup)
