#
# PySNMP MIB module RAPID-SYSTEM-STATISTICS-MIB (http://snmplabs.com/pysmi)
# ASN.1 source RAPID-SYSTEM-STATISTICS-MIB
# Source digest sha256:93214eedc1ed1a37260dd7b159a74402d061b8f255fdc6b02619dca0da3d327b
# Produced by pysmi-2.3.0
#
Integer, ObjectIdentifier, OctetString = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
NamedValues, = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
rapidstream, = mibBuilder.importSymbols("RAPID-MIB", "rapidstream")
ModuleCompliance, NotificationGroup = mibBuilder.importSymbols("SNMPv2-CONF", "ModuleCompliance", "NotificationGroup")
Bits, Counter32, Counter64, Gauge32, Integer32, IpAddress, ModuleIdentity, MibIdentifier, NotificationType, ObjectIdentity, MibScalar, MibTable, MibTableRow, MibTableColumn, TimeTicks, Unsigned32, enterprises, iso = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Counter32", "Counter64", "Gauge32", "Integer32", "IpAddress", "ModuleIdentity", "MibIdentifier", "NotificationType", "ObjectIdentity", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "TimeTicks", "Unsigned32", "enterprises", "iso")
DisplayString, TextualConvention = mibBuilder.importSymbols("SNMPv2-TC", "DisplayString", "TextualConvention")
rsInfoModule = ModuleIdentity((1, 3, 6, 1, 4, 1, 4355, 6))
rsInfoModule.setRevisions(('2001-05-16 12:00', '2002-11-01 12:00',))

if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    if mibBuilder.loadTexts: rsInfoModule.setRevisionsDescriptions(('Initial revision.', 'Changed CONTACT-INFO.',))
if mibBuilder.loadTexts: rsInfoModule.setLastUpdated('1901-05-16 12:00')
if mibBuilder.loadTexts: rsInfoModule.setOrganization('WatchGuard Technologies, Inc.')
if mibBuilder.loadTexts: rsInfoModule.setContactInfo('   Ella Yu\n                      WatchGuard Technologies, Inc.\n                      1841 Zanker Road \n                      San Jose, CA 95112\n                      USA\n\n                      408-519-4888\n                      ella.yu@watchguard.com ')
if mibBuilder.loadTexts: rsInfoModule.setDescription('The MIB module describes various system statistics information\n            of RapidStream system.')
rsSystemStatisticsMIB = ObjectIdentity((1, 3, 6, 1, 4, 1, 4355, 6, 3))
if mibBuilder.loadTexts: rsSystemStatisticsMIB.setStatus('current')
if mibBuilder.loadTexts: rsSystemStatisticsMIB.setDescription('This is the base system information for all system related\n             statistical counters.')
rsSystemCpuUtil = MibScalar((1, 3, 6, 1, 4, 1, 4355, 6, 3, 4), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rsSystemCpuUtil.setStatus('current')
if mibBuilder.loadTexts: rsSystemCpuUtil.setDescription('CPU utilization of the system in last 5 seconds. The value\n             is measured in 0.01%.  For example, if the value is 234, \n             then CPU utilization is 2.34%.')
rsSystemTotalSendBytes = MibScalar((1, 3, 6, 1, 4, 1, 4355, 6, 3, 8), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rsSystemTotalSendBytes.setStatus('current')
if mibBuilder.loadTexts: rsSystemTotalSendBytes.setDescription('The total number of bytes sent since system is up. This\n            number includes both cut through traffic and host traffic.')
rsSystemTotalRecvBytes = MibScalar((1, 3, 6, 1, 4, 1, 4355, 6, 3, 9), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rsSystemTotalRecvBytes.setStatus('current')
if mibBuilder.loadTexts: rsSystemTotalRecvBytes.setDescription('The total number of bytes received since system is up. This\n            number includes both cut through traffic and host traffic.')
rsSystemTotalSendPackets = MibScalar((1, 3, 6, 1, 4, 1, 4355, 6, 3, 10), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rsSystemTotalSendPackets.setStatus('current')
if mibBuilder.loadTexts: rsSystemTotalSendPackets.setDescription('The total number of the packets sent since system is up. This\n            number includes both cut through traffic and host traffic.')
rsSystemTotalRecvPackets = MibScalar((1, 3, 6, 1, 4, 1, 4355, 6, 3, 11), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rsSystemTotalRecvPackets.setStatus('current')
if mibBuilder.loadTexts: rsSystemTotalRecvPackets.setDescription('The total number of the packets received since system is up.\n            The number includes both cut through traffic and host traffic.')
rsSystemStreamReqTotal = MibScalar((1, 3, 6, 1, 4, 1, 4355, 6, 3, 30), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rsSystemStreamReqTotal.setStatus('current')
if mibBuilder.loadTexts: rsSystemStreamReqTotal.setDescription('The total number of the connection requests since system is up.')
rsSystemStreamReqDrop = MibScalar((1, 3, 6, 1, 4, 1, 4355, 6, 3, 34), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rsSystemStreamReqDrop.setStatus('current')
if mibBuilder.loadTexts: rsSystemStreamReqDrop.setDescription('The total number of the connection requests being dropped since system is up.')
rsSystemCpuUtil1 = MibScalar((1, 3, 6, 1, 4, 1, 4355, 6, 3, 77), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rsSystemCpuUtil1.setStatus('current')
if mibBuilder.loadTexts: rsSystemCpuUtil1.setDescription('CPU utilization of the system in last 1 minute. The value\n            is measured in 0.01%.  For example, if the value is 234, \n            then CPU utilization is 2.34%.')
rsSystemCpuUtil5 = MibScalar((1, 3, 6, 1, 4, 1, 4355, 6, 3, 78), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rsSystemCpuUtil5.setStatus('current')
if mibBuilder.loadTexts: rsSystemCpuUtil5.setDescription('CPU utilization of the system in last 5 minutes. The value\n            is measured in 0.01%.  For example, if the value is 234, \n            then CPU utilization is 2.34%.')
rsSystemCpuUtil15 = MibScalar((1, 3, 6, 1, 4, 1, 4355, 6, 3, 79), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rsSystemCpuUtil15.setStatus('current')
if mibBuilder.loadTexts: rsSystemCpuUtil15.setDescription('CPU utilization of the system in last 15 minutes. The value\n            is measured in 0.01%.  For example, if the value is 234, \n            then CPU utilization is 2.34%.')
mibBuilder.exportSymbols("RAPID-SYSTEM-STATISTICS-MIB", PYSNMP_MODULE_ID=rsInfoModule, rsInfoModule=rsInfoModule, rsSystemCpuUtil15=rsSystemCpuUtil15, rsSystemCpuUtil1=rsSystemCpuUtil1, rsSystemCpuUtil5=rsSystemCpuUtil5, rsSystemCpuUtil=rsSystemCpuUtil, rsSystemStatisticsMIB=rsSystemStatisticsMIB, rsSystemStreamReqDrop=rsSystemStreamReqDrop, rsSystemStreamReqTotal=rsSystemStreamReqTotal, rsSystemTotalRecvBytes=rsSystemTotalRecvBytes, rsSystemTotalRecvPackets=rsSystemTotalRecvPackets, rsSystemTotalSendBytes=rsSystemTotalSendBytes, rsSystemTotalSendPackets=rsSystemTotalSendPackets)
