{{- if and .Values.localMibs.pathToMibs (not (include "mibserver.existingClaim" .)) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mibserver.fullname" . }}
  labels:
    {{- include "mibserver.labels" . | nindent 4 }}
spec:
  storageClassName: {{ dig "storageClass" "microk8s-hostpath" (.Values.localMibs.persistence | default dict) }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ dig "size" "3Gi" (.Values.localMibs.persistence | default dict) }}
{{- end }}