{{- if and .Values.localMibs.pathToMibs (not (include "mibserver.existingClaim" .)) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mibserver.fullname" . }}
  labels:
    type: local
    {{- include "mibserver.labels" . | nindent 4 }}
spec:
  storageClassName: {{ dig "storageClass" "microk8s-hostpath" (.Values.localMibs.persistence | default dict) }}
  capacity:
    storage: {{ dig "size" "3Gi" (.Values.localMibs.persistence | default dict) }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.localMibs.pathToMibs }}
{{- end }}