name: Release-Notes-Preview

on:
  pull_request:
#    branches: [main, develop]
  issue_comment:
    types: [edited]

jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: false
          swap-storage: false
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          filter: blob:none
      - uses: snyk/release-notes-preview@v1.6.2
        with:
          releaseBranch: main
        env:
          GITHUB_PR_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
