#
# PySNMP MIB module ALCATEL-IND1-DOT1Q-MIB (http://snmplabs.com/pysmi)
# ASN.1 source ALCATEL-IND1-DOT1Q-MIB
# Source digest sha256:9a4f1ee96234e70318e689efd2a02569950d42f955379def6fccee7ee1c967cf
# Produced by pysmi-2.3.0
#
softentIND1Dot1Q, = mibBuilder.importSymbols("ALCATEL-IND1-BASE", "softentIND1Dot1Q")
Integer, ObjectIdentifier, OctetString = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
NamedValues, = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
ModuleCompliance, NotificationGroup, ObjectGroup = mibBuilder.importSymbols("SNMPv2-CONF", "ModuleCompliance", "NotificationGroup", "ObjectGroup")
Bits, Counter32, Counter64, Gauge32, Integer32, IpAddress, ModuleIdentity, MibIdentifier, NotificationType, ObjectIdentity, MibScalar, MibTable, MibTableRow, MibTableColumn, TimeTicks, Unsigned32, iso = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Counter32", "Counter64", "Gauge32", "Integer32", "IpAddress", "ModuleIdentity", "MibIdentifier", "NotificationType", "ObjectIdentity", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "TimeTicks", "Unsigned32", "iso")
DisplayString, RowStatus, TextualConvention = mibBuilder.importSymbols("SNMPv2-TC", "DisplayString", "RowStatus", "TextualConvention")
alcatelIND1Dot1QMIB = ModuleIdentity((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 21, 1))
alcatelIND1Dot1QMIB.setRevisions(('2019-10-07 00:00',))
if mibBuilder.loadTexts: alcatelIND1Dot1QMIB.setLastUpdated('2019-10-07 00:00')
if mibBuilder.loadTexts: alcatelIND1Dot1QMIB.setOrganization('ALE USA Inc')
alcatelIND1Dot1QMIBObjects = ObjectIdentity((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 21, 1, 1))
if mibBuilder.loadTexts: alcatelIND1Dot1QMIBObjects.setStatus('current')
alcatelIND1Dot1QMIBConformance = ObjectIdentity((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 21, 1, 2))
if mibBuilder.loadTexts: alcatelIND1Dot1QMIBConformance.setStatus('current')
alcatelIND1Dot1QMIBGroups = ObjectIdentity((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 21, 1, 2, 1))
if mibBuilder.loadTexts: alcatelIND1Dot1QMIBGroups.setStatus('current')
alcatelIND1Dot1QMIBCompliances = ObjectIdentity((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 21, 1, 2, 2))
if mibBuilder.loadTexts: alcatelIND1Dot1QMIBCompliances.setStatus('current')
v8021Q = MibIdentifier((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 21, 1, 1, 1))
qPortVlanTable = MibTable((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 21, 1, 1, 1, 1), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: qPortVlanTable.setStatus('current')
qPortVlanEntry = MibTableRow((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 21, 1, 1, 1, 1, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "ALCATEL-IND1-DOT1Q-MIB", "qPortVlanSlot"), (0, "ALCATEL-IND1-DOT1Q-MIB", "qPortVlanPort"), (0, "ALCATEL-IND1-DOT1Q-MIB", "qPortVlanTagValue"))
if mibBuilder.loadTexts: qPortVlanEntry.setStatus('current')
qPortVlanSlot = MibTableColumn((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 21, 1, 1, 1, 1, 1, 1), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 16))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: qPortVlanSlot.setStatus('current')
qPortVlanPort = MibTableColumn((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 21, 1, 1, 1, 1, 1, 2), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 64))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: qPortVlanPort.setStatus('current')
qPortVlanTagValue = MibTableColumn((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 21, 1, 1, 1, 1, 1, 3), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 4094))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: qPortVlanTagValue.setStatus('current')
qPortVlanStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 21, 1, 1, 1, 1, 1, 4), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: qPortVlanStatus.setStatus('current')
qPortVlanDescription = MibTableColumn((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 21, 1, 1, 1, 1, 1, 5), DisplayString().subtype(subtypeSpec=ValueSizeConstraint(0, 31))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: qPortVlanDescription.setStatus('current')
qPortVlanForceTagInternal = MibTableColumn((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 21, 1, 1, 1, 1, 1, 6), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(2, 1, 0))).clone(namedValues=NamedValues(("na", 2), ("on", 1), ("off", 0))).clone('na')).setMaxAccess("readcreate")
if mibBuilder.loadTexts: qPortVlanForceTagInternal.setStatus('current')
qAggregateVlanTable = MibTable((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 21, 1, 1, 1, 2), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: qAggregateVlanTable.setStatus('current')
qAggregateVlanEntry = MibTableRow((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 21, 1, 1, 1, 2, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "ALCATEL-IND1-DOT1Q-MIB", "qAggregateVlanAggregateId"), (0, "ALCATEL-IND1-DOT1Q-MIB", "qAggregateVlanTagValue"))
if mibBuilder.loadTexts: qAggregateVlanEntry.setStatus('current')
qAggregateVlanAggregateId = MibTableColumn((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 21, 1, 1, 1, 2, 1, 1), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 31))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: qAggregateVlanAggregateId.setStatus('current')
qAggregateVlanTagValue = MibTableColumn((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 21, 1, 1, 1, 2, 1, 2), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 4094))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: qAggregateVlanTagValue.setStatus('current')
qAggregateVlanStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 21, 1, 1, 1, 2, 1, 3), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: qAggregateVlanStatus.setStatus('current')
qAggregateVlanDescription = MibTableColumn((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 21, 1, 1, 1, 2, 1, 4), DisplayString().subtype(subtypeSpec=ValueSizeConstraint(0, 31))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: qAggregateVlanDescription.setStatus('current')
qAtmIfIndexVpiVciTable = MibTable((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 21, 1, 1, 1, 3), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: qAtmIfIndexVpiVciTable.setStatus('current')
qAtmIfIndexVpiVciEntry = MibTableRow((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 21, 1, 1, 1, 3, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "ALCATEL-IND1-DOT1Q-MIB", "qAtmIfIndex"), (0, "ALCATEL-IND1-DOT1Q-MIB", "qAtmVpiValue"), (0, "ALCATEL-IND1-DOT1Q-MIB", "qAtmVciValue"), (0, "ALCATEL-IND1-DOT1Q-MIB", "qAtmIfIndexVpiVciVlanTagValue"))
if mibBuilder.loadTexts: qAtmIfIndexVpiVciEntry.setStatus('current')
qAtmIfIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 21, 1, 1, 1, 3, 1, 1), Integer32().subtype(subtypeSpec=ValueRangeConstraint(4259841, 2147483647))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: qAtmIfIndex.setStatus('current')
qAtmVpiValue = MibTableColumn((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 21, 1, 1, 1, 3, 1, 2), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 4095))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: qAtmVpiValue.setStatus('current')
qAtmVciValue = MibTableColumn((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 21, 1, 1, 1, 3, 1, 3), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 65535))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: qAtmVciValue.setStatus('current')
qAtmIfIndexVpiVciVlanTagValue = MibTableColumn((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 21, 1, 1, 1, 3, 1, 4), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 4094))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: qAtmIfIndexVpiVciVlanTagValue.setStatus('current')
qAtmIfIndexVpiVciVlanAction = MibTableColumn((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 21, 1, 1, 1, 3, 1, 5), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: qAtmIfIndexVpiVciVlanAction.setStatus('current')
qAtmIfIndexVpiVciVlanDescription = MibTableColumn((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 21, 1, 1, 1, 3, 1, 6), DisplayString().subtype(subtypeSpec=ValueSizeConstraint(0, 31))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: qAtmIfIndexVpiVciVlanDescription.setStatus('current')
qAtmIfIndexVpiVciAcceptableFrameTypes = MibTableColumn((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 21, 1, 1, 1, 3, 1, 7), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("admitAll", 1), ("admitOnlyVlanTagged", 2))).clone('admitAll')).setMaxAccess("readcreate")
if mibBuilder.loadTexts: qAtmIfIndexVpiVciAcceptableFrameTypes.setStatus('current')
qAtmIfIndexVpiVciForceTagInternal = MibTableColumn((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 21, 1, 1, 1, 3, 1, 8), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(2, 1, 0))).clone(namedValues=NamedValues(("na", 2), ("on", 1), ("off", 0))).clone('na')).setMaxAccess("readcreate")
if mibBuilder.loadTexts: qAtmIfIndexVpiVciForceTagInternal.setStatus('current')
alcatelIND1Dot1QMIBCompliance = ModuleCompliance((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 21, 1, 2, 2, 1)).setObjects(("ALCATEL-IND1-DOT1Q-MIB", "dot1qPortGroup"), ("ALCATEL-IND1-DOT1Q-MIB", "dot1qAggregateGroup"), ("ALCATEL-IND1-DOT1Q-MIB", "qAtmIfIndexVpiVciEntryGroup"))

if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    alcatelIND1Dot1QMIBCompliance = alcatelIND1Dot1QMIBCompliance.setStatus('current')
dot1qPortGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 21, 1, 2, 1, 1)).setObjects(("ALCATEL-IND1-DOT1Q-MIB", "qPortVlanSlot"), ("ALCATEL-IND1-DOT1Q-MIB", "qPortVlanPort"), ("ALCATEL-IND1-DOT1Q-MIB", "qPortVlanTagValue"), ("ALCATEL-IND1-DOT1Q-MIB", "qPortVlanStatus"), ("ALCATEL-IND1-DOT1Q-MIB", "qPortVlanDescription"), ("ALCATEL-IND1-DOT1Q-MIB", "qPortVlanForceTagInternal"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    dot1qPortGroup = dot1qPortGroup.setStatus('current')
dot1qAggregateGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 21, 1, 2, 1, 2)).setObjects(("ALCATEL-IND1-DOT1Q-MIB", "qAggregateVlanAggregateId"), ("ALCATEL-IND1-DOT1Q-MIB", "qAggregateVlanTagValue"), ("ALCATEL-IND1-DOT1Q-MIB", "qAggregateVlanStatus"), ("ALCATEL-IND1-DOT1Q-MIB", "qAggregateVlanDescription"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    dot1qAggregateGroup = dot1qAggregateGroup.setStatus('current')
qAtmIfIndexVpiVciEntryGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 21, 1, 2, 1, 3)).setObjects(("ALCATEL-IND1-DOT1Q-MIB", "qAtmIfIndex"), ("ALCATEL-IND1-DOT1Q-MIB", "qAtmVpiValue"), ("ALCATEL-IND1-DOT1Q-MIB", "qAtmVciValue"), ("ALCATEL-IND1-DOT1Q-MIB", "qAtmIfIndexVpiVciVlanTagValue"), ("ALCATEL-IND1-DOT1Q-MIB", "qAtmIfIndexVpiVciVlanAction"), ("ALCATEL-IND1-DOT1Q-MIB", "qAtmIfIndexVpiVciVlanDescription"), ("ALCATEL-IND1-DOT1Q-MIB", "qAtmIfIndexVpiVciAcceptableFrameTypes"), ("ALCATEL-IND1-DOT1Q-MIB", "qAtmIfIndexVpiVciForceTagInternal"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    qAtmIfIndexVpiVciEntryGroup = qAtmIfIndexVpiVciEntryGroup.setStatus('current')
mibBuilder.exportSymbols("ALCATEL-IND1-DOT1Q-MIB", PYSNMP_MODULE_ID=alcatelIND1Dot1QMIB, alcatelIND1Dot1QMIB=alcatelIND1Dot1QMIB, alcatelIND1Dot1QMIBCompliance=alcatelIND1Dot1QMIBCompliance, alcatelIND1Dot1QMIBCompliances=alcatelIND1Dot1QMIBCompliances, alcatelIND1Dot1QMIBConformance=alcatelIND1Dot1QMIBConformance, alcatelIND1Dot1QMIBGroups=alcatelIND1Dot1QMIBGroups, alcatelIND1Dot1QMIBObjects=alcatelIND1Dot1QMIBObjects, dot1qAggregateGroup=dot1qAggregateGroup, dot1qPortGroup=dot1qPortGroup, qAggregateVlanAggregateId=qAggregateVlanAggregateId, qAggregateVlanDescription=qAggregateVlanDescription, qAggregateVlanEntry=qAggregateVlanEntry, qAggregateVlanStatus=qAggregateVlanStatus, qAggregateVlanTable=qAggregateVlanTable, qAggregateVlanTagValue=qAggregateVlanTagValue, qAtmIfIndex=qAtmIfIndex, qAtmIfIndexVpiVciAcceptableFrameTypes=qAtmIfIndexVpiVciAcceptableFrameTypes, qAtmIfIndexVpiVciEntry=qAtmIfIndexVpiVciEntry, qAtmIfIndexVpiVciEntryGroup=qAtmIfIndexVpiVciEntryGroup, qAtmIfIndexVpiVciForceTagInternal=qAtmIfIndexVpiVciForceTagInternal, qAtmIfIndexVpiVciTable=qAtmIfIndexVpiVciTable, qAtmIfIndexVpiVciVlanAction=qAtmIfIndexVpiVciVlanAction, qAtmIfIndexVpiVciVlanDescription=qAtmIfIndexVpiVciVlanDescription, qAtmIfIndexVpiVciVlanTagValue=qAtmIfIndexVpiVciVlanTagValue, qAtmVciValue=qAtmVciValue, qAtmVpiValue=qAtmVpiValue, qPortVlanDescription=qPortVlanDescription, qPortVlanEntry=qPortVlanEntry, qPortVlanForceTagInternal=qPortVlanForceTagInternal, qPortVlanPort=qPortVlanPort, qPortVlanSlot=qPortVlanSlot, qPortVlanStatus=qPortVlanStatus, qPortVlanTable=qPortVlanTable, qPortVlanTagValue=qPortVlanTagValue, v8021Q=v8021Q)
