#
# PySNMP MIB module ALCATEL-IND1-PORT-MAPPING (http://snmplabs.com/pysmi)
# ASN.1 source ALCATEL-IND1-PORT-MAPPING
# Source digest sha256:34defae0bd1473da885aa90c199a594897f35711740c0fa937da8a7349aada3b
# Produced by pysmi-2.3.0
#
softentIND1PortMapping, = mibBuilder.importSymbols("ALCATEL-IND1-BASE", "softentIND1PortMapping")
Integer, ObjectIdentifier, OctetString = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
NamedValues, = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
InterfaceIndexOrZero, = mibBuilder.importSymbols("IF-MIB", "InterfaceIndexOrZero")
ModuleCompliance, NotificationGroup = mibBuilder.importSymbols("SNMPv2-CONF", "ModuleCompliance", "NotificationGroup")
Bits, Counter32, Counter64, Gauge32, Integer32, IpAddress, ModuleIdentity, MibIdentifier, NotificationType, ObjectIdentity, MibScalar, MibTable, MibTableRow, MibTableColumn, TimeTicks, Unsigned32, iso = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Counter32", "Counter64", "Gauge32", "Integer32", "IpAddress", "ModuleIdentity", "MibIdentifier", "NotificationType", "ObjectIdentity", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "TimeTicks", "Unsigned32", "iso")
DisplayString, RowStatus, TextualConvention = mibBuilder.importSymbols("SNMPv2-TC", "DisplayString", "RowStatus", "TextualConvention")
alcatelIND1PortMappingMIB = ModuleIdentity((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 33, 1))
alcatelIND1PortMappingMIB.setRevisions(('2019-10-07 00:00',))
if mibBuilder.loadTexts: alcatelIND1PortMappingMIB.setLastUpdated('2019-10-07 00:00')
if mibBuilder.loadTexts: alcatelIND1PortMappingMIB.setOrganization('ALE USA Inc')
alcatelIND1PortMappingMIBObjects = ObjectIdentity((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 33, 1, 1))
if mibBuilder.loadTexts: alcatelIND1PortMappingMIBObjects.setStatus('current')
portMapping = MibIdentifier((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 33, 1, 1, 1))
portMappingSessionTable = MibTable((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 33, 1, 1, 1, 1), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: portMappingSessionTable.setStatus('current')
pmapSessionEntry = MibTableRow((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 33, 1, 1, 1, 1, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "ALCATEL-IND1-PORT-MAPPING", "pmapSessionNumber"))
if mibBuilder.loadTexts: pmapSessionEntry.setStatus('current')
pmapSessionNumber = MibTableColumn((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 33, 1, 1, 1, 1, 1, 1), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 2147483647)).clone(1)).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: pmapSessionNumber.setStatus('current')
pmapSessionStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 33, 1, 1, 1, 1, 1, 2), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("disable", 1), ("enable", 2))).clone('disable')).setMaxAccess("readcreate")
if mibBuilder.loadTexts: pmapSessionStatus.setStatus('current')
pmapSessionDirection = MibTableColumn((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 33, 1, 1, 1, 1, 1, 3), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("uni", 1), ("bi", 2))).clone('bi')).setMaxAccess("readcreate")
if mibBuilder.loadTexts: pmapSessionDirection.setStatus('current')
pmapSessionRowStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 33, 1, 1, 1, 1, 1, 4), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: pmapSessionRowStatus.setStatus('current')
pmapSessionUnknownUnicastFloodStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 33, 1, 1, 1, 1, 1, 5), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("disable", 1), ("enable", 2))).clone('enable')).setMaxAccess("readonly")
if mibBuilder.loadTexts: pmapSessionUnknownUnicastFloodStatus.setStatus('obsolete')
pmapSessionDynProxyARP = MibTableColumn((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 33, 1, 1, 1, 1, 1, 6), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("disable", 1), ("enable", 2))).clone('disable')).setMaxAccess("readcreate")
if mibBuilder.loadTexts: pmapSessionDynProxyARP.setStatus('current')
portMappingTable = MibTable((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 33, 1, 1, 1, 2), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: portMappingTable.setStatus('current')
pmapEntry = MibTableRow((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 33, 1, 1, 1, 2, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "ALCATEL-IND1-PORT-MAPPING", "pmapSessionNumber"), (0, "ALCATEL-IND1-PORT-MAPPING", "pmapPortIfIndex"))
if mibBuilder.loadTexts: pmapEntry.setStatus('current')
pmapPortIfIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 33, 1, 1, 1, 2, 1, 1), InterfaceIndexOrZero().clone(0)).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: pmapPortIfIndex.setStatus('current')
pmapPortType = MibTableColumn((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 33, 1, 1, 1, 2, 1, 2), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("user", 1), ("network", 2))).clone('user')).setMaxAccess("readcreate")
if mibBuilder.loadTexts: pmapPortType.setStatus('current')
pmapRowStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 33, 1, 1, 1, 2, 1, 3), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: pmapRowStatus.setStatus('current')
pmapConformance = MibIdentifier((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 33, 1, 2))
pmapGroups = MibIdentifier((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 33, 1, 2, 1))
pmapCompliances = MibIdentifier((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 33, 1, 2, 2))
pmapSessionTableGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 33, 1, 2, 1, 1)).setObjects(("ALCATEL-IND1-PORT-MAPPING", "pmapSessionStatus"), ("ALCATEL-IND1-PORT-MAPPING", "pmapSessionDirection"), ("ALCATEL-IND1-PORT-MAPPING", "pmapSessionRowStatus"), ("ALCATEL-IND1-PORT-MAPPING", "pmapSessionUnknownUnicastFloodStatus"), ("ALCATEL-IND1-PORT-MAPPING", "pmapSessionDynProxyARP"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    pmapSessionTableGroup = pmapSessionTableGroup.setStatus('current')
pmapTableGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 33, 1, 2, 1, 2)).setObjects(("ALCATEL-IND1-PORT-MAPPING", "pmapPortType"), ("ALCATEL-IND1-PORT-MAPPING", "pmapRowStatus"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    pmapTableGroup = pmapTableGroup.setStatus('current')
pmapCompliance = ModuleCompliance((1, 3, 6, 1, 4, 1, 6486, 800, 1, 2, 1, 33, 1, 2, 2, 1)).setObjects(("ALCATEL-IND1-PORT-MAPPING", "pmapSessionTableGroup"), ("ALCATEL-IND1-PORT-MAPPING", "pmapTableGroup"))

if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    pmapCompliance = pmapCompliance.setStatus('current')
mibBuilder.exportSymbols("ALCATEL-IND1-PORT-MAPPING", PYSNMP_MODULE_ID=alcatelIND1PortMappingMIB, alcatelIND1PortMappingMIB=alcatelIND1PortMappingMIB, alcatelIND1PortMappingMIBObjects=alcatelIND1PortMappingMIBObjects, pmapCompliance=pmapCompliance, pmapCompliances=pmapCompliances, pmapConformance=pmapConformance, pmapEntry=pmapEntry, pmapGroups=pmapGroups, pmapPortIfIndex=pmapPortIfIndex, pmapPortType=pmapPortType, pmapRowStatus=pmapRowStatus, pmapSessionDirection=pmapSessionDirection, pmapSessionDynProxyARP=pmapSessionDynProxyARP, pmapSessionEntry=pmapSessionEntry, pmapSessionNumber=pmapSessionNumber, pmapSessionRowStatus=pmapSessionRowStatus, pmapSessionStatus=pmapSessionStatus, pmapSessionTableGroup=pmapSessionTableGroup, pmapSessionUnknownUnicastFloodStatus=pmapSessionUnknownUnicastFloodStatus, pmapTableGroup=pmapTableGroup, portMapping=portMapping, portMappingSessionTable=portMappingSessionTable, portMappingTable=portMappingTable)
