#
# PySNMP MIB module BW-BroadworksMediaServer (http://snmplabs.com/pysmi)
# ASN.1 source BW-BroadworksMediaServer
# Source digest sha256:b659a88c6fbf5640432c4879d4aee18cf6aff9c1c2d202d35d36d9a07aa77d70
# Produced by pysmi-2.3.0
#
Integer, ObjectIdentifier, OctetString = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
NamedValues, = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
ModuleCompliance, NotificationGroup, ObjectGroup = mibBuilder.importSymbols("SNMPv2-CONF", "ModuleCompliance", "NotificationGroup", "ObjectGroup")
Bits, Counter32, Counter64, Gauge32, Integer32, IpAddress, ModuleIdentity, MibIdentifier, NotificationType, ObjectIdentity, MibScalar, MibTable, MibTableRow, MibTableColumn, TimeTicks, Unsigned32, enterprises, iso = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Counter32", "Counter64", "Gauge32", "Integer32", "IpAddress", "ModuleIdentity", "MibIdentifier", "NotificationType", "ObjectIdentity", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "TimeTicks", "Unsigned32", "enterprises", "iso")
DateAndTime, DisplayString, TextualConvention = mibBuilder.importSymbols("SNMPv2-TC", "DateAndTime", "DisplayString", "TextualConvention")
broadsoft = ModuleIdentity((1, 3, 6, 1, 4, 1, 6431))
broadsoft.setRevisions(('2005-08-15 14:30', '2000-09-19 14:31',))
if mibBuilder.loadTexts: broadsoft.setLastUpdated('2005-08-15 14:30')
if mibBuilder.loadTexts: broadsoft.setOrganization('Broadsoft, Inc')
broadworks = MibIdentifier((1, 3, 6, 1, 4, 1, 6431, 1))
mediaServer = MibIdentifier((1, 3, 6, 1, 4, 1, 6431, 1, 3))
mcp = MibIdentifier((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1))
rtp = MibIdentifier((1, 3, 6, 1, 4, 1, 6431, 1, 3, 2))
smtp = MibIdentifier((1, 3, 6, 1, 4, 1, 6431, 1, 3, 3))
system = MibIdentifier((1, 3, 6, 1, 4, 1, 6431, 1, 3, 4))
http = MibIdentifier((1, 3, 6, 1, 4, 1, 6431, 1, 3, 5))
management = MibIdentifier((1, 3, 6, 1, 4, 1, 6431, 1, 3, 6))
sip = MibIdentifier((1, 3, 6, 1, 4, 1, 6431, 1, 3, 7))
mscml = MibIdentifier((1, 3, 6, 1, 4, 1, 6431, 1, 3, 8))
liveaudio = MibIdentifier((1, 3, 6, 1, 4, 1, 6431, 1, 3, 9))
video = MibIdentifier((1, 3, 6, 1, 4, 1, 6431, 1, 3, 10))
fax = MibIdentifier((1, 3, 6, 1, 4, 1, 6431, 1, 3, 11))
vxml = MibIdentifier((1, 3, 6, 1, 4, 1, 6431, 1, 3, 12))
ccxml = MibIdentifier((1, 3, 6, 1, 4, 1, 6431, 1, 3, 13))
interfaces = MibIdentifier((1, 3, 6, 1, 4, 1, 6431, 1, 3, 14))
bwMsConformance = MibIdentifier((1, 3, 6, 1, 4, 1, 6431, 1, 3, 20))
conferencing = MibIdentifier((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 3))
ivr = MibIdentifier((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 4))
msPortsInUse = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 5), Gauge32().subtype(subtypeSpec=ValueRangeConstraint(0, 4294967295))).setMaxAccess("readonly")
if mibBuilder.loadTexts: msPortsInUse.setStatus('current')
msNoPortAvailableErrors = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 6), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msNoPortAvailableErrors.setStatus('current')
msMCPNotificationsTransmitted = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 7), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msMCPNotificationsTransmitted.setStatus('obsolete')
msMCPNotificationsRetransmitted = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 8), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msMCPNotificationsRetransmitted.setStatus('obsolete')
msMCPCommandsReceived = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 9), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msMCPCommandsReceived.setStatus('obsolete')
msConfAddParticipantFailed = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 3, 1), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msConfAddParticipantFailed.setStatus('obsolete')
msConfAddParticipant = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 3, 2), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msConfAddParticipant.setStatus('obsolete')
msConfAllocateBridge = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 3, 3), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msConfAllocateBridge.setStatus('obsolete')
msConfAllocateBridgeFailed = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 3, 4), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msConfAllocateBridgeFailed.setStatus('obsolete')
msConfRemoveParticipant = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 3, 5), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msConfRemoveParticipant.setStatus('obsolete')
msConfRemoveParticipantFailed = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 3, 6), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msConfRemoveParticipantFailed.setStatus('obsolete')
msConfCurrentPortsInUse = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 3, 7), Gauge32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: msConfCurrentPortsInUse.setStatus('obsolete')
msConferenceCount = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 3, 8), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msConferenceCount.setStatus('current')
msConfTotalDuration = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 3, 9), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msConfTotalDuration.setStatus('current')
msConfUpdateParticipant = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 3, 11), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msConfUpdateParticipant.setStatus('obsolete')
msConfUpdateParticipantFailed = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 3, 12), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msConfUpdateParticipantFailed.setStatus('obsolete')
msIvrFreeAudioMemory = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 4, 1), Gauge32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: msIvrFreeAudioMemory.setStatus('current')
msIvrAudioMemoryInUse = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 4, 2), Gauge32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: msIvrAudioMemoryInUse.setStatus('current')
msIvrCurrentPortsInUse = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 4, 3), Gauge32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: msIvrCurrentPortsInUse.setStatus('obsolete')
msIvrCreateConnection = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 4, 4), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msIvrCreateConnection.setStatus('obsolete')
msIvrCreateConnectionFailed = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 4, 5), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msIvrCreateConnectionFailed.setStatus('obsolete')
msIvrUpdateConnection = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 4, 6), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msIvrUpdateConnection.setStatus('obsolete')
msIvrUpdateConnectionFailed = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 4, 7), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msIvrUpdateConnectionFailed.setStatus('obsolete')
msIvrPlay = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 4, 8), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msIvrPlay.setStatus('obsolete')
msIvrPlayFailed = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 4, 9), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msIvrPlayFailed.setStatus('obsolete')
msIvrPlayCollect = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 4, 10), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msIvrPlayCollect.setStatus('obsolete')
msIvrPlayCollectFailed = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 4, 11), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msIvrPlayCollectFailed.setStatus('obsolete')
msIvrPlayRecord = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 4, 12), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msIvrPlayRecord.setStatus('obsolete')
msIvrPlayRecordFailed = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 4, 13), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msIvrPlayRecordFailed.setStatus('obsolete')
msIvrSendEmail = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 4, 14), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msIvrSendEmail.setStatus('obsolete')
msIvrSendEmailFailed = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 4, 15), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msIvrSendEmailFailed.setStatus('obsolete')
msIvrSessionCount = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 4, 16), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msIvrSessionCount.setStatus('current')
msIvrTotalDuration = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 4, 17), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msIvrTotalDuration.setStatus('current')
msIvrTotalRecordingDuration = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 4, 18), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msIvrTotalRecordingDuration.setStatus('obsolete')
msIvrMerge = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 4, 21), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msIvrMerge.setStatus('obsolete')
msIvrMergeFailed = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 4, 22), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msIvrMergeFailed.setStatus('obsolete')
msIvrEmptyRecordings = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 1, 4, 23), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msIvrEmptyRecordings.setStatus('obsolete')
msRtpSessionsCount = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 2, 1), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: msRtpSessionsCount.setStatus('current')
receive = MibIdentifier((1, 3, 6, 1, 4, 1, 6431, 1, 3, 2, 2))
transmit = MibIdentifier((1, 3, 6, 1, 4, 1, 6431, 1, 3, 2, 3))
msRtpSessionsInUse = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 2, 4), Gauge32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: msRtpSessionsInUse.setStatus('current')
msRtcpSenderReports = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 2, 2, 1), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: msRtcpSenderReports.setStatus('current')
msRtpPacketsExpected = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 2, 2, 2), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: msRtpPacketsExpected.setStatus('current')
msRtpPacketsReceived = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 2, 2, 3), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: msRtpPacketsReceived.setStatus('current')
msRtpOutOfOrder = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 2, 2, 5), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: msRtpOutOfOrder.setStatus('current')
msRtpBadPayload = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 2, 2, 6), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: msRtpBadPayload.setStatus('current')
msRtpSsrc = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 2, 2, 7), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: msRtpSsrc.setStatus('current')
msRtpReceivedPacketJitter = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 2, 2, 8), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: msRtpReceivedPacketJitter.setStatus('current')
msRtpCumulativePacketsLost = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 2, 3, 1), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: msRtpCumulativePacketsLost.setStatus('current')
msRtpPacketsSent = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 2, 3, 4), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: msRtpPacketsSent.setStatus('current')
msRtpFramesSkipped = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 2, 3, 5), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: msRtpFramesSkipped.setStatus('current')
msRtpTransmitJitter = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 2, 3, 6), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: msRtpTransmitJitter.setStatus('current')
primary = MibIdentifier((1, 3, 6, 1, 4, 1, 6431, 1, 3, 3, 1))
secondary = MibIdentifier((1, 3, 6, 1, 4, 1, 6431, 1, 3, 3, 2))
msPrimaryEmailSent = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 3, 1, 1), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msPrimaryEmailSent.setStatus('current')
msPrimarySmtpErrors = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 3, 1, 2), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msPrimarySmtpErrors.setStatus('current')
msSecondaryEmailSent = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 3, 2, 1), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msSecondaryEmailSent.setStatus('current')
msSecondarySmtpErrors = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 3, 2, 2), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msSecondarySmtpErrors.setStatus('current')
msAlarmsCount = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 4, 1), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msAlarmsCount.setStatus('current')
msSoftwareErrorsCount = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 4, 2), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msSoftwareErrorsCount.setStatus('current')
msACLViolationCount = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 4, 3), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msACLViolationCount.setStatus('current')
msMaxCapacityInPorts = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 4, 4), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msMaxCapacityInPorts.setStatus('current')
msNumLicensedPorts = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 4, 5), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msNumLicensedPorts.setStatus('current')
msSipStatsInviteIns = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 7, 1), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msSipStatsInviteIns.setStatus('current')
msSipStatsAckIns = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 7, 2), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msSipStatsAckIns.setStatus('current')
msSipStatsByeIns = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 7, 3), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msSipStatsByeIns.setStatus('current')
msSipStatsByeOuts = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 7, 4), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msSipStatsByeOuts.setStatus('current')
msSipStatsInfoIns = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 7, 5), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msSipStatsInfoIns.setStatus('current')
msSipStatsInfoOuts = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 7, 6), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msSipStatsInfoOuts.setStatus('current')
msSipStatsOthersIns = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 7, 7), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msSipStatsOthersIns.setStatus('current')
msSipStatsOthersOuts = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 7, 8), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msSipStatsOthersOuts.setStatus('current')
msSipStatsResponsesIns = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 7, 9), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msSipStatsResponsesIns.setStatus('current')
msSipStatsResponsesOuts = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 7, 10), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msSipStatsResponsesOuts.setStatus('current')
msSipStatsInvite200OKRetransmitsOuts = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 7, 11), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msSipStatsInvite200OKRetransmitsOuts.setStatus('current')
msSipStatsRequestRetransmittedIns = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 7, 12), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msSipStatsRequestRetransmittedIns.setStatus('current')
msSipStatsReferOuts = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 7, 13), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msSipStatsReferOuts.setStatus('current')
msRedirectsCount = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 7, 14), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msRedirectsCount.setStatus('current')
msTimeOutRouteAdvancesCount = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 7, 15), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msTimeOutRouteAdvancesCount.setStatus('current')
msRouteAdvancesCount = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 7, 16), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msRouteAdvancesCount.setStatus('current')
msMSCMLPlayCollect = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 8, 1), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msMSCMLPlayCollect.setStatus('current')
msMSCMLPlayCollectFailed = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 8, 2), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msMSCMLPlayCollectFailed.setStatus('current')
msMSCMLPlay = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 8, 3), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msMSCMLPlay.setStatus('current')
msMSCMLPlayFailed = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 8, 4), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msMSCMLPlayFailed.setStatus('current')
msMSCMLPlayRecord = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 8, 5), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msMSCMLPlayRecord.setStatus('current')
msMSCMLRecordFailed = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 8, 6), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msMSCMLRecordFailed.setStatus('current')
msMSCMLSendMail = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 8, 7), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msMSCMLSendMail.setStatus('current')
msMSCMLSendMailFailed = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 8, 8), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msMSCMLSendMailFailed.setStatus('current')
msMSCMLTotalRecordingDuration = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 8, 9), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msMSCMLTotalRecordingDuration.setStatus('current')
msMSCMLEmptyRecordings = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 8, 10), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msMSCMLEmptyRecordings.setStatus('current')
msFilesDownloaded = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 5, 1), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msFilesDownloaded.setStatus('current')
msTotalSizeDownloadedFiles = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 5, 2), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msTotalSizeDownloadedFiles.setStatus('current')
msFilesRetrievedFromCache = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 5, 3), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msFilesRetrievedFromCache.setStatus('current')
msLiveAudioRequestCount = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 9, 1), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msLiveAudioRequestCount.setStatus('obsolete')
msLiveAudioFailureCount = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 9, 2), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msLiveAudioFailureCount.setStatus('obsolete')
msLiveAudioTotalDuration = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 9, 3), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msLiveAudioTotalDuration.setStatus('obsolete')
msLiveAudioULawUserCount = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 9, 4), Gauge32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: msLiveAudioULawUserCount.setStatus('obsolete')
msLiveAudioALawUserCount = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 9, 5), Gauge32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: msLiveAudioALawUserCount.setStatus('obsolete')
msLiveAudioG726UserCount = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 9, 6), Gauge32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: msLiveAudioG726UserCount.setStatus('obsolete')
msLiveAudioG729UserCount = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 9, 7), Gauge32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: msLiveAudioG729UserCount.setStatus('obsolete')
msVideoRecorded = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 10, 6), Counter32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msVideoRecorded.setStatus('current')
msVideoPlayback = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 10, 7), Counter32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msVideoPlayback.setStatus('current')
msFaxReceived = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 11, 1), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msFaxReceived.setStatus('current')
msFaxReceptionFailure = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 11, 2), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msFaxReceptionFailure.setStatus('current')
msFaxPrinted = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 11, 3), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msFaxPrinted.setStatus('current')
msFaxPrintingFailure = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 11, 4), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msFaxPrintingFailure.setStatus('current')
msVoiceXMLErrorCount = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 12, 1), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msVoiceXMLErrorCount.setStatus('current')
msVoiceXMLFilesDownloaded = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 12, 2), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msVoiceXMLFilesDownloaded.setStatus('current')
msCallControlXMLSessionCount = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 13, 1), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msCallControlXMLSessionCount.setStatus('current')
msCallControlXMLCreateCallCount = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 13, 2), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msCallControlXMLCreateCallCount.setStatus('current')
msCallControlXMLDialogCount = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 13, 3), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msCallControlXMLDialogCount.setStatus('current')
msCallControlXMLConfCount = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 13, 4), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msCallControlXMLConfCount.setStatus('current')
resetAllMSCounters = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 6, 1), Counter32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: resetAllMSCounters.setStatus('current')
mrcp = MibIdentifier((1, 3, 6, 1, 4, 1, 6431, 1, 3, 14, 1))
msMrcpAsrSessionsCount = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 14, 1, 1), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msMrcpAsrSessionsCount.setStatus('current')
msMrcpAsrSessionsInUse = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 14, 1, 2), Gauge32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msMrcpAsrSessionsInUse.setStatus('current')
msMrcpTtsSessionsCount = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 14, 1, 3), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msMrcpTtsSessionsCount.setStatus('current')
msMrcpTtsSessionsInUse = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 14, 1, 4), Gauge32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msMrcpTtsSessionsInUse.setStatus('current')
msMrcpRecognitionAttemptsCount = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 14, 1, 8), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msMrcpRecognitionAttemptsCount.setStatus('current')
msMrcpSuccessfulRecognitionsCount = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 14, 1, 9), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msMrcpSuccessfulRecognitionsCount.setStatus('current')
msMrcpRequestsCount = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 14, 1, 10), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msMrcpRequestsCount.setStatus('current')
msMrcpFailedRequestsCount = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 14, 1, 11), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msMrcpFailedRequestsCount.setStatus('current')
msMrcpFailedConnectionsCount = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 14, 1, 12), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msMrcpFailedConnectionsCount.setStatus('current')
msMrcpKeepAliveFailuresCount = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 14, 1, 13), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msMrcpKeepAliveFailuresCount.setStatus('current')
msMrcpSpeakRequestsCount = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 14, 1, 14), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msMrcpSpeakRequestsCount.setStatus('current')
msMrcpSpeakRequestFailuresCount = MibScalar((1, 3, 6, 1, 4, 1, 6431, 1, 3, 14, 1, 15), Counter64()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: msMrcpSpeakRequestFailuresCount.setStatus('current')
bwMSGroups = MibIdentifier((1, 3, 6, 1, 4, 1, 6431, 1, 3, 20, 1))
bwMSCompliancy = MibIdentifier((1, 3, 6, 1, 4, 1, 6431, 1, 3, 20, 2))
bwMSGroupMCP = ObjectGroup((1, 3, 6, 1, 4, 1, 6431, 1, 3, 20, 1, 1)).setObjects(("BW-BroadworksMediaServer", "msPortsInUse"), ("BW-BroadworksMediaServer", "msNoPortAvailableErrors"), ("BW-BroadworksMediaServer", "msMCPNotificationsTransmitted"), ("BW-BroadworksMediaServer", "msMCPNotificationsRetransmitted"), ("BW-BroadworksMediaServer", "msMCPCommandsReceived"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    bwMSGroupMCP = bwMSGroupMCP.setStatus('current')
bwMSGroupMCPConferencing = ObjectGroup((1, 3, 6, 1, 4, 1, 6431, 1, 3, 20, 1, 2)).setObjects(("BW-BroadworksMediaServer", "msConfAddParticipantFailed"), ("BW-BroadworksMediaServer", "msConfAddParticipant"), ("BW-BroadworksMediaServer", "msConfAllocateBridge"), ("BW-BroadworksMediaServer", "msConfAllocateBridgeFailed"), ("BW-BroadworksMediaServer", "msConfRemoveParticipant"), ("BW-BroadworksMediaServer", "msConfRemoveParticipantFailed"), ("BW-BroadworksMediaServer", "msConfCurrentPortsInUse"), ("BW-BroadworksMediaServer", "msConferenceCount"), ("BW-BroadworksMediaServer", "msConfTotalDuration"), ("BW-BroadworksMediaServer", "msConfUpdateParticipant"), ("BW-BroadworksMediaServer", "msConfUpdateParticipantFailed"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    bwMSGroupMCPConferencing = bwMSGroupMCPConferencing.setStatus('current')
bwMSGroupMCPIVR = ObjectGroup((1, 3, 6, 1, 4, 1, 6431, 1, 3, 20, 1, 3)).setObjects(("BW-BroadworksMediaServer", "msIvrFreeAudioMemory"), ("BW-BroadworksMediaServer", "msIvrAudioMemoryInUse"), ("BW-BroadworksMediaServer", "msIvrCurrentPortsInUse"), ("BW-BroadworksMediaServer", "msIvrCreateConnection"), ("BW-BroadworksMediaServer", "msIvrCreateConnectionFailed"), ("BW-BroadworksMediaServer", "msIvrUpdateConnection"), ("BW-BroadworksMediaServer", "msIvrUpdateConnectionFailed"), ("BW-BroadworksMediaServer", "msIvrPlay"), ("BW-BroadworksMediaServer", "msIvrPlayFailed"), ("BW-BroadworksMediaServer", "msIvrPlayCollect"), ("BW-BroadworksMediaServer", "msIvrPlayCollectFailed"), ("BW-BroadworksMediaServer", "msIvrPlayRecord"), ("BW-BroadworksMediaServer", "msIvrPlayRecordFailed"), ("BW-BroadworksMediaServer", "msIvrSendEmail"), ("BW-BroadworksMediaServer", "msIvrSendEmailFailed"), ("BW-BroadworksMediaServer", "msIvrSessionCount"), ("BW-BroadworksMediaServer", "msIvrTotalDuration"), ("BW-BroadworksMediaServer", "msIvrTotalRecordingDuration"), ("BW-BroadworksMediaServer", "msIvrMerge"), ("BW-BroadworksMediaServer", "msIvrMergeFailed"), ("BW-BroadworksMediaServer", "msIvrEmptyRecordings"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    bwMSGroupMCPIVR = bwMSGroupMCPIVR.setStatus('current')
bwMSGroupRTP = ObjectGroup((1, 3, 6, 1, 4, 1, 6431, 1, 3, 20, 1, 4)).setObjects(("BW-BroadworksMediaServer", "msRtcpSenderReports"), ("BW-BroadworksMediaServer", "msRtpPacketsExpected"), ("BW-BroadworksMediaServer", "msRtpPacketsReceived"), ("BW-BroadworksMediaServer", "msRtpOutOfOrder"), ("BW-BroadworksMediaServer", "msRtpBadPayload"), ("BW-BroadworksMediaServer", "msRtpSsrc"), ("BW-BroadworksMediaServer", "msRtpReceivedPacketJitter"), ("BW-BroadworksMediaServer", "msRtpCumulativePacketsLost"), ("BW-BroadworksMediaServer", "msRtpPacketsSent"), ("BW-BroadworksMediaServer", "msRtpFramesSkipped"), ("BW-BroadworksMediaServer", "msRtpTransmitJitter"), ("BW-BroadworksMediaServer", "msRtpSessionsCount"), ("BW-BroadworksMediaServer", "msRtpSessionsInUse"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    bwMSGroupRTP = bwMSGroupRTP.setStatus('current')
bwMSGroupSMTP = ObjectGroup((1, 3, 6, 1, 4, 1, 6431, 1, 3, 20, 1, 5)).setObjects(("BW-BroadworksMediaServer", "msPrimaryEmailSent"), ("BW-BroadworksMediaServer", "msPrimarySmtpErrors"), ("BW-BroadworksMediaServer", "msSecondaryEmailSent"), ("BW-BroadworksMediaServer", "msSecondarySmtpErrors"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    bwMSGroupSMTP = bwMSGroupSMTP.setStatus('current')
bwMSGroupSystem = ObjectGroup((1, 3, 6, 1, 4, 1, 6431, 1, 3, 20, 1, 6)).setObjects(("BW-BroadworksMediaServer", "msAlarmsCount"), ("BW-BroadworksMediaServer", "msSoftwareErrorsCount"), ("BW-BroadworksMediaServer", "msACLViolationCount"), ("BW-BroadworksMediaServer", "msMaxCapacityInPorts"), ("BW-BroadworksMediaServer", "msNumLicensedPorts"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    bwMSGroupSystem = bwMSGroupSystem.setStatus('current')
bwMSGroupHTTP = ObjectGroup((1, 3, 6, 1, 4, 1, 6431, 1, 3, 20, 1, 7)).setObjects(("BW-BroadworksMediaServer", "msFilesDownloaded"), ("BW-BroadworksMediaServer", "msTotalSizeDownloadedFiles"), ("BW-BroadworksMediaServer", "msFilesRetrievedFromCache"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    bwMSGroupHTTP = bwMSGroupHTTP.setStatus('current')
bwMSGroupManagement = ObjectGroup((1, 3, 6, 1, 4, 1, 6431, 1, 3, 20, 1, 8)).setObjects(("BW-BroadworksMediaServer", "resetAllMSCounters"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    bwMSGroupManagement = bwMSGroupManagement.setStatus('current')
bwMSGroupSIP = ObjectGroup((1, 3, 6, 1, 4, 1, 6431, 1, 3, 20, 1, 9)).setObjects(("BW-BroadworksMediaServer", "msSipStatsInviteIns"), ("BW-BroadworksMediaServer", "msSipStatsAckIns"), ("BW-BroadworksMediaServer", "msSipStatsByeIns"), ("BW-BroadworksMediaServer", "msSipStatsByeOuts"), ("BW-BroadworksMediaServer", "msSipStatsInfoIns"), ("BW-BroadworksMediaServer", "msSipStatsInfoOuts"), ("BW-BroadworksMediaServer", "msSipStatsOthersIns"), ("BW-BroadworksMediaServer", "msSipStatsOthersOuts"), ("BW-BroadworksMediaServer", "msSipStatsResponsesIns"), ("BW-BroadworksMediaServer", "msSipStatsResponsesOuts"), ("BW-BroadworksMediaServer", "msSipStatsInvite200OKRetransmitsOuts"), ("BW-BroadworksMediaServer", "msSipStatsRequestRetransmittedIns"), ("BW-BroadworksMediaServer", "msSipStatsReferOuts"), ("BW-BroadworksMediaServer", "msRedirectsCount"), ("BW-BroadworksMediaServer", "msTimeOutRouteAdvancesCount"), ("BW-BroadworksMediaServer", "msRouteAdvancesCount"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    bwMSGroupSIP = bwMSGroupSIP.setStatus('current')
bwMSGroupMSCML = ObjectGroup((1, 3, 6, 1, 4, 1, 6431, 1, 3, 20, 1, 10)).setObjects(("BW-BroadworksMediaServer", "msMSCMLPlayCollect"), ("BW-BroadworksMediaServer", "msMSCMLPlayCollectFailed"), ("BW-BroadworksMediaServer", "msMSCMLPlay"), ("BW-BroadworksMediaServer", "msMSCMLPlayFailed"), ("BW-BroadworksMediaServer", "msMSCMLPlayRecord"), ("BW-BroadworksMediaServer", "msMSCMLRecordFailed"), ("BW-BroadworksMediaServer", "msMSCMLSendMail"), ("BW-BroadworksMediaServer", "msMSCMLSendMailFailed"), ("BW-BroadworksMediaServer", "msMSCMLTotalRecordingDuration"), ("BW-BroadworksMediaServer", "msMSCMLEmptyRecordings"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    bwMSGroupMSCML = bwMSGroupMSCML.setStatus('current')
bwMSGroupLiveAudio = ObjectGroup((1, 3, 6, 1, 4, 1, 6431, 1, 3, 20, 1, 11)).setObjects(("BW-BroadworksMediaServer", "msLiveAudioRequestCount"), ("BW-BroadworksMediaServer", "msLiveAudioFailureCount"), ("BW-BroadworksMediaServer", "msLiveAudioTotalDuration"), ("BW-BroadworksMediaServer", "msLiveAudioULawUserCount"), ("BW-BroadworksMediaServer", "msLiveAudioALawUserCount"), ("BW-BroadworksMediaServer", "msLiveAudioG726UserCount"), ("BW-BroadworksMediaServer", "msLiveAudioG729UserCount"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    bwMSGroupLiveAudio = bwMSGroupLiveAudio.setStatus('current')
bwMSGroupVideo = ObjectGroup((1, 3, 6, 1, 4, 1, 6431, 1, 3, 20, 1, 12)).setObjects(("BW-BroadworksMediaServer", "msVideoRecorded"), ("BW-BroadworksMediaServer", "msVideoPlayback"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    bwMSGroupVideo = bwMSGroupVideo.setStatus('current')
bwMSGroupFax = ObjectGroup((1, 3, 6, 1, 4, 1, 6431, 1, 3, 20, 1, 13)).setObjects(("BW-BroadworksMediaServer", "msFaxReceived"), ("BW-BroadworksMediaServer", "msFaxReceptionFailure"), ("BW-BroadworksMediaServer", "msFaxPrinted"), ("BW-BroadworksMediaServer", "msFaxPrintingFailure"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    bwMSGroupFax = bwMSGroupFax.setStatus('current')
bwMSGroupVxml = ObjectGroup((1, 3, 6, 1, 4, 1, 6431, 1, 3, 20, 1, 14)).setObjects(("BW-BroadworksMediaServer", "msVoiceXMLErrorCount"), ("BW-BroadworksMediaServer", "msVoiceXMLFilesDownloaded"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    bwMSGroupVxml = bwMSGroupVxml.setStatus('current')
bwMSGroupCcxml = ObjectGroup((1, 3, 6, 1, 4, 1, 6431, 1, 3, 20, 1, 15)).setObjects(("BW-BroadworksMediaServer", "msCallControlXMLSessionCount"), ("BW-BroadworksMediaServer", "msCallControlXMLCreateCallCount"), ("BW-BroadworksMediaServer", "msCallControlXMLDialogCount"), ("BW-BroadworksMediaServer", "msCallControlXMLConfCount"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    bwMSGroupCcxml = bwMSGroupCcxml.setStatus('current')
bwMSGroupMrcp = ObjectGroup((1, 3, 6, 1, 4, 1, 6431, 1, 3, 20, 1, 16)).setObjects(("BW-BroadworksMediaServer", "msCallControlXMLConfCount"), ("BW-BroadworksMediaServer", "msMrcpAsrSessionsInUse"), ("BW-BroadworksMediaServer", "msMrcpTtsSessionsCount"), ("BW-BroadworksMediaServer", "msMrcpTtsSessionsInUse"), ("BW-BroadworksMediaServer", "msMrcpRecognitionAttemptsCount"), ("BW-BroadworksMediaServer", "msMrcpSuccessfulRecognitionsCount"), ("BW-BroadworksMediaServer", "msMrcpRequestsCount"), ("BW-BroadworksMediaServer", "msMrcpFailedRequestsCount"), ("BW-BroadworksMediaServer", "msMrcpFailedConnectionsCount"), ("BW-BroadworksMediaServer", "msMrcpKeepAliveFailuresCount"), ("BW-BroadworksMediaServer", "msMrcpSpeakRequestsCount"), ("BW-BroadworksMediaServer", "msMrcpSpeakRequestFailuresCount"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    bwMSGroupMrcp = bwMSGroupMrcp.setStatus('current')
bwMsBasicCompliance = ModuleCompliance((1, 3, 6, 1, 4, 1, 6431, 1, 3, 20, 2, 1)).setObjects(("BW-BroadworksMediaServer", "bwMSGroupMCP"), ("BW-BroadworksMediaServer", "bwMSGroupMCPConferencing"), ("BW-BroadworksMediaServer", "bwMSGroupMCPIVR"), ("BW-BroadworksMediaServer", "bwMSGroupRTP"), ("BW-BroadworksMediaServer", "bwMSGroupSMTP"), ("BW-BroadworksMediaServer", "bwMSGroupSystem"), ("BW-BroadworksMediaServer", "bwMSGroupHTTP"), ("BW-BroadworksMediaServer", "bwMSGroupManagement"), ("BW-BroadworksMediaServer", "bwMSGroupSIP"), ("BW-BroadworksMediaServer", "bwMSGroupMSCML"), ("BW-BroadworksMediaServer", "bwMSGroupLiveAudio"), ("BW-BroadworksMediaServer", "bwMSGroupVideo"), ("BW-BroadworksMediaServer", "bwMSGroupFax"), ("BW-BroadworksMediaServer", "bwMSGroupVxml"), ("BW-BroadworksMediaServer", "bwMSGroupCcxml"), ("BW-BroadworksMediaServer", "bwMSGroupMrcp"))

if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    bwMsBasicCompliance = bwMsBasicCompliance.setStatus('obsolete')
mibBuilder.exportSymbols("BW-BroadworksMediaServer", PYSNMP_MODULE_ID=broadsoft, broadsoft=broadsoft, broadworks=broadworks, bwMSCompliancy=bwMSCompliancy, bwMSGroupCcxml=bwMSGroupCcxml, bwMSGroupFax=bwMSGroupFax, bwMSGroupHTTP=bwMSGroupHTTP, bwMSGroupLiveAudio=bwMSGroupLiveAudio, bwMSGroupMCP=bwMSGroupMCP, bwMSGroupMCPConferencing=bwMSGroupMCPConferencing, bwMSGroupMCPIVR=bwMSGroupMCPIVR, bwMSGroupMSCML=bwMSGroupMSCML, bwMSGroupManagement=bwMSGroupManagement, bwMSGroupMrcp=bwMSGroupMrcp, bwMSGroupRTP=bwMSGroupRTP, bwMSGroupSIP=bwMSGroupSIP, bwMSGroupSMTP=bwMSGroupSMTP, bwMSGroupSystem=bwMSGroupSystem, bwMSGroupVideo=bwMSGroupVideo, bwMSGroupVxml=bwMSGroupVxml, bwMSGroups=bwMSGroups, bwMsBasicCompliance=bwMsBasicCompliance, bwMsConformance=bwMsConformance, ccxml=ccxml, conferencing=conferencing, fax=fax, http=http, interfaces=interfaces, ivr=ivr, liveaudio=liveaudio, management=management, mcp=mcp, mediaServer=mediaServer, mrcp=mrcp, msACLViolationCount=msACLViolationCount, msAlarmsCount=msAlarmsCount, msCallControlXMLConfCount=msCallControlXMLConfCount, msCallControlXMLCreateCallCount=msCallControlXMLCreateCallCount, msCallControlXMLDialogCount=msCallControlXMLDialogCount, msCallControlXMLSessionCount=msCallControlXMLSessionCount, msConfAddParticipant=msConfAddParticipant, msConfAddParticipantFailed=msConfAddParticipantFailed, msConfAllocateBridge=msConfAllocateBridge, msConfAllocateBridgeFailed=msConfAllocateBridgeFailed, msConfCurrentPortsInUse=msConfCurrentPortsInUse, msConfRemoveParticipant=msConfRemoveParticipant, msConfRemoveParticipantFailed=msConfRemoveParticipantFailed, msConfTotalDuration=msConfTotalDuration, msConfUpdateParticipant=msConfUpdateParticipant, msConfUpdateParticipantFailed=msConfUpdateParticipantFailed, msConferenceCount=msConferenceCount, msFaxPrinted=msFaxPrinted, msFaxPrintingFailure=msFaxPrintingFailure, msFaxReceived=msFaxReceived, msFaxReceptionFailure=msFaxReceptionFailure, msFilesDownloaded=msFilesDownloaded, msFilesRetrievedFromCache=msFilesRetrievedFromCache, msIvrAudioMemoryInUse=msIvrAudioMemoryInUse, msIvrCreateConnection=msIvrCreateConnection, msIvrCreateConnectionFailed=msIvrCreateConnectionFailed, msIvrCurrentPortsInUse=msIvrCurrentPortsInUse, msIvrEmptyRecordings=msIvrEmptyRecordings, msIvrFreeAudioMemory=msIvrFreeAudioMemory, msIvrMerge=msIvrMerge, msIvrMergeFailed=msIvrMergeFailed, msIvrPlay=msIvrPlay, msIvrPlayCollect=msIvrPlayCollect, msIvrPlayCollectFailed=msIvrPlayCollectFailed, msIvrPlayFailed=msIvrPlayFailed, msIvrPlayRecord=msIvrPlayRecord, msIvrPlayRecordFailed=msIvrPlayRecordFailed, msIvrSendEmail=msIvrSendEmail, msIvrSendEmailFailed=msIvrSendEmailFailed, msIvrSessionCount=msIvrSessionCount, msIvrTotalDuration=msIvrTotalDuration, msIvrTotalRecordingDuration=msIvrTotalRecordingDuration, msIvrUpdateConnection=msIvrUpdateConnection, msIvrUpdateConnectionFailed=msIvrUpdateConnectionFailed, msLiveAudioALawUserCount=msLiveAudioALawUserCount, msLiveAudioFailureCount=msLiveAudioFailureCount, msLiveAudioG726UserCount=msLiveAudioG726UserCount, msLiveAudioG729UserCount=msLiveAudioG729UserCount, msLiveAudioRequestCount=msLiveAudioRequestCount, msLiveAudioTotalDuration=msLiveAudioTotalDuration, msLiveAudioULawUserCount=msLiveAudioULawUserCount, msMCPCommandsReceived=msMCPCommandsReceived, msMCPNotificationsRetransmitted=msMCPNotificationsRetransmitted, msMCPNotificationsTransmitted=msMCPNotificationsTransmitted, msMSCMLEmptyRecordings=msMSCMLEmptyRecordings, msMSCMLPlay=msMSCMLPlay, msMSCMLPlayCollect=msMSCMLPlayCollect, msMSCMLPlayCollectFailed=msMSCMLPlayCollectFailed, msMSCMLPlayFailed=msMSCMLPlayFailed, msMSCMLPlayRecord=msMSCMLPlayRecord, msMSCMLRecordFailed=msMSCMLRecordFailed, msMSCMLSendMail=msMSCMLSendMail, msMSCMLSendMailFailed=msMSCMLSendMailFailed, msMSCMLTotalRecordingDuration=msMSCMLTotalRecordingDuration, msMaxCapacityInPorts=msMaxCapacityInPorts, msMrcpAsrSessionsCount=msMrcpAsrSessionsCount, msMrcpAsrSessionsInUse=msMrcpAsrSessionsInUse, msMrcpFailedConnectionsCount=msMrcpFailedConnectionsCount, msMrcpFailedRequestsCount=msMrcpFailedRequestsCount, msMrcpKeepAliveFailuresCount=msMrcpKeepAliveFailuresCount, msMrcpRecognitionAttemptsCount=msMrcpRecognitionAttemptsCount, msMrcpRequestsCount=msMrcpRequestsCount, msMrcpSpeakRequestFailuresCount=msMrcpSpeakRequestFailuresCount, msMrcpSpeakRequestsCount=msMrcpSpeakRequestsCount, msMrcpSuccessfulRecognitionsCount=msMrcpSuccessfulRecognitionsCount, msMrcpTtsSessionsCount=msMrcpTtsSessionsCount, msMrcpTtsSessionsInUse=msMrcpTtsSessionsInUse, msNoPortAvailableErrors=msNoPortAvailableErrors, msNumLicensedPorts=msNumLicensedPorts, msPortsInUse=msPortsInUse, msPrimaryEmailSent=msPrimaryEmailSent, msPrimarySmtpErrors=msPrimarySmtpErrors, msRedirectsCount=msRedirectsCount, msRouteAdvancesCount=msRouteAdvancesCount, msRtcpSenderReports=msRtcpSenderReports, msRtpBadPayload=msRtpBadPayload, msRtpCumulativePacketsLost=msRtpCumulativePacketsLost, msRtpFramesSkipped=msRtpFramesSkipped, msRtpOutOfOrder=msRtpOutOfOrder, msRtpPacketsExpected=msRtpPacketsExpected, msRtpPacketsReceived=msRtpPacketsReceived, msRtpPacketsSent=msRtpPacketsSent, msRtpReceivedPacketJitter=msRtpReceivedPacketJitter, msRtpSessionsCount=msRtpSessionsCount, msRtpSessionsInUse=msRtpSessionsInUse, msRtpSsrc=msRtpSsrc, msRtpTransmitJitter=msRtpTransmitJitter, msSecondaryEmailSent=msSecondaryEmailSent, msSecondarySmtpErrors=msSecondarySmtpErrors, msSipStatsAckIns=msSipStatsAckIns, msSipStatsByeIns=msSipStatsByeIns, msSipStatsByeOuts=msSipStatsByeOuts, msSipStatsInfoIns=msSipStatsInfoIns, msSipStatsInfoOuts=msSipStatsInfoOuts, msSipStatsInvite200OKRetransmitsOuts=msSipStatsInvite200OKRetransmitsOuts, msSipStatsInviteIns=msSipStatsInviteIns, msSipStatsOthersIns=msSipStatsOthersIns, msSipStatsOthersOuts=msSipStatsOthersOuts, msSipStatsReferOuts=msSipStatsReferOuts, msSipStatsRequestRetransmittedIns=msSipStatsRequestRetransmittedIns, msSipStatsResponsesIns=msSipStatsResponsesIns, msSipStatsResponsesOuts=msSipStatsResponsesOuts, msSoftwareErrorsCount=msSoftwareErrorsCount, msTimeOutRouteAdvancesCount=msTimeOutRouteAdvancesCount, msTotalSizeDownloadedFiles=msTotalSizeDownloadedFiles, msVideoPlayback=msVideoPlayback, msVideoRecorded=msVideoRecorded, msVoiceXMLErrorCount=msVoiceXMLErrorCount, msVoiceXMLFilesDownloaded=msVoiceXMLFilesDownloaded, mscml=mscml, primary=primary, receive=receive, resetAllMSCounters=resetAllMSCounters, rtp=rtp, secondary=secondary, sip=sip, smtp=smtp, system=system, transmit=transmit, video=video, vxml=vxml)
