#
# PySNMP MIB module CGX-EVENTS-MIB (http://snmplabs.com/pysmi)
# ASN.1 source CGX-EVENTS-MIB
# Source digest sha256:b27b7968f01a8a8d20d6188bf31ebb446dfd188ae5d835a8d1554a0fae40aa71
# Produced by pysmi-2.3.0
#
Integer, ObjectIdentifier, OctetString = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
NamedValues, = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
cgxMgmt, = mibBuilder.importSymbols("CLOUDGENIX-SMI", "cgxMgmt")
ModuleCompliance, NotificationGroup, ObjectGroup = mibBuilder.importSymbols("SNMPv2-CONF", "ModuleCompliance", "NotificationGroup", "ObjectGroup")
Bits, Counter32, Counter64, Gauge32, Integer32, IpAddress, ModuleIdentity, MibIdentifier, NotificationType, ObjectIdentity, MibScalar, MibTable, MibTableRow, MibTableColumn, TimeTicks, Unsigned32, iso = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Counter32", "Counter64", "Gauge32", "Integer32", "IpAddress", "ModuleIdentity", "MibIdentifier", "NotificationType", "ObjectIdentity", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "TimeTicks", "Unsigned32", "iso")
DisplayString, TextualConvention = mibBuilder.importSymbols("SNMPv2-TC", "DisplayString", "TextualConvention")
cgxEventsMIB = ModuleIdentity((1, 3, 6, 1, 4, 1, 50114, 10, 1))
cgxEventsMIB.setRevisions(('2022-02-24 19:35', '2017-06-19 18:00',))
if mibBuilder.loadTexts: cgxEventsMIB.setLastUpdated('2022-02-24 19:35')
if mibBuilder.loadTexts: cgxEventsMIB.setOrganization('Palo Alto Networks, Inc.')
cgxEventsNotifications = MibIdentifier((1, 3, 6, 1, 4, 1, 50114, 10, 1, 0))
cgxVpnLinkUp = NotificationType((1, 3, 6, 1, 4, 1, 50114, 10, 1, 0, 1)).setObjects(("CGX-EVENTS-MIB", "cgxElementId"), ("CGX-EVENTS-MIB", "cgxElementName"), ("CGX-EVENTS-MIB", "cgxElementRemoteId"), ("CGX-EVENTS-MIB", "cgxElementRemoteName"), ("CGX-EVENTS-MIB", "cgxSiteId"), ("CGX-EVENTS-MIB", "cgxSiteName"), ("CGX-EVENTS-MIB", "cgxSiteRemoteId"), ("CGX-EVENTS-MIB", "cgxSiteRemoteName"), ("CGX-EVENTS-MIB", "cgxSiteWanInterfaceId"), ("CGX-EVENTS-MIB", "cgxSiteWanInterfaceName"), ("CGX-EVENTS-MIB", "cgxVpnLinkId"), ("CGX-EVENTS-MIB", "cgxWanNetworkId"), ("CGX-EVENTS-MIB", "cgxWanNetworkName"), ("CGX-EVENTS-MIB", "cgxWanNetworkType"), ("CGX-EVENTS-MIB", "cgxWanNetworkRemoteId"), ("CGX-EVENTS-MIB", "cgxWanNetworkRemoteName"), ("CGX-EVENTS-MIB", "cgxWanNetworkRemoteType"))
if mibBuilder.loadTexts: cgxVpnLinkUp.setStatus('current')
cgxVpnLinkDown = NotificationType((1, 3, 6, 1, 4, 1, 50114, 10, 1, 0, 2)).setObjects(("CGX-EVENTS-MIB", "cgxElementId"), ("CGX-EVENTS-MIB", "cgxElementName"), ("CGX-EVENTS-MIB", "cgxElementRemoteId"), ("CGX-EVENTS-MIB", "cgxElementRemoteName"), ("CGX-EVENTS-MIB", "cgxSiteId"), ("CGX-EVENTS-MIB", "cgxSiteName"), ("CGX-EVENTS-MIB", "cgxSiteRemoteId"), ("CGX-EVENTS-MIB", "cgxSiteRemoteName"), ("CGX-EVENTS-MIB", "cgxSiteWanInterfaceId"), ("CGX-EVENTS-MIB", "cgxSiteWanInterfaceName"), ("CGX-EVENTS-MIB", "cgxVpnLinkId"), ("CGX-EVENTS-MIB", "cgxWanNetworkId"), ("CGX-EVENTS-MIB", "cgxWanNetworkName"), ("CGX-EVENTS-MIB", "cgxWanNetworkType"), ("CGX-EVENTS-MIB", "cgxWanNetworkRemoteId"), ("CGX-EVENTS-MIB", "cgxWanNetworkRemoteName"), ("CGX-EVENTS-MIB", "cgxWanNetworkRemoteType"))
if mibBuilder.loadTexts: cgxVpnLinkDown.setStatus('current')
cgxVpnPeerUnreachableClear = NotificationType((1, 3, 6, 1, 4, 1, 50114, 10, 1, 0, 3)).setObjects(("CGX-EVENTS-MIB", "cgxElementId"), ("CGX-EVENTS-MIB", "cgxElementName"), ("CGX-EVENTS-MIB", "cgxElementRemoteId"), ("CGX-EVENTS-MIB", "cgxElementRemoteName"), ("CGX-EVENTS-MIB", "cgxSiteId"), ("CGX-EVENTS-MIB", "cgxSiteName"), ("CGX-EVENTS-MIB", "cgxSiteRemoteId"), ("CGX-EVENTS-MIB", "cgxSiteRemoteName"), ("CGX-EVENTS-MIB", "cgxSiteWanInterfaceId"), ("CGX-EVENTS-MIB", "cgxSiteWanInterfaceName"), ("CGX-EVENTS-MIB", "cgxVpnLinkId"), ("CGX-EVENTS-MIB", "cgxWanNetworkId"), ("CGX-EVENTS-MIB", "cgxWanNetworkName"), ("CGX-EVENTS-MIB", "cgxWanNetworkType"), ("CGX-EVENTS-MIB", "cgxWanNetworkRemoteId"), ("CGX-EVENTS-MIB", "cgxWanNetworkRemoteName"), ("CGX-EVENTS-MIB", "cgxWanNetworkRemoteType"))
if mibBuilder.loadTexts: cgxVpnPeerUnreachableClear.setStatus('current')
cgxVpnPeerUnreachable = NotificationType((1, 3, 6, 1, 4, 1, 50114, 10, 1, 0, 4)).setObjects(("CGX-EVENTS-MIB", "cgxElementId"), ("CGX-EVENTS-MIB", "cgxElementName"), ("CGX-EVENTS-MIB", "cgxElementRemoteId"), ("CGX-EVENTS-MIB", "cgxElementRemoteName"), ("CGX-EVENTS-MIB", "cgxSiteId"), ("CGX-EVENTS-MIB", "cgxSiteName"), ("CGX-EVENTS-MIB", "cgxSiteRemoteId"), ("CGX-EVENTS-MIB", "cgxSiteRemoteName"), ("CGX-EVENTS-MIB", "cgxSiteWanInterfaceId"), ("CGX-EVENTS-MIB", "cgxSiteWanInterfaceName"), ("CGX-EVENTS-MIB", "cgxVpnLinkId"), ("CGX-EVENTS-MIB", "cgxWanNetworkId"), ("CGX-EVENTS-MIB", "cgxWanNetworkName"), ("CGX-EVENTS-MIB", "cgxWanNetworkType"), ("CGX-EVENTS-MIB", "cgxWanNetworkRemoteId"), ("CGX-EVENTS-MIB", "cgxWanNetworkRemoteName"), ("CGX-EVENTS-MIB", "cgxWanNetworkRemoteType"))
if mibBuilder.loadTexts: cgxVpnPeerUnreachable.setStatus('current')
cgxVpnBfdUp = NotificationType((1, 3, 6, 1, 4, 1, 50114, 10, 1, 0, 5)).setObjects(("CGX-EVENTS-MIB", "cgxElementId"), ("CGX-EVENTS-MIB", "cgxElementName"), ("CGX-EVENTS-MIB", "cgxElementRemoteId"), ("CGX-EVENTS-MIB", "cgxElementRemoteName"), ("CGX-EVENTS-MIB", "cgxSiteId"), ("CGX-EVENTS-MIB", "cgxSiteName"), ("CGX-EVENTS-MIB", "cgxSiteRemoteId"), ("CGX-EVENTS-MIB", "cgxSiteRemoteName"), ("CGX-EVENTS-MIB", "cgxSiteWanInterfaceId"), ("CGX-EVENTS-MIB", "cgxSiteWanInterfaceName"), ("CGX-EVENTS-MIB", "cgxVpnLinkId"), ("CGX-EVENTS-MIB", "cgxWanNetworkId"), ("CGX-EVENTS-MIB", "cgxWanNetworkName"), ("CGX-EVENTS-MIB", "cgxWanNetworkType"), ("CGX-EVENTS-MIB", "cgxWanNetworkRemoteId"), ("CGX-EVENTS-MIB", "cgxWanNetworkRemoteName"), ("CGX-EVENTS-MIB", "cgxWanNetworkRemoteType"))
if mibBuilder.loadTexts: cgxVpnBfdUp.setStatus('current')
cgxVpnBfdDown = NotificationType((1, 3, 6, 1, 4, 1, 50114, 10, 1, 0, 6)).setObjects(("CGX-EVENTS-MIB", "cgxElementId"), ("CGX-EVENTS-MIB", "cgxElementName"), ("CGX-EVENTS-MIB", "cgxElementRemoteId"), ("CGX-EVENTS-MIB", "cgxElementRemoteName"), ("CGX-EVENTS-MIB", "cgxSiteId"), ("CGX-EVENTS-MIB", "cgxSiteName"), ("CGX-EVENTS-MIB", "cgxSiteRemoteId"), ("CGX-EVENTS-MIB", "cgxSiteRemoteName"), ("CGX-EVENTS-MIB", "cgxSiteWanInterfaceId"), ("CGX-EVENTS-MIB", "cgxSiteWanInterfaceName"), ("CGX-EVENTS-MIB", "cgxVpnLinkId"), ("CGX-EVENTS-MIB", "cgxWanNetworkId"), ("CGX-EVENTS-MIB", "cgxWanNetworkName"), ("CGX-EVENTS-MIB", "cgxWanNetworkType"), ("CGX-EVENTS-MIB", "cgxWanNetworkRemoteId"), ("CGX-EVENTS-MIB", "cgxWanNetworkRemoteName"), ("CGX-EVENTS-MIB", "cgxWanNetworkRemoteType"))
if mibBuilder.loadTexts: cgxVpnBfdDown.setStatus('current')
cgxRoutePeerUp = NotificationType((1, 3, 6, 1, 4, 1, 50114, 10, 1, 0, 101)).setObjects(("CGX-EVENTS-MIB", "cgxElementId"), ("CGX-EVENTS-MIB", "cgxElementName"), ("CGX-EVENTS-MIB", "cgxSiteId"), ("CGX-EVENTS-MIB", "cgxSiteName"), ("CGX-EVENTS-MIB", "cgxRoutePeerId"), ("CGX-EVENTS-MIB", "cgxRoutePeerIp"), ("CGX-EVENTS-MIB", "cgxRoutePeerType"))
if mibBuilder.loadTexts: cgxRoutePeerUp.setStatus('current')
cgxRoutePeerDown = NotificationType((1, 3, 6, 1, 4, 1, 50114, 10, 1, 0, 102)).setObjects(("CGX-EVENTS-MIB", "cgxElementId"), ("CGX-EVENTS-MIB", "cgxElementName"), ("CGX-EVENTS-MIB", "cgxSiteId"), ("CGX-EVENTS-MIB", "cgxSiteName"), ("CGX-EVENTS-MIB", "cgxRoutePeerId"), ("CGX-EVENTS-MIB", "cgxRoutePeerIp"), ("CGX-EVENTS-MIB", "cgxRoutePeerType"))
if mibBuilder.loadTexts: cgxRoutePeerDown.setStatus('current')
cgxPrivateWanUnreachableClear = NotificationType((1, 3, 6, 1, 4, 1, 50114, 10, 1, 0, 201)).setObjects(("CGX-EVENTS-MIB", "cgxElementId"), ("CGX-EVENTS-MIB", "cgxElementName"), ("CGX-EVENTS-MIB", "cgxSiteId"), ("CGX-EVENTS-MIB", "cgxSiteName"), ("CGX-EVENTS-MIB", "cgxSiteWanInterfaceId"), ("CGX-EVENTS-MIB", "cgxSiteWanInterfaceName"), ("CGX-EVENTS-MIB", "cgxWanNetworkId"), ("CGX-EVENTS-MIB", "cgxWanNetworkName"), ("CGX-EVENTS-MIB", "cgxWanNetworkType"))
if mibBuilder.loadTexts: cgxPrivateWanUnreachableClear.setStatus('current')
cgxPrivateWanUnreachable = NotificationType((1, 3, 6, 1, 4, 1, 50114, 10, 1, 0, 202)).setObjects(("CGX-EVENTS-MIB", "cgxElementId"), ("CGX-EVENTS-MIB", "cgxElementName"), ("CGX-EVENTS-MIB", "cgxSiteId"), ("CGX-EVENTS-MIB", "cgxSiteName"), ("CGX-EVENTS-MIB", "cgxSiteWanInterfaceId"), ("CGX-EVENTS-MIB", "cgxSiteWanInterfaceName"), ("CGX-EVENTS-MIB", "cgxWanNetworkId"), ("CGX-EVENTS-MIB", "cgxWanNetworkName"), ("CGX-EVENTS-MIB", "cgxWanNetworkType"))
if mibBuilder.loadTexts: cgxPrivateWanUnreachable.setStatus('current')
cgxPrivateWanDegradedClear = NotificationType((1, 3, 6, 1, 4, 1, 50114, 10, 1, 0, 203)).setObjects(("CGX-EVENTS-MIB", "cgxElementId"), ("CGX-EVENTS-MIB", "cgxElementName"), ("CGX-EVENTS-MIB", "cgxSiteId"), ("CGX-EVENTS-MIB", "cgxSiteName"), ("CGX-EVENTS-MIB", "cgxSiteWanInterfaceId"), ("CGX-EVENTS-MIB", "cgxSiteWanInterfaceName"), ("CGX-EVENTS-MIB", "cgxWanNetworkId"), ("CGX-EVENTS-MIB", "cgxWanNetworkName"), ("CGX-EVENTS-MIB", "cgxWanNetworkType"))
if mibBuilder.loadTexts: cgxPrivateWanDegradedClear.setStatus('current')
cgxPrivateWanDegraded = NotificationType((1, 3, 6, 1, 4, 1, 50114, 10, 1, 0, 204)).setObjects(("CGX-EVENTS-MIB", "cgxElementId"), ("CGX-EVENTS-MIB", "cgxElementName"), ("CGX-EVENTS-MIB", "cgxSiteId"), ("CGX-EVENTS-MIB", "cgxSiteName"), ("CGX-EVENTS-MIB", "cgxSiteWanInterfaceId"), ("CGX-EVENTS-MIB", "cgxSiteWanInterfaceName"), ("CGX-EVENTS-MIB", "cgxWanNetworkId"), ("CGX-EVENTS-MIB", "cgxWanNetworkName"), ("CGX-EVENTS-MIB", "cgxWanNetworkType"))
if mibBuilder.loadTexts: cgxPrivateWanDegraded.setStatus('current')
cgxPublicWanUp = NotificationType((1, 3, 6, 1, 4, 1, 50114, 10, 1, 0, 205)).setObjects(("CGX-EVENTS-MIB", "cgxElementId"), ("CGX-EVENTS-MIB", "cgxElementName"), ("CGX-EVENTS-MIB", "cgxSiteId"), ("CGX-EVENTS-MIB", "cgxSiteName"), ("CGX-EVENTS-MIB", "cgxSiteWanInterfaceId"), ("CGX-EVENTS-MIB", "cgxSiteWanInterfaceName"), ("CGX-EVENTS-MIB", "cgxWanNetworkId"), ("CGX-EVENTS-MIB", "cgxWanNetworkName"), ("CGX-EVENTS-MIB", "cgxWanNetworkType"))
if mibBuilder.loadTexts: cgxPublicWanUp.setStatus('current')
cgxPublicWanDown = NotificationType((1, 3, 6, 1, 4, 1, 50114, 10, 1, 0, 206)).setObjects(("CGX-EVENTS-MIB", "cgxElementId"), ("CGX-EVENTS-MIB", "cgxElementName"), ("CGX-EVENTS-MIB", "cgxSiteId"), ("CGX-EVENTS-MIB", "cgxSiteName"), ("CGX-EVENTS-MIB", "cgxSiteWanInterfaceId"), ("CGX-EVENTS-MIB", "cgxSiteWanInterfaceName"), ("CGX-EVENTS-MIB", "cgxWanNetworkId"), ("CGX-EVENTS-MIB", "cgxWanNetworkName"), ("CGX-EVENTS-MIB", "cgxWanNetworkType"))
if mibBuilder.loadTexts: cgxPublicWanDown.setStatus('current')
cgxPrivateWanUp = NotificationType((1, 3, 6, 1, 4, 1, 50114, 10, 1, 0, 207)).setObjects(("CGX-EVENTS-MIB", "cgxElementId"), ("CGX-EVENTS-MIB", "cgxElementName"), ("CGX-EVENTS-MIB", "cgxSiteId"), ("CGX-EVENTS-MIB", "cgxSiteName"), ("CGX-EVENTS-MIB", "cgxSiteWanInterfaceId"), ("CGX-EVENTS-MIB", "cgxSiteWanInterfaceName"), ("CGX-EVENTS-MIB", "cgxWanNetworkId"), ("CGX-EVENTS-MIB", "cgxWanNetworkName"), ("CGX-EVENTS-MIB", "cgxWanNetworkType"))
if mibBuilder.loadTexts: cgxPrivateWanUp.setStatus('current')
cgxPrivateWanDown = NotificationType((1, 3, 6, 1, 4, 1, 50114, 10, 1, 0, 208)).setObjects(("CGX-EVENTS-MIB", "cgxElementId"), ("CGX-EVENTS-MIB", "cgxElementName"), ("CGX-EVENTS-MIB", "cgxSiteId"), ("CGX-EVENTS-MIB", "cgxSiteName"), ("CGX-EVENTS-MIB", "cgxSiteWanInterfaceId"), ("CGX-EVENTS-MIB", "cgxSiteWanInterfaceName"), ("CGX-EVENTS-MIB", "cgxWanNetworkId"), ("CGX-EVENTS-MIB", "cgxWanNetworkName"), ("CGX-EVENTS-MIB", "cgxWanNetworkType"))
if mibBuilder.loadTexts: cgxPrivateWanDown.setStatus('current')
cgxProcessStopClear = NotificationType((1, 3, 6, 1, 4, 1, 50114, 10, 1, 0, 301)).setObjects(("CGX-EVENTS-MIB", "cgxElementId"), ("CGX-EVENTS-MIB", "cgxElementName"), ("CGX-EVENTS-MIB", "cgxSiteId"), ("CGX-EVENTS-MIB", "cgxSiteName"), ("CGX-EVENTS-MIB", "cgxProcessName"))
if mibBuilder.loadTexts: cgxProcessStopClear.setStatus('current')
cgxProcessStop = NotificationType((1, 3, 6, 1, 4, 1, 50114, 10, 1, 0, 302)).setObjects(("CGX-EVENTS-MIB", "cgxElementId"), ("CGX-EVENTS-MIB", "cgxElementName"), ("CGX-EVENTS-MIB", "cgxSiteId"), ("CGX-EVENTS-MIB", "cgxSiteName"), ("CGX-EVENTS-MIB", "cgxProcessName"))
if mibBuilder.loadTexts: cgxProcessStop.setStatus('current')
cgxProcessRestart = NotificationType((1, 3, 6, 1, 4, 1, 50114, 10, 1, 0, 303)).setObjects(("CGX-EVENTS-MIB", "cgxElementId"), ("CGX-EVENTS-MIB", "cgxElementName"), ("CGX-EVENTS-MIB", "cgxSiteId"), ("CGX-EVENTS-MIB", "cgxSiteName"), ("CGX-EVENTS-MIB", "cgxProcessName"))
if mibBuilder.loadTexts: cgxProcessRestart.setStatus('current')
cgxEventsObjects = MibIdentifier((1, 3, 6, 1, 4, 1, 50114, 10, 1, 1))
cgxEventsObjectStats = MibIdentifier((1, 3, 6, 1, 4, 1, 50114, 10, 1, 1, 1))
cgxVpnObjects = MibIdentifier((1, 3, 6, 1, 4, 1, 50114, 10, 1, 1, 2))
cgxVpnLinkId = MibScalar((1, 3, 6, 1, 4, 1, 50114, 10, 1, 1, 2, 1), DisplayString()).setMaxAccess("accessiblefornotify")
if mibBuilder.loadTexts: cgxVpnLinkId.setStatus('current')
cgxRoutingObjects = MibIdentifier((1, 3, 6, 1, 4, 1, 50114, 10, 1, 1, 3))
cgxRoutePeerId = MibScalar((1, 3, 6, 1, 4, 1, 50114, 10, 1, 1, 3, 1), DisplayString()).setMaxAccess("accessiblefornotify")
if mibBuilder.loadTexts: cgxRoutePeerId.setStatus('current')
cgxRoutePeerName = MibScalar((1, 3, 6, 1, 4, 1, 50114, 10, 1, 1, 3, 2), DisplayString()).setMaxAccess("accessiblefornotify")
if mibBuilder.loadTexts: cgxRoutePeerName.setStatus('current')
cgxRoutePeerIp = MibScalar((1, 3, 6, 1, 4, 1, 50114, 10, 1, 1, 3, 3), IpAddress()).setMaxAccess("accessiblefornotify")
if mibBuilder.loadTexts: cgxRoutePeerIp.setStatus('current')
cgxRoutePeerType = MibScalar((1, 3, 6, 1, 4, 1, 50114, 10, 1, 1, 3, 4), DisplayString()).setMaxAccess("accessiblefornotify")
if mibBuilder.loadTexts: cgxRoutePeerType.setStatus('current')
cgxSiteObjects = MibIdentifier((1, 3, 6, 1, 4, 1, 50114, 10, 1, 1, 4))
cgxSiteId = MibScalar((1, 3, 6, 1, 4, 1, 50114, 10, 1, 1, 4, 1), DisplayString()).setMaxAccess("accessiblefornotify")
if mibBuilder.loadTexts: cgxSiteId.setStatus('current')
cgxSiteName = MibScalar((1, 3, 6, 1, 4, 1, 50114, 10, 1, 1, 4, 2), DisplayString()).setMaxAccess("accessiblefornotify")
if mibBuilder.loadTexts: cgxSiteName.setStatus('current')
cgxSiteRemoteId = MibScalar((1, 3, 6, 1, 4, 1, 50114, 10, 1, 1, 4, 3), DisplayString()).setMaxAccess("accessiblefornotify")
if mibBuilder.loadTexts: cgxSiteRemoteId.setStatus('current')
cgxSiteRemoteName = MibScalar((1, 3, 6, 1, 4, 1, 50114, 10, 1, 1, 4, 4), DisplayString()).setMaxAccess("accessiblefornotify")
if mibBuilder.loadTexts: cgxSiteRemoteName.setStatus('current')
cgxSiteWanInterfaceId = MibScalar((1, 3, 6, 1, 4, 1, 50114, 10, 1, 1, 4, 5), DisplayString()).setMaxAccess("accessiblefornotify")
if mibBuilder.loadTexts: cgxSiteWanInterfaceId.setStatus('current')
cgxSiteWanInterfaceName = MibScalar((1, 3, 6, 1, 4, 1, 50114, 10, 1, 1, 4, 6), DisplayString()).setMaxAccess("accessiblefornotify")
if mibBuilder.loadTexts: cgxSiteWanInterfaceName.setStatus('current')
cgxElementObjects = MibIdentifier((1, 3, 6, 1, 4, 1, 50114, 10, 1, 1, 5))
cgxElementId = MibScalar((1, 3, 6, 1, 4, 1, 50114, 10, 1, 1, 5, 1), DisplayString()).setMaxAccess("accessiblefornotify")
if mibBuilder.loadTexts: cgxElementId.setStatus('current')
cgxElementName = MibScalar((1, 3, 6, 1, 4, 1, 50114, 10, 1, 1, 5, 2), DisplayString()).setMaxAccess("accessiblefornotify")
if mibBuilder.loadTexts: cgxElementName.setStatus('current')
cgxElementRemoteId = MibScalar((1, 3, 6, 1, 4, 1, 50114, 10, 1, 1, 5, 3), DisplayString()).setMaxAccess("accessiblefornotify")
if mibBuilder.loadTexts: cgxElementRemoteId.setStatus('current')
cgxElementRemoteName = MibScalar((1, 3, 6, 1, 4, 1, 50114, 10, 1, 1, 5, 4), DisplayString()).setMaxAccess("accessiblefornotify")
if mibBuilder.loadTexts: cgxElementRemoteName.setStatus('current')
cgxWanObjects = MibIdentifier((1, 3, 6, 1, 4, 1, 50114, 10, 1, 1, 6))
cgxWanNetworkId = MibScalar((1, 3, 6, 1, 4, 1, 50114, 10, 1, 1, 6, 1), DisplayString()).setMaxAccess("accessiblefornotify")
if mibBuilder.loadTexts: cgxWanNetworkId.setStatus('current')
cgxWanNetworkName = MibScalar((1, 3, 6, 1, 4, 1, 50114, 10, 1, 1, 6, 2), DisplayString()).setMaxAccess("accessiblefornotify")
if mibBuilder.loadTexts: cgxWanNetworkName.setStatus('current')
cgxWanNetworkType = MibScalar((1, 3, 6, 1, 4, 1, 50114, 10, 1, 1, 6, 3), DisplayString()).setMaxAccess("accessiblefornotify")
if mibBuilder.loadTexts: cgxWanNetworkType.setStatus('current')
cgxWanNetworkRemoteId = MibScalar((1, 3, 6, 1, 4, 1, 50114, 10, 1, 1, 6, 4), DisplayString()).setMaxAccess("accessiblefornotify")
if mibBuilder.loadTexts: cgxWanNetworkRemoteId.setStatus('current')
cgxWanNetworkRemoteName = MibScalar((1, 3, 6, 1, 4, 1, 50114, 10, 1, 1, 6, 5), DisplayString()).setMaxAccess("accessiblefornotify")
if mibBuilder.loadTexts: cgxWanNetworkRemoteName.setStatus('current')
cgxWanNetworkRemoteType = MibScalar((1, 3, 6, 1, 4, 1, 50114, 10, 1, 1, 6, 6), DisplayString()).setMaxAccess("accessiblefornotify")
if mibBuilder.loadTexts: cgxWanNetworkRemoteType.setStatus('current')
cgxWanNetworkPrefix = MibScalar((1, 3, 6, 1, 4, 1, 50114, 10, 1, 1, 6, 7), DisplayString()).setMaxAccess("accessiblefornotify")
if mibBuilder.loadTexts: cgxWanNetworkPrefix.setStatus('current')
cgxProcessObjects = MibIdentifier((1, 3, 6, 1, 4, 1, 50114, 10, 1, 1, 7))
cgxProcessId = MibScalar((1, 3, 6, 1, 4, 1, 50114, 10, 1, 1, 7, 1), DisplayString()).setMaxAccess("accessiblefornotify")
if mibBuilder.loadTexts: cgxProcessId.setStatus('current')
cgxProcessName = MibScalar((1, 3, 6, 1, 4, 1, 50114, 10, 1, 1, 7, 2), DisplayString()).setMaxAccess("accessiblefornotify")
if mibBuilder.loadTexts: cgxProcessName.setStatus('current')
cgxEventsConformance = MibIdentifier((1, 3, 6, 1, 4, 1, 50114, 10, 1, 2))
cgxEventsCompliances = MibIdentifier((1, 3, 6, 1, 4, 1, 50114, 10, 1, 2, 1))
cgxEventsMIBCompliance = ModuleCompliance((1, 3, 6, 1, 4, 1, 50114, 10, 1, 2, 1, 1)).setObjects(("CGX-EVENTS-MIB", "cgxElementObjectGroup"), ("CGX-EVENTS-MIB", "cgxProcessNotificationGroup"), ("CGX-EVENTS-MIB", "cgxProcessObjectGroup"), ("CGX-EVENTS-MIB", "cgxRoutingNotificationGroup"), ("CGX-EVENTS-MIB", "cgxRoutingObjectGroup"), ("CGX-EVENTS-MIB", "cgxSiteObjectGroup"), ("CGX-EVENTS-MIB", "cgxVpnNotificationGroup"), ("CGX-EVENTS-MIB", "cgxVpnObjectGroup"), ("CGX-EVENTS-MIB", "cgxWanNotificationGroup"), ("CGX-EVENTS-MIB", "cgxWanObjectGroup"))

if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    cgxEventsMIBCompliance = cgxEventsMIBCompliance.setStatus('current')
cgxEventsGroups = MibIdentifier((1, 3, 6, 1, 4, 1, 50114, 10, 1, 2, 2))
cgxVpnObjectGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 50114, 10, 1, 2, 2, 2)).setObjects(("CGX-EVENTS-MIB", "cgxVpnLinkId"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    cgxVpnObjectGroup = cgxVpnObjectGroup.setStatus('current')
cgxRoutingObjectGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 50114, 10, 1, 2, 2, 3)).setObjects(("CGX-EVENTS-MIB", "cgxRoutePeerId"), ("CGX-EVENTS-MIB", "cgxRoutePeerIp"), ("CGX-EVENTS-MIB", "cgxRoutePeerName"), ("CGX-EVENTS-MIB", "cgxRoutePeerType"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    cgxRoutingObjectGroup = cgxRoutingObjectGroup.setStatus('current')
cgxSiteObjectGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 50114, 10, 1, 2, 2, 4)).setObjects(("CGX-EVENTS-MIB", "cgxSiteId"), ("CGX-EVENTS-MIB", "cgxSiteName"), ("CGX-EVENTS-MIB", "cgxSiteRemoteId"), ("CGX-EVENTS-MIB", "cgxSiteRemoteName"), ("CGX-EVENTS-MIB", "cgxSiteWanInterfaceId"), ("CGX-EVENTS-MIB", "cgxSiteWanInterfaceName"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    cgxSiteObjectGroup = cgxSiteObjectGroup.setStatus('current')
cgxElementObjectGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 50114, 10, 1, 2, 2, 5)).setObjects(("CGX-EVENTS-MIB", "cgxElementId"), ("CGX-EVENTS-MIB", "cgxElementName"), ("CGX-EVENTS-MIB", "cgxElementRemoteId"), ("CGX-EVENTS-MIB", "cgxElementRemoteName"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    cgxElementObjectGroup = cgxElementObjectGroup.setStatus('current')
cgxWanObjectGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 50114, 10, 1, 2, 2, 6)).setObjects(("CGX-EVENTS-MIB", "cgxWanNetworkId"), ("CGX-EVENTS-MIB", "cgxWanNetworkName"), ("CGX-EVENTS-MIB", "cgxWanNetworkType"), ("CGX-EVENTS-MIB", "cgxWanNetworkRemoteId"), ("CGX-EVENTS-MIB", "cgxWanNetworkRemoteName"), ("CGX-EVENTS-MIB", "cgxWanNetworkRemoteType"), ("CGX-EVENTS-MIB", "cgxWanNetworkPrefix"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    cgxWanObjectGroup = cgxWanObjectGroup.setStatus('current')
cgxProcessObjectGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 50114, 10, 1, 2, 2, 7)).setObjects(("CGX-EVENTS-MIB", "cgxProcessId"), ("CGX-EVENTS-MIB", "cgxProcessName"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    cgxProcessObjectGroup = cgxProcessObjectGroup.setStatus('current')
cgxVpnNotificationGroup = NotificationGroup((1, 3, 6, 1, 4, 1, 50114, 10, 1, 2, 2, 102)).setObjects(("CGX-EVENTS-MIB", "cgxVpnBfdDown"), ("CGX-EVENTS-MIB", "cgxVpnBfdUp"), ("CGX-EVENTS-MIB", "cgxVpnLinkDown"), ("CGX-EVENTS-MIB", "cgxVpnLinkUp"), ("CGX-EVENTS-MIB", "cgxVpnPeerUnreachable"), ("CGX-EVENTS-MIB", "cgxVpnPeerUnreachableClear"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    cgxVpnNotificationGroup = cgxVpnNotificationGroup.setStatus('current')
cgxRoutingNotificationGroup = NotificationGroup((1, 3, 6, 1, 4, 1, 50114, 10, 1, 2, 2, 103)).setObjects(("CGX-EVENTS-MIB", "cgxRoutePeerDown"), ("CGX-EVENTS-MIB", "cgxRoutePeerUp"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    cgxRoutingNotificationGroup = cgxRoutingNotificationGroup.setStatus('current')
cgxWanNotificationGroup = NotificationGroup((1, 3, 6, 1, 4, 1, 50114, 10, 1, 2, 2, 104)).setObjects(("CGX-EVENTS-MIB", "cgxPrivateWanDegraded"), ("CGX-EVENTS-MIB", "cgxPrivateWanDegradedClear"), ("CGX-EVENTS-MIB", "cgxPublicWanDown"), ("CGX-EVENTS-MIB", "cgxPublicWanUp"), ("CGX-EVENTS-MIB", "cgxPrivateWanDown"), ("CGX-EVENTS-MIB", "cgxPrivateWanUp"), ("CGX-EVENTS-MIB", "cgxPrivateWanUnreachable"), ("CGX-EVENTS-MIB", "cgxPrivateWanUnreachableClear"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    cgxWanNotificationGroup = cgxWanNotificationGroup.setStatus('current')
cgxProcessNotificationGroup = NotificationGroup((1, 3, 6, 1, 4, 1, 50114, 10, 1, 2, 2, 105)).setObjects(("CGX-EVENTS-MIB", "cgxProcessStop"), ("CGX-EVENTS-MIB", "cgxProcessStopClear"), ("CGX-EVENTS-MIB", "cgxProcessRestart"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    cgxProcessNotificationGroup = cgxProcessNotificationGroup.setStatus('current')
mibBuilder.exportSymbols("CGX-EVENTS-MIB", PYSNMP_MODULE_ID=cgxEventsMIB, cgxElementId=cgxElementId, cgxElementName=cgxElementName, cgxElementObjectGroup=cgxElementObjectGroup, cgxElementObjects=cgxElementObjects, cgxElementRemoteId=cgxElementRemoteId, cgxElementRemoteName=cgxElementRemoteName, cgxEventsCompliances=cgxEventsCompliances, cgxEventsConformance=cgxEventsConformance, cgxEventsGroups=cgxEventsGroups, cgxEventsMIB=cgxEventsMIB, cgxEventsMIBCompliance=cgxEventsMIBCompliance, cgxEventsNotifications=cgxEventsNotifications, cgxEventsObjectStats=cgxEventsObjectStats, cgxEventsObjects=cgxEventsObjects, cgxPrivateWanDegraded=cgxPrivateWanDegraded, cgxPrivateWanDegradedClear=cgxPrivateWanDegradedClear, cgxPrivateWanDown=cgxPrivateWanDown, cgxPrivateWanUnreachable=cgxPrivateWanUnreachable, cgxPrivateWanUnreachableClear=cgxPrivateWanUnreachableClear, cgxPrivateWanUp=cgxPrivateWanUp, cgxProcessId=cgxProcessId, cgxProcessName=cgxProcessName, cgxProcessNotificationGroup=cgxProcessNotificationGroup, cgxProcessObjectGroup=cgxProcessObjectGroup, cgxProcessObjects=cgxProcessObjects, cgxProcessRestart=cgxProcessRestart, cgxProcessStop=cgxProcessStop, cgxProcessStopClear=cgxProcessStopClear, cgxPublicWanDown=cgxPublicWanDown, cgxPublicWanUp=cgxPublicWanUp, cgxRoutePeerDown=cgxRoutePeerDown, cgxRoutePeerId=cgxRoutePeerId, cgxRoutePeerIp=cgxRoutePeerIp, cgxRoutePeerName=cgxRoutePeerName, cgxRoutePeerType=cgxRoutePeerType, cgxRoutePeerUp=cgxRoutePeerUp, cgxRoutingNotificationGroup=cgxRoutingNotificationGroup, cgxRoutingObjectGroup=cgxRoutingObjectGroup, cgxRoutingObjects=cgxRoutingObjects, cgxSiteId=cgxSiteId, cgxSiteName=cgxSiteName, cgxSiteObjectGroup=cgxSiteObjectGroup, cgxSiteObjects=cgxSiteObjects, cgxSiteRemoteId=cgxSiteRemoteId, cgxSiteRemoteName=cgxSiteRemoteName, cgxSiteWanInterfaceId=cgxSiteWanInterfaceId, cgxSiteWanInterfaceName=cgxSiteWanInterfaceName, cgxVpnBfdDown=cgxVpnBfdDown, cgxVpnBfdUp=cgxVpnBfdUp, cgxVpnLinkDown=cgxVpnLinkDown, cgxVpnLinkId=cgxVpnLinkId, cgxVpnLinkUp=cgxVpnLinkUp, cgxVpnNotificationGroup=cgxVpnNotificationGroup, cgxVpnObjectGroup=cgxVpnObjectGroup, cgxVpnObjects=cgxVpnObjects, cgxVpnPeerUnreachable=cgxVpnPeerUnreachable, cgxVpnPeerUnreachableClear=cgxVpnPeerUnreachableClear, cgxWanNetworkId=cgxWanNetworkId, cgxWanNetworkName=cgxWanNetworkName, cgxWanNetworkPrefix=cgxWanNetworkPrefix, cgxWanNetworkRemoteId=cgxWanNetworkRemoteId, cgxWanNetworkRemoteName=cgxWanNetworkRemoteName, cgxWanNetworkRemoteType=cgxWanNetworkRemoteType, cgxWanNetworkType=cgxWanNetworkType, cgxWanNotificationGroup=cgxWanNotificationGroup, cgxWanObjectGroup=cgxWanObjectGroup, cgxWanObjects=cgxWanObjects)
