#
# PySNMP MIB module CISCO-VIRTUAL-NIC-MIB (http://snmplabs.com/pysmi)
# ASN.1 source CISCO-VIRTUAL-NIC-MIB
# Source digest sha256:3a4eaeeddb1d483568907c183842ffd81683ba587a2933f6a7d7bb9f843f7654
# Produced by pysmi-2.3.0
#
Integer, ObjectIdentifier, OctetString = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
NamedValues, = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
ciscoMgmt, = mibBuilder.importSymbols("CISCO-SMI", "ciscoMgmt")
InterfaceIndex, = mibBuilder.importSymbols("IF-MIB", "InterfaceIndex")
InetAddress, InetAddressType = mibBuilder.importSymbols("INET-ADDRESS-MIB", "InetAddress", "InetAddressType")
SnmpAdminString, = mibBuilder.importSymbols("SNMP-FRAMEWORK-MIB", "SnmpAdminString")
ModuleCompliance, NotificationGroup, ObjectGroup = mibBuilder.importSymbols("SNMPv2-CONF", "ModuleCompliance", "NotificationGroup", "ObjectGroup")
Bits, Counter32, Counter64, Gauge32, Integer32, IpAddress, ModuleIdentity, MibIdentifier, NotificationType, ObjectIdentity, MibScalar, MibTable, MibTableRow, MibTableColumn, TimeTicks, Unsigned32, iso = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Counter32", "Counter64", "Gauge32", "Integer32", "IpAddress", "ModuleIdentity", "MibIdentifier", "NotificationType", "ObjectIdentity", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "TimeTicks", "Unsigned32", "iso")
DisplayString, MacAddress, TextualConvention = mibBuilder.importSymbols("SNMPv2-TC", "DisplayString", "MacAddress", "TextualConvention")
ciscoVirtualNicMIB = ModuleIdentity((1, 3, 6, 1, 4, 1, 9, 9, 710))
ciscoVirtualNicMIB.setRevisions(('2009-10-26 00:00',))
if mibBuilder.loadTexts: ciscoVirtualNicMIB.setLastUpdated('2009-10-26 00:00')
if mibBuilder.loadTexts: ciscoVirtualNicMIB.setOrganization('Cisco Systems, Inc.')
ciscoVirtualNicMIBNotifs = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 710, 0))
ciscoVirtualNicMIBObjects = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 710, 1))
ciscoVirtualNicMIBConformance = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 710, 2))
cvnInterfaceObjects = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 710, 1, 1))
cvnConnecteeObjects = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 710, 1, 2))
cvnVethIfTable = MibTable((1, 3, 6, 1, 4, 1, 9, 9, 710, 1, 1, 1), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cvnVethIfTable.setStatus('current')
cvnVethIfEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 9, 710, 1, 1, 1, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "CISCO-VIRTUAL-NIC-MIB", "cvnVethInterface"))
if mibBuilder.loadTexts: cvnVethIfEntry.setStatus('current')
cvnVethInterface = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 710, 1, 1, 1, 1, 1), InterfaceIndex()).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cvnVethInterface.setStatus('current')
cvnVethAdapter = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 710, 1, 1, 1, 1, 2), SnmpAdminString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cvnVethAdapter.setStatus('current')
cvnVethOwner = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 710, 1, 1, 1, 1, 3), SnmpAdminString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cvnVethOwner.setStatus('current')
cvnVethHostID = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 710, 1, 1, 1, 1, 4), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cvnVethHostID.setStatus('current')
cvnVethHostAddrType = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 710, 1, 1, 1, 1, 5), InetAddressType()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cvnVethHostAddrType.setStatus('current')
cvnVethHostAddr = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 710, 1, 1, 1, 1, 6), InetAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cvnVethHostAddr.setStatus('current')
cvnVethPortProfileUsed = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 710, 1, 1, 1, 1, 7), SnmpAdminString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cvnVethPortProfileUsed.setStatus('current')
cvnVethIfProfileAlias = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 710, 1, 1, 1, 1, 8), SnmpAdminString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cvnVethIfProfileAlias.setStatus('current')
cvnVethIfAdditionalState = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 710, 1, 1, 1, 1, 9), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3, 4, 5))).clone(namedValues=NamedValues(("none", 1), ("participating", 2), ("suspended", 3), ("errDisabled", 4), ("nonParticipating", 5)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cvnVethIfAdditionalState.setStatus('current')
cvnVethStateReason = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 710, 1, 1, 1, 1, 10), SnmpAdminString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cvnVethStateReason.setStatus('current')
cvnPinningTable = MibTable((1, 3, 6, 1, 4, 1, 9, 9, 710, 1, 1, 2), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cvnPinningTable.setStatus('current')
cvnPinningEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 9, 710, 1, 1, 2, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "CISCO-VIRTUAL-NIC-MIB", "cvnVethInterface"))
if mibBuilder.loadTexts: cvnPinningEntry.setStatus('current')
cvnPinnedSubGrpId = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 710, 1, 1, 2, 1, 1), Integer32().subtype(subtypeSpec=ValueRangeConstraint(-1, 2147483647))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: cvnPinnedSubGrpId.setStatus('current')
cvnConnecteeTable = MibTable((1, 3, 6, 1, 4, 1, 9, 9, 710, 1, 2, 1), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cvnConnecteeTable.setStatus('current')
cvnConnecteeEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 9, 710, 1, 2, 1, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "CISCO-VIRTUAL-NIC-MIB", "cvnVethInterface"))
if mibBuilder.loadTexts: cvnConnecteeEntry.setStatus('current')
cvnConnecteeAttachType = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 710, 1, 2, 1, 1, 1), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3))).clone(namedValues=NamedValues(("none", 1), ("vem", 2), ("niv", 3)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cvnConnecteeAttachType.setStatus('current')
cvnDVSPort = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 710, 1, 2, 1, 1, 2), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cvnDVSPort.setStatus('current')
cvnConnecteeName = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 710, 1, 2, 1, 1, 3), SnmpAdminString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cvnConnecteeName.setStatus('current')
cvnConnecteeUuid = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 710, 1, 2, 1, 1, 4), SnmpAdminString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cvnConnecteeUuid.setStatus('current')
cvnConnecteeType = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 710, 1, 2, 1, 1, 5), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3))).clone(namedValues=NamedValues(("unknown", 1), ("vmwareVm", 2), ("vmwareHost", 3)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cvnConnecteeType.setStatus('current')
cvnConnecteeMac = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 710, 1, 2, 1, 1, 6), MacAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cvnConnecteeMac.setStatus('current')
cvnConnecteeDeviceName = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 710, 1, 2, 1, 1, 7), SnmpAdminString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cvnConnecteeDeviceName.setStatus('current')
cvnConnecteeDeviceType = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 710, 1, 2, 1, 1, 8), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3, 4, 5))).clone(namedValues=NamedValues(("unknown", 1), ("pnic", 2), ("vnic", 3), ("vswif", 4), ("vmknic", 5)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cvnConnecteeDeviceType.setStatus('current')
ciscoVirtualNicMIBCompliances = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 710, 2, 1))
ciscoVirtualNicMIBGroups = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 710, 2, 2))
virtualNicMIBCompliance = ModuleCompliance((1, 3, 6, 1, 4, 1, 9, 9, 710, 2, 1, 1)).setObjects(("CISCO-VIRTUAL-NIC-MIB", "cvnVethGroup"), ("CISCO-VIRTUAL-NIC-MIB", "cvnPinningGroup"), ("CISCO-VIRTUAL-NIC-MIB", "cvnConnecteeGroup"))

if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    virtualNicMIBCompliance = virtualNicMIBCompliance.setStatus('current')
cvnVethGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 9, 9, 710, 2, 2, 1)).setObjects(("CISCO-VIRTUAL-NIC-MIB", "cvnVethAdapter"), ("CISCO-VIRTUAL-NIC-MIB", "cvnVethOwner"), ("CISCO-VIRTUAL-NIC-MIB", "cvnVethHostID"), ("CISCO-VIRTUAL-NIC-MIB", "cvnVethHostAddrType"), ("CISCO-VIRTUAL-NIC-MIB", "cvnVethHostAddr"), ("CISCO-VIRTUAL-NIC-MIB", "cvnVethPortProfileUsed"), ("CISCO-VIRTUAL-NIC-MIB", "cvnVethIfProfileAlias"), ("CISCO-VIRTUAL-NIC-MIB", "cvnVethIfAdditionalState"), ("CISCO-VIRTUAL-NIC-MIB", "cvnVethStateReason"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    cvnVethGroup = cvnVethGroup.setStatus('current')
cvnPinningGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 9, 9, 710, 2, 2, 2)).setObjects(("CISCO-VIRTUAL-NIC-MIB", "cvnPinnedSubGrpId"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    cvnPinningGroup = cvnPinningGroup.setStatus('current')
cvnConnecteeGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 9, 9, 710, 2, 2, 3)).setObjects(("CISCO-VIRTUAL-NIC-MIB", "cvnConnecteeAttachType"), ("CISCO-VIRTUAL-NIC-MIB", "cvnDVSPort"), ("CISCO-VIRTUAL-NIC-MIB", "cvnConnecteeName"), ("CISCO-VIRTUAL-NIC-MIB", "cvnConnecteeUuid"), ("CISCO-VIRTUAL-NIC-MIB", "cvnConnecteeType"), ("CISCO-VIRTUAL-NIC-MIB", "cvnConnecteeMac"), ("CISCO-VIRTUAL-NIC-MIB", "cvnConnecteeDeviceName"), ("CISCO-VIRTUAL-NIC-MIB", "cvnConnecteeDeviceType"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    cvnConnecteeGroup = cvnConnecteeGroup.setStatus('current')
mibBuilder.exportSymbols("CISCO-VIRTUAL-NIC-MIB", PYSNMP_MODULE_ID=ciscoVirtualNicMIB, ciscoVirtualNicMIB=ciscoVirtualNicMIB, ciscoVirtualNicMIBCompliances=ciscoVirtualNicMIBCompliances, ciscoVirtualNicMIBConformance=ciscoVirtualNicMIBConformance, ciscoVirtualNicMIBGroups=ciscoVirtualNicMIBGroups, ciscoVirtualNicMIBNotifs=ciscoVirtualNicMIBNotifs, ciscoVirtualNicMIBObjects=ciscoVirtualNicMIBObjects, cvnConnecteeAttachType=cvnConnecteeAttachType, cvnConnecteeDeviceName=cvnConnecteeDeviceName, cvnConnecteeDeviceType=cvnConnecteeDeviceType, cvnConnecteeEntry=cvnConnecteeEntry, cvnConnecteeGroup=cvnConnecteeGroup, cvnConnecteeMac=cvnConnecteeMac, cvnConnecteeName=cvnConnecteeName, cvnConnecteeObjects=cvnConnecteeObjects, cvnConnecteeTable=cvnConnecteeTable, cvnConnecteeType=cvnConnecteeType, cvnConnecteeUuid=cvnConnecteeUuid, cvnDVSPort=cvnDVSPort, cvnInterfaceObjects=cvnInterfaceObjects, cvnPinnedSubGrpId=cvnPinnedSubGrpId, cvnPinningEntry=cvnPinningEntry, cvnPinningGroup=cvnPinningGroup, cvnPinningTable=cvnPinningTable, cvnVethAdapter=cvnVethAdapter, cvnVethGroup=cvnVethGroup, cvnVethHostAddr=cvnVethHostAddr, cvnVethHostAddrType=cvnVethHostAddrType, cvnVethHostID=cvnVethHostID, cvnVethIfAdditionalState=cvnVethIfAdditionalState, cvnVethIfEntry=cvnVethIfEntry, cvnVethIfProfileAlias=cvnVethIfProfileAlias, cvnVethIfTable=cvnVethIfTable, cvnVethInterface=cvnVethInterface, cvnVethOwner=cvnVethOwner, cvnVethPortProfileUsed=cvnVethPortProfileUsed, cvnVethStateReason=cvnVethStateReason, virtualNicMIBCompliance=virtualNicMIBCompliance)
