#
# PySNMP MIB module CISCOSB-DHCPv6-RELAY (http://snmplabs.com/pysmi)
# ASN.1 source CISCOSB-DHCPv6-RELAY
# Source digest sha256:a3e8f73cf8f0c4dd5c5674fc798d965c73664b604d17f7dfa4ff596bb9c21547
# Produced by pysmi-2.3.0
#
Integer, ObjectIdentifier, OctetString = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
NamedValues, = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
rlDhcpv6Relay, = mibBuilder.importSymbols("CISCOSB-DHCPv6", "rlDhcpv6Relay")
InetAddress, InetAddressIPv6, InetAddressType = mibBuilder.importSymbols("INET-ADDRESS-MIB", "InetAddress", "InetAddressIPv6", "InetAddressType")
ModuleCompliance, NotificationGroup = mibBuilder.importSymbols("SNMPv2-CONF", "ModuleCompliance", "NotificationGroup")
Bits, Counter32, Counter64, Gauge32, Integer32, IpAddress, ModuleIdentity, MibIdentifier, NotificationType, ObjectIdentity, MibScalar, MibTable, MibTableRow, MibTableColumn, TimeTicks, Unsigned32, iso = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Counter32", "Counter64", "Gauge32", "Integer32", "IpAddress", "ModuleIdentity", "MibIdentifier", "NotificationType", "ObjectIdentity", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "TimeTicks", "Unsigned32", "iso")
DisplayString, MacAddress, RowStatus, TextualConvention, TruthValue = mibBuilder.importSymbols("SNMPv2-TC", "DisplayString", "MacAddress", "RowStatus", "TextualConvention", "TruthValue")
rlDhcpv6RelayInterfaceListTable = MibTable((1, 3, 6, 1, 4, 1, 9, 6, 1, 101, 214, 3, 1), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: rlDhcpv6RelayInterfaceListTable.setStatus('current')
rlDhcpv6RelayInterfaceListEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 6, 1, 101, 214, 3, 1, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "CISCOSB-DHCPv6-RELAY", "rlDhcpv6RelayInterfaceListIfIndex"))
if mibBuilder.loadTexts: rlDhcpv6RelayInterfaceListEntry.setStatus('current')
rlDhcpv6RelayInterfaceListIfIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 6, 1, 101, 214, 3, 1, 1, 1), Unsigned32()).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: rlDhcpv6RelayInterfaceListIfIndex.setStatus('current')
rlDhcpv6RelayInterfaceListRowStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 6, 1, 101, 214, 3, 1, 1, 2), RowStatus()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: rlDhcpv6RelayInterfaceListRowStatus.setStatus('current')
rlDhcpv6RelayDestinationsGlobalTable = MibTable((1, 3, 6, 1, 4, 1, 9, 6, 1, 101, 214, 3, 2), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: rlDhcpv6RelayDestinationsGlobalTable.setStatus('current')
rlDhcpv6RelayDestinationsGlobalEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 6, 1, 101, 214, 3, 2, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "CISCOSB-DHCPv6-RELAY", "rlDhcpv6RelayDestinationsGlobalIpv6AddrType"), (0, "CISCOSB-DHCPv6-RELAY", "rlDhcpv6RelayDestinationsGlobalIpv6Addr"), (0, "CISCOSB-DHCPv6-RELAY", "rlDhcpv6RelayDestinationsGlobalOutputInterface"))
if mibBuilder.loadTexts: rlDhcpv6RelayDestinationsGlobalEntry.setStatus('current')
rlDhcpv6RelayDestinationsGlobalIpv6AddrType = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 6, 1, 101, 214, 3, 2, 1, 1), InetAddressType()).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: rlDhcpv6RelayDestinationsGlobalIpv6AddrType.setStatus('current')
rlDhcpv6RelayDestinationsGlobalIpv6Addr = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 6, 1, 101, 214, 3, 2, 1, 2), InetAddress()).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: rlDhcpv6RelayDestinationsGlobalIpv6Addr.setStatus('current')
rlDhcpv6RelayDestinationsGlobalOutputInterface = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 6, 1, 101, 214, 3, 2, 1, 3), Unsigned32()).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: rlDhcpv6RelayDestinationsGlobalOutputInterface.setStatus('current')
rlDhcpv6RelayDestinationsGlobalRowStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 6, 1, 101, 214, 3, 2, 1, 4), RowStatus()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: rlDhcpv6RelayDestinationsGlobalRowStatus.setStatus('current')
rlDhcpv6RelayInterfaceDestinationsTable = MibTable((1, 3, 6, 1, 4, 1, 9, 6, 1, 101, 214, 3, 3), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: rlDhcpv6RelayInterfaceDestinationsTable.setStatus('current')
rlDhcpv6RelayInterfaceDestinationsEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 6, 1, 101, 214, 3, 3, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "CISCOSB-DHCPv6-RELAY", "rlDhcpv6RelayInterfaceDestinationsIfindex"), (0, "CISCOSB-DHCPv6-RELAY", "rlDhcpv6RelayInterfaceDestinationsIpv6AddrType"), (0, "CISCOSB-DHCPv6-RELAY", "rlDhcpv6RelayInterfaceDestinationsIpv6Addr"), (0, "CISCOSB-DHCPv6-RELAY", "rlDhcpv6RelayInterfaceDestinationsOutputInterface"))
if mibBuilder.loadTexts: rlDhcpv6RelayInterfaceDestinationsEntry.setStatus('current')
rlDhcpv6RelayInterfaceDestinationsIfindex = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 6, 1, 101, 214, 3, 3, 1, 1), Unsigned32()).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: rlDhcpv6RelayInterfaceDestinationsIfindex.setStatus('current')
rlDhcpv6RelayInterfaceDestinationsIpv6AddrType = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 6, 1, 101, 214, 3, 3, 1, 2), InetAddressType()).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: rlDhcpv6RelayInterfaceDestinationsIpv6AddrType.setStatus('current')
rlDhcpv6RelayInterfaceDestinationsIpv6Addr = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 6, 1, 101, 214, 3, 3, 1, 3), InetAddress()).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: rlDhcpv6RelayInterfaceDestinationsIpv6Addr.setStatus('current')
rlDhcpv6RelayInterfaceDestinationsOutputInterface = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 6, 1, 101, 214, 3, 3, 1, 4), Unsigned32()).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: rlDhcpv6RelayInterfaceDestinationsOutputInterface.setStatus('current')
rlDhcpv6RelayInterfaceDestinationsRowStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 6, 1, 101, 214, 3, 3, 1, 5), RowStatus()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: rlDhcpv6RelayInterfaceDestinationsRowStatus.setStatus('current')
mibBuilder.exportSymbols("CISCOSB-DHCPv6-RELAY", rlDhcpv6RelayDestinationsGlobalEntry=rlDhcpv6RelayDestinationsGlobalEntry, rlDhcpv6RelayDestinationsGlobalIpv6Addr=rlDhcpv6RelayDestinationsGlobalIpv6Addr, rlDhcpv6RelayDestinationsGlobalIpv6AddrType=rlDhcpv6RelayDestinationsGlobalIpv6AddrType, rlDhcpv6RelayDestinationsGlobalOutputInterface=rlDhcpv6RelayDestinationsGlobalOutputInterface, rlDhcpv6RelayDestinationsGlobalRowStatus=rlDhcpv6RelayDestinationsGlobalRowStatus, rlDhcpv6RelayDestinationsGlobalTable=rlDhcpv6RelayDestinationsGlobalTable, rlDhcpv6RelayInterfaceDestinationsEntry=rlDhcpv6RelayInterfaceDestinationsEntry, rlDhcpv6RelayInterfaceDestinationsIfindex=rlDhcpv6RelayInterfaceDestinationsIfindex, rlDhcpv6RelayInterfaceDestinationsIpv6Addr=rlDhcpv6RelayInterfaceDestinationsIpv6Addr, rlDhcpv6RelayInterfaceDestinationsIpv6AddrType=rlDhcpv6RelayInterfaceDestinationsIpv6AddrType, rlDhcpv6RelayInterfaceDestinationsOutputInterface=rlDhcpv6RelayInterfaceDestinationsOutputInterface, rlDhcpv6RelayInterfaceDestinationsRowStatus=rlDhcpv6RelayInterfaceDestinationsRowStatus, rlDhcpv6RelayInterfaceDestinationsTable=rlDhcpv6RelayInterfaceDestinationsTable, rlDhcpv6RelayInterfaceListEntry=rlDhcpv6RelayInterfaceListEntry, rlDhcpv6RelayInterfaceListIfIndex=rlDhcpv6RelayInterfaceListIfIndex, rlDhcpv6RelayInterfaceListRowStatus=rlDhcpv6RelayInterfaceListRowStatus, rlDhcpv6RelayInterfaceListTable=rlDhcpv6RelayInterfaceListTable)
