#
# PySNMP MIB module CISCO-FLEX-LINKS-MIB (http://snmplabs.com/pysmi)
# ASN.1 source CISCO-FLEX-LINKS-MIB
# Source digest sha256:26fd5c9c51d34a0033cdc8a63d3d78cdf19822d85cccc428d0e93064c787ee5e
# Produced by pysmi-2.3.0
#
Integer, ObjectIdentifier, OctetString = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
NamedValues, = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
ciscoMgmt, = mibBuilder.importSymbols("CISCO-SMI", "ciscoMgmt")
Cisco2KVlanList, = mibBuilder.importSymbols("CISCO-TC", "Cisco2KVlanList")
InterfaceIndex, InterfaceIndexOrZero = mibBuilder.importSymbols("IF-MIB", "InterfaceIndex", "InterfaceIndexOrZero")
VlanIdOrNone, = mibBuilder.importSymbols("Q-BRIDGE-MIB", "VlanIdOrNone")
ModuleCompliance, NotificationGroup, ObjectGroup = mibBuilder.importSymbols("SNMPv2-CONF", "ModuleCompliance", "NotificationGroup", "ObjectGroup")
Bits, Counter32, Counter64, Gauge32, Integer32, IpAddress, ModuleIdentity, MibIdentifier, NotificationType, ObjectIdentity, MibScalar, MibTable, MibTableRow, MibTableColumn, TimeTicks, Unsigned32, iso = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Counter32", "Counter64", "Gauge32", "Integer32", "IpAddress", "ModuleIdentity", "MibIdentifier", "NotificationType", "ObjectIdentity", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "TimeTicks", "Unsigned32", "iso")
DisplayString, RowStatus, StorageType, TextualConvention, TruthValue = mibBuilder.importSymbols("SNMPv2-TC", "DisplayString", "RowStatus", "StorageType", "TextualConvention", "TruthValue")
ciscoFlexLinksMIB = ModuleIdentity((1, 3, 6, 1, 4, 1, 9, 9, 471))
ciscoFlexLinksMIB.setRevisions(('2010-02-04 00:00', '2005-04-25 00:00',))
if mibBuilder.loadTexts: ciscoFlexLinksMIB.setLastUpdated('2010-02-04 00:00')
if mibBuilder.loadTexts: ciscoFlexLinksMIB.setOrganization('Cisco Systems, Inc.')
ciscoFlexLinksMIBNotifs = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 471, 0))
ciscoFlexLinksMIBObjects = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 471, 1))
ciscoFlexLinksMIBConformance = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 471, 2))
cflConfig = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 471, 1, 1))
cflStatus = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 471, 1, 2))
cflIfConfigTable = MibTable((1, 3, 6, 1, 4, 1, 9, 9, 471, 1, 1, 1), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cflIfConfigTable.setStatus('current')
cflIfConfigEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 9, 471, 1, 1, 1, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "CISCO-FLEX-LINKS-MIB", "cflIfConfigPrimary"))
if mibBuilder.loadTexts: cflIfConfigEntry.setStatus('current')
cflIfConfigPrimary = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 471, 1, 1, 1, 1, 1), InterfaceIndex()).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cflIfConfigPrimary.setStatus('current')
cflIfConfigBackUp = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 471, 1, 1, 1, 1, 2), InterfaceIndexOrZero()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: cflIfConfigBackUp.setStatus('current')
cflIfConfigStorageType = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 471, 1, 1, 1, 1, 3), StorageType().clone('nonVolatile')).setMaxAccess("readcreate")
if mibBuilder.loadTexts: cflIfConfigStorageType.setStatus('current')
cflIfConfigStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 471, 1, 1, 1, 1, 4), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: cflIfConfigStatus.setStatus('current')
cflEnableStatusChangeNotif = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 471, 1, 1, 2), TruthValue()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: cflEnableStatusChangeNotif.setStatus('current')
cflIfConfigExtTable = MibTable((1, 3, 6, 1, 4, 1, 9, 9, 471, 1, 1, 3), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cflIfConfigExtTable.setStatus('current')
cflIfConfigExtEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 9, 471, 1, 1, 3, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "CISCO-FLEX-LINKS-MIB", "cflIfConfigPrimary"))
if mibBuilder.loadTexts: cflIfConfigExtEntry.setStatus('current')
cflIfConfigMmuPrimaryVlan = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 471, 1, 1, 3, 1, 1), VlanIdOrNone()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: cflIfConfigMmuPrimaryVlan.setStatus('current')
cflIfConfigPreemptionMode = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 471, 1, 1, 3, 1, 2), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3))).clone(namedValues=NamedValues(("off", 1), ("forced", 2), ("bandwidth", 3)))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: cflIfConfigPreemptionMode.setStatus('current')
cflIfConfigPreemptionDelay = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 471, 1, 1, 3, 1, 3), Unsigned32()).setUnits('seconds').setMaxAccess("readwrite")
if mibBuilder.loadTexts: cflIfConfigPreemptionDelay.setStatus('current')
cflIfConfigPrefer2kVlan = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 471, 1, 1, 3, 1, 4), Cisco2KVlanList()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: cflIfConfigPrefer2kVlan.setStatus('current')
cflIfConfigPrefer4kVlan = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 471, 1, 1, 3, 1, 5), Cisco2KVlanList()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: cflIfConfigPrefer4kVlan.setStatus('current')
cflIfStatusTable = MibTable((1, 3, 6, 1, 4, 1, 9, 9, 471, 1, 2, 1), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cflIfStatusTable.setStatus('current')
cflIfStatusEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 9, 471, 1, 2, 1, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "CISCO-FLEX-LINKS-MIB", "cflIfIndex"))
if mibBuilder.loadTexts: cflIfStatusEntry.setStatus('current')
cflIfIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 471, 1, 2, 1, 1, 1), InterfaceIndex()).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cflIfIndex.setStatus('current')
cflIfStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 471, 1, 2, 1, 1, 2), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3, 4, 5, 6, 7, 8, 9))).clone(namedValues=NamedValues(("forwarding", 1), ("blocking", 2), ("down", 3), ("waitingToSync", 4), ("waitingForPeerStrate", 5), ("unknown", 6), ("vlbAll", 7), ("vlbConfig", 8), ("vlbPreempt", 9)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cflIfStatus.setStatus('current')
cflIfStatusChangeNotif = NotificationType((1, 3, 6, 1, 4, 1, 9, 9, 471, 0, 1)).setObjects(("CISCO-FLEX-LINKS-MIB", "cflIfStatus"))
if mibBuilder.loadTexts: cflIfStatusChangeNotif.setStatus('current')
ciscoFlexLinksMIBCompliances = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 471, 2, 1))
ciscoFlexLinksMIBGroups = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 471, 2, 2))
ciscoFlexLinksMIBCompliance = ModuleCompliance((1, 3, 6, 1, 4, 1, 9, 9, 471, 2, 1, 1)).setObjects(("CISCO-FLEX-LINKS-MIB", "ciscoFlexLinksIfConfigGroup"), ("CISCO-FLEX-LINKS-MIB", "ciscoFlexLinksIfStatusGroup"), ("CISCO-FLEX-LINKS-MIB", "ciscoFlexLinksEnableNotifGroup"), ("CISCO-FLEX-LINKS-MIB", "ciscoFlexLinksNotifGroup"))

if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    ciscoFlexLinksMIBCompliance = ciscoFlexLinksMIBCompliance.setStatus('deprecated')
ciscoFlexLinksMIBCompliance2 = ModuleCompliance((1, 3, 6, 1, 4, 1, 9, 9, 471, 2, 1, 2)).setObjects(("CISCO-FLEX-LINKS-MIB", "ciscoFlexLinksIfConfigGroup"), ("CISCO-FLEX-LINKS-MIB", "ciscoFlexLinksIfStatusGroup"), ("CISCO-FLEX-LINKS-MIB", "ciscoFlexLinksEnableNotifGroup"), ("CISCO-FLEX-LINKS-MIB", "ciscoFlexLinksNotifGroup"), ("CISCO-FLEX-LINKS-MIB", "ciscoFlexLinksMmuPrimaryVlanGroup"), ("CISCO-FLEX-LINKS-MIB", "ciscoFlexLinksPreemptionGroup"), ("CISCO-FLEX-LINKS-MIB", "ciscoFlexLinksPreferVlanGroup"))

if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    ciscoFlexLinksMIBCompliance2 = ciscoFlexLinksMIBCompliance2.setStatus('current')
ciscoFlexLinksIfConfigGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 9, 9, 471, 2, 2, 1)).setObjects(("CISCO-FLEX-LINKS-MIB", "cflIfConfigBackUp"), ("CISCO-FLEX-LINKS-MIB", "cflIfConfigStorageType"), ("CISCO-FLEX-LINKS-MIB", "cflIfConfigStatus"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    ciscoFlexLinksIfConfigGroup = ciscoFlexLinksIfConfigGroup.setStatus('current')
ciscoFlexLinksIfStatusGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 9, 9, 471, 2, 2, 2)).setObjects(("CISCO-FLEX-LINKS-MIB", "cflIfStatus"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    ciscoFlexLinksIfStatusGroup = ciscoFlexLinksIfStatusGroup.setStatus('current')
ciscoFlexLinksEnableNotifGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 9, 9, 471, 2, 2, 3)).setObjects(("CISCO-FLEX-LINKS-MIB", "cflEnableStatusChangeNotif"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    ciscoFlexLinksEnableNotifGroup = ciscoFlexLinksEnableNotifGroup.setStatus('current')
ciscoFlexLinksNotifGroup = NotificationGroup((1, 3, 6, 1, 4, 1, 9, 9, 471, 2, 2, 4)).setObjects(("CISCO-FLEX-LINKS-MIB", "cflIfStatusChangeNotif"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    ciscoFlexLinksNotifGroup = ciscoFlexLinksNotifGroup.setStatus('current')
ciscoFlexLinksMmuPrimaryVlanGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 9, 9, 471, 2, 2, 5)).setObjects(("CISCO-FLEX-LINKS-MIB", "cflIfConfigMmuPrimaryVlan"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    ciscoFlexLinksMmuPrimaryVlanGroup = ciscoFlexLinksMmuPrimaryVlanGroup.setStatus('current')
ciscoFlexLinksPreemptionGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 9, 9, 471, 2, 2, 6)).setObjects(("CISCO-FLEX-LINKS-MIB", "cflIfConfigPreemptionMode"), ("CISCO-FLEX-LINKS-MIB", "cflIfConfigPreemptionDelay"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    ciscoFlexLinksPreemptionGroup = ciscoFlexLinksPreemptionGroup.setStatus('current')
ciscoFlexLinksPreferVlanGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 9, 9, 471, 2, 2, 7)).setObjects(("CISCO-FLEX-LINKS-MIB", "cflIfConfigPrefer2kVlan"), ("CISCO-FLEX-LINKS-MIB", "cflIfConfigPrefer4kVlan"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    ciscoFlexLinksPreferVlanGroup = ciscoFlexLinksPreferVlanGroup.setStatus('current')
mibBuilder.exportSymbols("CISCO-FLEX-LINKS-MIB", PYSNMP_MODULE_ID=ciscoFlexLinksMIB, cflConfig=cflConfig, cflEnableStatusChangeNotif=cflEnableStatusChangeNotif, cflIfConfigBackUp=cflIfConfigBackUp, cflIfConfigEntry=cflIfConfigEntry, cflIfConfigExtEntry=cflIfConfigExtEntry, cflIfConfigExtTable=cflIfConfigExtTable, cflIfConfigMmuPrimaryVlan=cflIfConfigMmuPrimaryVlan, cflIfConfigPreemptionDelay=cflIfConfigPreemptionDelay, cflIfConfigPreemptionMode=cflIfConfigPreemptionMode, cflIfConfigPrefer2kVlan=cflIfConfigPrefer2kVlan, cflIfConfigPrefer4kVlan=cflIfConfigPrefer4kVlan, cflIfConfigPrimary=cflIfConfigPrimary, cflIfConfigStatus=cflIfConfigStatus, cflIfConfigStorageType=cflIfConfigStorageType, cflIfConfigTable=cflIfConfigTable, cflIfIndex=cflIfIndex, cflIfStatus=cflIfStatus, cflIfStatusChangeNotif=cflIfStatusChangeNotif, cflIfStatusEntry=cflIfStatusEntry, cflIfStatusTable=cflIfStatusTable, cflStatus=cflStatus, ciscoFlexLinksEnableNotifGroup=ciscoFlexLinksEnableNotifGroup, ciscoFlexLinksIfConfigGroup=ciscoFlexLinksIfConfigGroup, ciscoFlexLinksIfStatusGroup=ciscoFlexLinksIfStatusGroup, ciscoFlexLinksMIB=ciscoFlexLinksMIB, ciscoFlexLinksMIBCompliance2=ciscoFlexLinksMIBCompliance2, ciscoFlexLinksMIBCompliance=ciscoFlexLinksMIBCompliance, ciscoFlexLinksMIBCompliances=ciscoFlexLinksMIBCompliances, ciscoFlexLinksMIBConformance=ciscoFlexLinksMIBConformance, ciscoFlexLinksMIBGroups=ciscoFlexLinksMIBGroups, ciscoFlexLinksMIBNotifs=ciscoFlexLinksMIBNotifs, ciscoFlexLinksMIBObjects=ciscoFlexLinksMIBObjects, ciscoFlexLinksMmuPrimaryVlanGroup=ciscoFlexLinksMmuPrimaryVlanGroup, ciscoFlexLinksNotifGroup=ciscoFlexLinksNotifGroup, ciscoFlexLinksPreemptionGroup=ciscoFlexLinksPreemptionGroup, ciscoFlexLinksPreferVlanGroup=ciscoFlexLinksPreferVlanGroup)
