#
# PySNMP MIB module CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB (http://snmplabs.com/pysmi)
# ASN.1 source CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB
# Source digest sha256:8ad49850f604d91c26b3bd582053a614c8bb7176691093fdc8b270e1253a1206
# Produced by pysmi-2.3.0
#
Integer, ObjectIdentifier, OctetString = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
NamedValues, = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
CiscoLwappDot11ClientAuthMethod, CiscoLwappDot11ClientCredentialType, CiscoLwappDot11ClientEAPMethod, CiscoLwappDot11ClientEncryptionMethod, CiscoLwappDot11ClientKeyMgmtMethod, CiscoLwappDot11ClientPowerSaveMode, CiscoLwappDot11ClientRadioType, CiscoLwappDot11ClientReqStatus, CiscoLwappDot11ClientSSId, CiscoLwappDot11ClientTxPowerMode = mibBuilder.importSymbols("CISCO-LWAPP-DOT11-CLIENT-CCX-TC-MIB", "CiscoLwappDot11ClientAuthMethod", "CiscoLwappDot11ClientCredentialType", "CiscoLwappDot11ClientEAPMethod", "CiscoLwappDot11ClientEncryptionMethod", "CiscoLwappDot11ClientKeyMgmtMethod", "CiscoLwappDot11ClientPowerSaveMode", "CiscoLwappDot11ClientRadioType", "CiscoLwappDot11ClientReqStatus", "CiscoLwappDot11ClientSSId", "CiscoLwappDot11ClientTxPowerMode")
ciscoLwappDot11ClientCCXV5ReportingMIBConform, ciscoLwappDot11ClientCcxMIBObjects, cldcClientMacAddress = mibBuilder.importSymbols("CISCO-LWAPP-DOT11-CLIENT-MIB", "ciscoLwappDot11ClientCCXV5ReportingMIBConform", "ciscoLwappDot11ClientCcxMIBObjects", "cldcClientMacAddress")
ciscoMgmt, = mibBuilder.importSymbols("CISCO-SMI", "ciscoMgmt")
CvE164Address, = mibBuilder.importSymbols("CISCO-TC", "CvE164Address")
SnmpAdminString, = mibBuilder.importSymbols("SNMP-FRAMEWORK-MIB", "SnmpAdminString")
ModuleCompliance, NotificationGroup, ObjectGroup = mibBuilder.importSymbols("SNMPv2-CONF", "ModuleCompliance", "NotificationGroup", "ObjectGroup")
Bits, Counter32, Counter64, Gauge32, Integer32, IpAddress, ModuleIdentity, MibIdentifier, NotificationType, ObjectIdentity, MibScalar, MibTable, MibTableRow, MibTableColumn, TimeTicks, Unsigned32, iso = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Counter32", "Counter64", "Gauge32", "Integer32", "IpAddress", "ModuleIdentity", "MibIdentifier", "NotificationType", "ObjectIdentity", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "TimeTicks", "Unsigned32", "iso")
DisplayString, MacAddress, TextualConvention = mibBuilder.importSymbols("SNMPv2-TC", "DisplayString", "MacAddress", "TextualConvention")
ciscoLwappDot11ClientCCXv5ReportingMIB = ModuleIdentity((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4))
ciscoLwappDot11ClientCCXv5ReportingMIB.setRevisions(('2017-04-18 00:00',))
if mibBuilder.loadTexts: ciscoLwappDot11ClientCCXv5ReportingMIB.setLastUpdated('2017-04-18 00:00')
if mibBuilder.loadTexts: ciscoLwappDot11ClientCCXv5ReportingMIB.setOrganization('Cisco Systems Inc.')
ciscoLwappDot11ClientCCXv5ReportingMIBObjects = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1))
ciscoClientCcxManuReporting = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 1))
ciscoClientCcxOperReporting = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2))
ciscoClientCcxProfileReporting = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3))
ciscoClientCcxCapabilityReporting = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 4))
cldccManufacturerInfoTable = MibTable((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 1, 1), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cldccManufacturerInfoTable.setStatus('current')
cldccManufacturerInfoEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 1, 1, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "CISCO-LWAPP-DOT11-CLIENT-MIB", "cldcClientMacAddress"))
if mibBuilder.loadTexts: cldccManufacturerInfoEntry.setStatus('current')
cldccManufacturerInfoStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 1, 1, 1, 1), CiscoLwappDot11ClientReqStatus()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: cldccManufacturerInfoStatus.setStatus('current')
cldccManufacturerInfoOUI = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 1, 1, 1, 2), OctetString().subtype(subtypeSpec=ValueSizeConstraint(3, 3)).setFixedLength(3)).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccManufacturerInfoOUI.setStatus('current')
cldccManufacturerInfoID = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 1, 1, 1, 3), SnmpAdminString().subtype(subtypeSpec=ValueSizeConstraint(0, 255))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccManufacturerInfoID.setStatus('current')
cldccManufacturerInfoModel = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 1, 1, 1, 4), SnmpAdminString().subtype(subtypeSpec=ValueSizeConstraint(0, 255))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccManufacturerInfoModel.setStatus('current')
cldccManufacturerInfoSerialNum = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 1, 1, 1, 5), SnmpAdminString().subtype(subtypeSpec=ValueSizeConstraint(0, 255))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccManufacturerInfoSerialNum.setStatus('current')
cldccManufacturerInfoRadioType = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 1, 1, 1, 6), SnmpAdminString().subtype(subtypeSpec=ValueSizeConstraint(0, 100))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccManufacturerInfoRadioType.setStatus('current')
cldccManufacturerInfoMacAddress = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 1, 1, 1, 7), MacAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccManufacturerInfoMacAddress.setStatus('current')
cldccManufacturerInfoAntennaType = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 1, 1, 1, 8), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(0, 1, 2, 3, 4, 5, 6, 7))).clone(namedValues=NamedValues(("omniDirectionalCollinear", 0), ("omniDirectionalDiversity", 1), ("omniDirectionalOther", 2), ("directionalYagi", 3), ("directionalPanel", 4), ("directionalSector", 5), ("directionalOther", 6), ("unknown", 7)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccManufacturerInfoAntennaType.setStatus('current')
cldccManufacturerInfoAntennaGain = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 1, 1, 1, 9), Unsigned32().subtype(subtypeSpec=ValueRangeConstraint(0, 40))).setUnits('dBm').setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccManufacturerInfoAntennaGain.setStatus('current')
cldccManuRxSensTable = MibTable((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 1, 2), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cldccManuRxSensTable.setStatus('current')
cldccManuRxSensEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 1, 2, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "CISCO-LWAPP-DOT11-CLIENT-MIB", "cldcClientMacAddress"), (0, "CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccManuRxSensRadioIndex"), (0, "CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccManuRxSensRadioDataRateIndex"))
if mibBuilder.loadTexts: cldccManuRxSensEntry.setStatus('current')
cldccManuRxSensRadioIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 1, 2, 1, 1), Unsigned32()).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cldccManuRxSensRadioIndex.setStatus('current')
cldccManuRxSensRadioDataRateIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 1, 2, 1, 2), Unsigned32()).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cldccManuRxSensRadioDataRateIndex.setStatus('current')
cldccManuRxSensRadioType = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 1, 2, 1, 3), CiscoLwappDot11ClientRadioType()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccManuRxSensRadioType.setStatus('current')
cldccManuRxSensRadioDataRate = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 1, 2, 1, 4), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccManuRxSensRadioDataRate.setStatus('current')
cldccManuRxSensMinRssi = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 1, 2, 1, 5), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccManuRxSensMinRssi.setStatus('current')
cldccManuRxSensMaxRssi = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 1, 2, 1, 6), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccManuRxSensMaxRssi.setStatus('current')
cldccCapabilityTable = MibTable((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 4, 1), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cldccCapabilityTable.setStatus('current')
cldccCapabilityEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 4, 1, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "CISCO-LWAPP-DOT11-CLIENT-MIB", "cldcClientMacAddress"))
if mibBuilder.loadTexts: cldccCapabilityEntry.setStatus('current')
cldccCapabilityStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 4, 1, 1, 1), CiscoLwappDot11ClientReqStatus()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: cldccCapabilityStatus.setStatus('current')
cldccCapabilityRadioType = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 4, 1, 1, 2), SnmpAdminString().subtype(subtypeSpec=ValueSizeConstraint(0, 100))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccCapabilityRadioType.setStatus('current')
cldccServiceCapability = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 4, 1, 1, 4), SnmpAdminString().subtype(subtypeSpec=ValueSizeConstraint(0, 100))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccServiceCapability.setStatus('current')
cldccCapabilityChannelsTable = MibTable((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 4, 2), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cldccCapabilityChannelsTable.setStatus('current')
cldccCapabilityChannelsEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 4, 2, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "CISCO-LWAPP-DOT11-CLIENT-MIB", "cldcClientMacAddress"), (0, "CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccCapabilityRadioIndex"))
if mibBuilder.loadTexts: cldccCapabilityChannelsEntry.setStatus('current')
cldccCapabilityRadioIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 4, 2, 1, 1), Unsigned32()).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cldccCapabilityRadioIndex.setStatus('current')
cldccCapabilityChRadioType = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 4, 2, 1, 2), CiscoLwappDot11ClientRadioType()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccCapabilityChRadioType.setStatus('current')
cldccCapabilityRadioChannels = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 4, 2, 1, 3), SnmpAdminString().subtype(subtypeSpec=ValueSizeConstraint(0, 100))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccCapabilityRadioChannels.setStatus('current')
cldccCapabilityTxPowerTable = MibTable((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 4, 3), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cldccCapabilityTxPowerTable.setStatus('current')
cldccCapabilityTxPowerEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 4, 3, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "CISCO-LWAPP-DOT11-CLIENT-MIB", "cldcClientMacAddress"), (0, "CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccCapabilityTxPowerIndex"))
if mibBuilder.loadTexts: cldccCapabilityTxPowerEntry.setStatus('current')
cldccCapabilityTxPowerIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 4, 3, 1, 1), Unsigned32()).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cldccCapabilityTxPowerIndex.setStatus('current')
cldccCapabilityTxPowerRadioType = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 4, 3, 1, 2), CiscoLwappDot11ClientRadioType()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccCapabilityTxPowerRadioType.setStatus('current')
cldccCapabilityTxPowerMode = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 4, 3, 1, 3), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(0, 1))).clone(namedValues=NamedValues(("fixed", 0), ("automatic", 1)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccCapabilityTxPowerMode.setStatus('current')
cldccCapabilityTxPower = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 4, 3, 1, 4), OctetString().subtype(subtypeSpec=ValueSizeConstraint(0, 255))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccCapabilityTxPower.setStatus('current')
cldccCapabilityDataRateTable = MibTable((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 4, 4), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cldccCapabilityDataRateTable.setStatus('current')
cldccCapabilityDataRateEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 4, 4, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "CISCO-LWAPP-DOT11-CLIENT-MIB", "cldcClientMacAddress"), (0, "CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccCapabilityDataRateIndex"))
if mibBuilder.loadTexts: cldccCapabilityDataRateEntry.setStatus('current')
cldccCapabilityDataRateIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 4, 4, 1, 1), Unsigned32()).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cldccCapabilityDataRateIndex.setStatus('current')
cldccCapabilityDataRateRadioType = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 4, 4, 1, 2), CiscoLwappDot11ClientRadioType()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccCapabilityDataRateRadioType.setStatus('current')
cldccCapabilityDataRates = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 4, 4, 1, 3), SnmpAdminString().subtype(subtypeSpec=ValueSizeConstraint(0, 255))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccCapabilityDataRates.setStatus('current')
cldccOperParamsTable = MibTable((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 1), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cldccOperParamsTable.setStatus('current')
cldccOperParamsEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 1, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "CISCO-LWAPP-DOT11-CLIENT-MIB", "cldcClientMacAddress"))
if mibBuilder.loadTexts: cldccOperParamsEntry.setStatus('current')
cldccOperParamsStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 1, 1, 1), CiscoLwappDot11ClientReqStatus()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: cldccOperParamsStatus.setStatus('current')
cldccOperParamsRadioType = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 1, 1, 2), SnmpAdminString().subtype(subtypeSpec=ValueSizeConstraint(0, 100))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccOperParamsRadioType.setStatus('current')
cldccOperParamsSSId = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 1, 1, 7), CiscoLwappDot11ClientSSId()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccOperParamsSSId.setStatus('current')
cldccOperParamsDeviceName = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 1, 1, 8), SnmpAdminString().subtype(subtypeSpec=ValueSizeConstraint(0, 100))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccOperParamsDeviceName.setStatus('current')
cldccOperParamsDeviceType = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 1, 1, 9), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 255))).clone(namedValues=NamedValues(("laptop", 0), ("pc", 1), ("pda", 2), ("dot11MobilePhone", 3), ("dualModePhone", 4), ("wgb", 5), ("scanner", 6), ("tabletPc", 7), ("printer", 8), ("projector", 9), ("videoConfSystem", 10), ("camera", 11), ("gamingSystem", 12), ("dot11DeskPhone", 13), ("cashRegister", 14), ("radioTag", 15), ("rfidSensor", 16), ("server", 17), ("appSpecific", 18), ("unknown", 255)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccOperParamsDeviceType.setStatus('current')
cldccOperParamsOSId = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 1, 1, 10), SnmpAdminString().subtype(subtypeSpec=ValueSizeConstraint(0, 100))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccOperParamsOSId.setStatus('current')
cldccOperParamsOSVersion = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 1, 1, 11), SnmpAdminString().subtype(subtypeSpec=ValueSizeConstraint(0, 100))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccOperParamsOSVersion.setStatus('current')
cldccOperParamsIpAddressMode = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 1, 1, 12), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(0, 1))).clone(namedValues=NamedValues(("static", 0), ("dhcp", 1)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccOperParamsIpAddressMode.setStatus('current')
cldccOperParamsIpv4Address = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 1, 1, 13), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccOperParamsIpv4Address.setStatus('current')
cldccOperParamsIpv4SubnetMask = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 1, 1, 14), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccOperParamsIpv4SubnetMask.setStatus('current')
cldccOperParamsIpv6Address = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 1, 1, 15), OctetString().subtype(subtypeSpec=ValueSizeConstraint(0, 16))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccOperParamsIpv6Address.setStatus('current')
cldccOperParamsIpv6SubnetMask = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 1, 1, 16), OctetString().subtype(subtypeSpec=ValueSizeConstraint(0, 16))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccOperParamsIpv6SubnetMask.setStatus('current')
cldccOperParamsDefaultGateway = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 1, 1, 17), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccOperParamsDefaultGateway.setStatus('current')
cldccOperParamsEntPhone = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 1, 1, 18), CvE164Address()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccOperParamsEntPhone.setStatus('current')
cldccOperParamsCellPhone = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 1, 1, 19), CvE164Address()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccOperParamsCellPhone.setStatus('current')
cldccOperParamsFirmwareVersion = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 1, 1, 20), SnmpAdminString().subtype(subtypeSpec=ValueSizeConstraint(0, 100))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccOperParamsFirmwareVersion.setStatus('current')
cldccOperParamsDriverVersion = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 1, 1, 21), SnmpAdminString().subtype(subtypeSpec=ValueSizeConstraint(0, 100))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccOperParamsDriverVersion.setStatus('current')
cldccOperParamsPowerSaveMode = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 1, 1, 22), CiscoLwappDot11ClientPowerSaveMode()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccOperParamsPowerSaveMode.setStatus('current')
cldccOperParamsAuthMethod = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 1, 1, 23), CiscoLwappDot11ClientAuthMethod()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccOperParamsAuthMethod.setStatus('current')
cldccOperParamsKeyMgmtMethod = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 1, 1, 25), CiscoLwappDot11ClientKeyMgmtMethod()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccOperParamsKeyMgmtMethod.setStatus('current')
cldccOperParamsEncrMethod = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 1, 1, 26), CiscoLwappDot11ClientEncryptionMethod()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccOperParamsEncrMethod.setStatus('current')
cldccOperParamsDot1xSecurity = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 1, 1, 27), SnmpAdminString().subtype(subtypeSpec=ValueSizeConstraint(0, 100))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccOperParamsDot1xSecurity.setStatus('current')
cldccOperParamsSysName = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 1, 1, 28), SnmpAdminString().subtype(subtypeSpec=ValueSizeConstraint(0, 100))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccOperParamsSysName.setStatus('current')
cldccOperParamsLocalization = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 1, 1, 29), SnmpAdminString().subtype(subtypeSpec=ValueSizeConstraint(0, 100))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccOperParamsLocalization.setStatus('current')
cldccOperParamsDNSTable = MibTable((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 2), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cldccOperParamsDNSTable.setStatus('current')
cldccOperParamsDNSEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 2, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "CISCO-LWAPP-DOT11-CLIENT-MIB", "cldcClientMacAddress"), (0, "CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperParamsDNSServerIndex"))
if mibBuilder.loadTexts: cldccOperParamsDNSEntry.setStatus('current')
cldccOperParamsDNSServerIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 2, 1, 1), Unsigned32()).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cldccOperParamsDNSServerIndex.setStatus('current')
cldccOperParamsDNSServerAddress = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 2, 1, 2), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccOperParamsDNSServerAddress.setStatus('current')
cldccOperParamsWINSTable = MibTable((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 3), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cldccOperParamsWINSTable.setStatus('current')
cldccOperParamsWINSEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 3, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "CISCO-LWAPP-DOT11-CLIENT-MIB", "cldcClientMacAddress"), (0, "CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperParamsWINSServerIndex"))
if mibBuilder.loadTexts: cldccOperParamsWINSEntry.setStatus('current')
cldccOperParamsWINSServerIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 3, 1, 1), Unsigned32()).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cldccOperParamsWINSServerIndex.setStatus('current')
cldccOperParamsWINSServerAddress = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 3, 1, 2), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccOperParamsWINSServerAddress.setStatus('current')
cldccOperChannelsTable = MibTable((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 4), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cldccOperChannelsTable.setStatus('current')
cldccOperChannelsEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 4, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "CISCO-LWAPP-DOT11-CLIENT-MIB", "cldcClientMacAddress"), (0, "CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperRadioIndex"))
if mibBuilder.loadTexts: cldccOperChannelsEntry.setStatus('current')
cldccOperRadioIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 4, 1, 1), Unsigned32()).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cldccOperRadioIndex.setStatus('current')
cldccOperRadioType = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 4, 1, 2), CiscoLwappDot11ClientRadioType()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccOperRadioType.setStatus('current')
cldccOperRadioChannels = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 4, 1, 3), SnmpAdminString().subtype(subtypeSpec=ValueSizeConstraint(0, 255))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccOperRadioChannels.setStatus('current')
cldccOperTxPowerTable = MibTable((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 5), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cldccOperTxPowerTable.setStatus('current')
cldccOperTxPowerEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 5, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "CISCO-LWAPP-DOT11-CLIENT-MIB", "cldcClientMacAddress"), (0, "CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperTxPowerIndex"))
if mibBuilder.loadTexts: cldccOperTxPowerEntry.setStatus('current')
cldccOperTxPowerIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 5, 1, 1), Unsigned32()).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cldccOperTxPowerIndex.setStatus('current')
cldccOperTxPowerRadioType = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 5, 1, 2), CiscoLwappDot11ClientRadioType()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccOperTxPowerRadioType.setStatus('current')
cldccOperTxPowerMode = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 5, 1, 3), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(0, 1))).clone(namedValues=NamedValues(("fixed", 0), ("automatic", 1)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccOperTxPowerMode.setStatus('current')
cldccOperTxPower = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 5, 1, 4), OctetString().subtype(subtypeSpec=ValueSizeConstraint(0, 255))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccOperTxPower.setStatus('current')
cldccOperDataRateTable = MibTable((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 6), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cldccOperDataRateTable.setStatus('current')
cldccOperDataRateEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 6, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "CISCO-LWAPP-DOT11-CLIENT-MIB", "cldcClientMacAddress"), (0, "CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperDataRateIndex"))
if mibBuilder.loadTexts: cldccOperDataRateEntry.setStatus('current')
cldccOperDataRateIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 6, 1, 1), Unsigned32()).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cldccOperDataRateIndex.setStatus('current')
cldccOperDataRateRadioType = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 6, 1, 2), CiscoLwappDot11ClientRadioType()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccOperDataRateRadioType.setStatus('current')
cldccOperDataRates = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 2, 6, 1, 3), SnmpAdminString().subtype(subtypeSpec=ValueSizeConstraint(0, 255))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccOperDataRates.setStatus('current')
cldccProfileReqTable = MibTable((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 1), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cldccProfileReqTable.setStatus('current')
cldccProfileReqEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 1, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "CISCO-LWAPP-DOT11-CLIENT-MIB", "cldcClientMacAddress"))
if mibBuilder.loadTexts: cldccProfileReqEntry.setStatus('current')
cldccProfileReqNumProfiles = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 1, 1, 1), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 32))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccProfileReqNumProfiles.setStatus('current')
cldccProfileReqCurrentProfile = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 1, 1, 2), SnmpAdminString().subtype(subtypeSpec=ValueSizeConstraint(1, 100))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccProfileReqCurrentProfile.setStatus('current')
cldccProfileReqReportingStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 1, 1, 3), CiscoLwappDot11ClientReqStatus()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: cldccProfileReqReportingStatus.setStatus('current')
cldccProfileTable = MibTable((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 2), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cldccProfileTable.setStatus('current')
cldccProfileEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 2, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "CISCO-LWAPP-DOT11-CLIENT-MIB", "cldcClientMacAddress"), (0, "CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfileIndex"))
if mibBuilder.loadTexts: cldccProfileEntry.setStatus('current')
cldccProfileIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 2, 1, 1), Unsigned32()).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cldccProfileIndex.setStatus('current')
cldccProfileName = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 2, 1, 2), SnmpAdminString().subtype(subtypeSpec=ValueSizeConstraint(1, 100))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccProfileName.setStatus('current')
cldccProfileSSId = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 2, 1, 4), CiscoLwappDot11ClientSSId()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccProfileSSId.setStatus('current')
cldccProfileAuthMethod = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 2, 1, 5), CiscoLwappDot11ClientAuthMethod()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccProfileAuthMethod.setStatus('current')
cldccProfileKeyMgmtMethod = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 2, 1, 6), CiscoLwappDot11ClientKeyMgmtMethod()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccProfileKeyMgmtMethod.setStatus('current')
cldccProfileEncrMethod = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 2, 1, 7), CiscoLwappDot11ClientEncryptionMethod()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccProfileEncrMethod.setStatus('current')
cldccProfileDot1xSecurity = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 2, 1, 8), SnmpAdminString().subtype(subtypeSpec=ValueSizeConstraint(0, 100))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccProfileDot1xSecurity.setStatus('current')
cldccProfilePowerSaveMode = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 2, 1, 9), CiscoLwappDot11ClientPowerSaveMode()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccProfilePowerSaveMode.setStatus('current')
cldccProfileRadioType = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 2, 1, 10), SnmpAdminString().subtype(subtypeSpec=ValueSizeConstraint(0, 100))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccProfileRadioType.setStatus('current')
cldccProfileProprietaryOptionName = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 2, 1, 11), SnmpAdminString().subtype(subtypeSpec=ValueSizeConstraint(0, 100))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccProfileProprietaryOptionName.setStatus('current')
cldccProfileProprietaryOptionValue = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 2, 1, 12), SnmpAdminString().subtype(subtypeSpec=ValueSizeConstraint(0, 100))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccProfileProprietaryOptionValue.setStatus('current')
cldccProfileAPTable = MibTable((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 3), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cldccProfileAPTable.setStatus('current')
cldccProfileAPEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 3, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "CISCO-LWAPP-DOT11-CLIENT-MIB", "cldcClientMacAddress"), (0, "CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfileIndex"), (0, "CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfilePreferredAPIndex"))
if mibBuilder.loadTexts: cldccProfileAPEntry.setStatus('current')
cldccProfilePreferredAPIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 3, 1, 1), Unsigned32()).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cldccProfilePreferredAPIndex.setStatus('current')
cldccProfilePreferredAP = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 3, 1, 2), MacAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccProfilePreferredAP.setStatus('current')
cldccProfileTxPowerTable = MibTable((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 4), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cldccProfileTxPowerTable.setStatus('current')
cldccProfileTxPowerEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 4, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "CISCO-LWAPP-DOT11-CLIENT-MIB", "cldcClientMacAddress"), (0, "CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfileIndex"), (0, "CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfileTxPowerIndex"))
if mibBuilder.loadTexts: cldccProfileTxPowerEntry.setStatus('current')
cldccProfileTxPowerIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 4, 1, 1), Unsigned32()).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cldccProfileTxPowerIndex.setStatus('current')
cldccProfileTxPowerRadioType = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 4, 1, 2), CiscoLwappDot11ClientRadioType()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccProfileTxPowerRadioType.setStatus('current')
cldccProfileTxPowerMode = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 4, 1, 3), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(0, 1))).clone(namedValues=NamedValues(("fixed", 0), ("automatic", 1)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccProfileTxPowerMode.setStatus('current')
cldccProfileTxPower = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 4, 1, 4), OctetString().subtype(subtypeSpec=ValueSizeConstraint(0, 255))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccProfileTxPower.setStatus('current')
cldccProfileChannelTable = MibTable((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 5), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cldccProfileChannelTable.setStatus('current')
cldccProfileChannelEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 5, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "CISCO-LWAPP-DOT11-CLIENT-MIB", "cldcClientMacAddress"), (0, "CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfileIndex"), (0, "CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfileChannelIndex"))
if mibBuilder.loadTexts: cldccProfileChannelEntry.setStatus('current')
cldccProfileChannelIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 5, 1, 1), Unsigned32()).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cldccProfileChannelIndex.setStatus('current')
cldccProfileChRadioType = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 5, 1, 2), CiscoLwappDot11ClientRadioType()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccProfileChRadioType.setStatus('current')
cldccProfileChannels = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 5, 1, 3), SnmpAdminString().subtype(subtypeSpec=ValueSizeConstraint(0, 255))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccProfileChannels.setStatus('current')
cldccProfileDataRateTable = MibTable((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 6), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cldccProfileDataRateTable.setStatus('current')
cldccProfileDataRateEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 6, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "CISCO-LWAPP-DOT11-CLIENT-MIB", "cldcClientMacAddress"), (0, "CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfileIndex"), (0, "CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfileDataRateIndex"))
if mibBuilder.loadTexts: cldccProfileDataRateEntry.setStatus('current')
cldccProfileDataRateIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 6, 1, 1), Unsigned32()).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cldccProfileDataRateIndex.setStatus('current')
cldccProfileDataRateRadioType = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 6, 1, 2), CiscoLwappDot11ClientRadioType()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccProfileDataRateRadioType.setStatus('current')
cldccProfileDataRates = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 6, 1, 3), SnmpAdminString().subtype(subtypeSpec=ValueSizeConstraint(0, 255))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccProfileDataRates.setStatus('current')
cldccProfileRadioOptionsTable = MibTable((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 7), ).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cldccProfileRadioOptionsTable.setStatus('current')
cldccProfileRadioOptionsEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 7, 1), ).setMaxAccess("notaccessible").setIndexNames((0, "CISCO-LWAPP-DOT11-CLIENT-MIB", "cldcClientMacAddress"), (0, "CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfileIndex"), (0, "CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfileRadioOptionIndex"))
if mibBuilder.loadTexts: cldccProfileRadioOptionsEntry.setStatus('current')
cldccProfileRadioOptionIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 7, 1, 1), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 10))).setMaxAccess("notaccessible")
if mibBuilder.loadTexts: cldccProfileRadioOptionIndex.setStatus('current')
cldccProfileRadioOptionsRadioType = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 7, 1, 2), CiscoLwappDot11ClientRadioType()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccProfileRadioOptionsRadioType.setStatus('current')
cldccProfilePreambleType = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 7, 1, 3), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(0, 1, 255))).clone(namedValues=NamedValues(("short", 0), ("long", 1), ("unknown", 255)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccProfilePreambleType.setStatus('current')
cldccProfileCCAMethod = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 7, 1, 4), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(0, 1, 2, 255))).clone(namedValues=NamedValues(("energyDetect", 0), ("carrierDetect", 1), ("energyCarrierDetect", 2), ("unknown", 255)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccProfileCCAMethod.setStatus('current')
cldccProfileDataRetries = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 7, 1, 5), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 10))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccProfileDataRetries.setStatus('current')
cldccProfileFragmentThreshold = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 599, 3, 4, 1, 3, 7, 1, 6), Integer32().subtype(subtypeSpec=ValueRangeConstraint(256, 2346))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cldccProfileFragmentThreshold.setStatus('current')
ciscoLwappDot11ClientCCXV5ReportingMIBCompliances = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 599, 2, 4, 1))
ciscoLwappDot11ClientCCXV5ReportingMIBGroups = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 599, 2, 4, 2))
ciscoLwappDot11ClientCCXV5ReportingMIBCompliance = ModuleCompliance((1, 3, 6, 1, 4, 1, 9, 9, 599, 2, 4, 1, 1)).setObjects(("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "ciscoLwappDot11ClientCCXV5ReportingMIBManufacturerGroup"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "ciscoLwappDot11ClientCCXV5ReportingMIBCapabilityGroup"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "ciscoLwappDot11ClientCCXV5ReportingMIBOperParamsGroup"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "ciscoLwappDot11ClientCCXV5ReportingMIBProfileGroup"))

if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    ciscoLwappDot11ClientCCXV5ReportingMIBCompliance = ciscoLwappDot11ClientCCXV5ReportingMIBCompliance.setStatus('current')
ciscoLwappDot11ClientCCXV5ReportingMIBManufacturerGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 9, 9, 599, 2, 4, 2, 1)).setObjects(("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccManufacturerInfoStatus"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccManufacturerInfoOUI"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccManufacturerInfoID"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccManufacturerInfoModel"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccManufacturerInfoSerialNum"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccManufacturerInfoRadioType"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccManufacturerInfoMacAddress"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccManufacturerInfoAntennaType"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccManufacturerInfoAntennaGain"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccManuRxSensRadioIndex"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccManuRxSensRadioDataRateIndex"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccManuRxSensRadioType"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccManuRxSensRadioDataRate"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccManuRxSensMinRssi"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccManuRxSensMaxRssi"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    ciscoLwappDot11ClientCCXV5ReportingMIBManufacturerGroup = ciscoLwappDot11ClientCCXV5ReportingMIBManufacturerGroup.setStatus('current')
ciscoLwappDot11ClientCCXV5ReportingMIBCapabilityGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 9, 9, 599, 2, 4, 2, 2)).setObjects(("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccCapabilityStatus"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccCapabilityRadioType"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccServiceCapability"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccCapabilityRadioIndex"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccCapabilityChRadioType"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccCapabilityRadioChannels"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccCapabilityTxPowerIndex"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccCapabilityTxPowerRadioType"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccCapabilityTxPowerMode"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccCapabilityTxPower"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccCapabilityDataRateIndex"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccCapabilityDataRateRadioType"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccCapabilityDataRates"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    ciscoLwappDot11ClientCCXV5ReportingMIBCapabilityGroup = ciscoLwappDot11ClientCCXV5ReportingMIBCapabilityGroup.setStatus('current')
ciscoLwappDot11ClientCCXV5ReportingMIBOperParamsGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 9, 9, 599, 2, 4, 2, 3)).setObjects(("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperParamsStatus"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperParamsRadioType"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperParamsSSId"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperParamsDeviceName"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperParamsDeviceType"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperParamsOSId"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperParamsOSVersion"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperParamsIpAddressMode"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperParamsIpv4Address"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperParamsIpv4SubnetMask"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperParamsIpv6Address"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperParamsIpv6SubnetMask"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperParamsDefaultGateway"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperParamsEntPhone"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperParamsCellPhone"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperParamsFirmwareVersion"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperParamsDriverVersion"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperParamsPowerSaveMode"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperParamsAuthMethod"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperParamsKeyMgmtMethod"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperParamsEncrMethod"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperParamsDot1xSecurity"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperParamsSysName"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperParamsLocalization"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperParamsDNSServerIndex"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperParamsDNSServerAddress"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperParamsWINSServerIndex"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperParamsWINSServerAddress"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperRadioIndex"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperRadioType"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperRadioChannels"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperTxPowerIndex"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperTxPowerRadioType"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperTxPowerMode"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperTxPower"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperDataRateIndex"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperDataRateRadioType"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccOperDataRates"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    ciscoLwappDot11ClientCCXV5ReportingMIBOperParamsGroup = ciscoLwappDot11ClientCCXV5ReportingMIBOperParamsGroup.setStatus('current')
ciscoLwappDot11ClientCCXV5ReportingMIBProfileGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 9, 9, 599, 2, 4, 2, 4)).setObjects(("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfileReqNumProfiles"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfileReqCurrentProfile"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfileReqReportingStatus"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfileIndex"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfileName"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfileSSId"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfileAuthMethod"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfileKeyMgmtMethod"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfileEncrMethod"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfileDot1xSecurity"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfilePowerSaveMode"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfileRadioType"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfileProprietaryOptionName"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfileProprietaryOptionValue"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfilePreferredAPIndex"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfilePreferredAP"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfileTxPowerIndex"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfileTxPowerRadioType"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfileTxPowerMode"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfileTxPower"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfileChannelIndex"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfileChRadioType"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfileChannels"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfileDataRateIndex"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfileDataRateRadioType"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfileDataRates"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfileRadioOptionIndex"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfileRadioOptionsRadioType"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfilePreambleType"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfileCCAMethod"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfileDataRetries"), ("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", "cldccProfileFragmentThreshold"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    ciscoLwappDot11ClientCCXV5ReportingMIBProfileGroup = ciscoLwappDot11ClientCCXV5ReportingMIBProfileGroup.setStatus('current')
mibBuilder.exportSymbols("CISCO-LWAPP-DOT11-CLIENT-CCXV5-REPORTING-MIB", PYSNMP_MODULE_ID=ciscoLwappDot11ClientCCXv5ReportingMIB, ciscoClientCcxCapabilityReporting=ciscoClientCcxCapabilityReporting, ciscoClientCcxManuReporting=ciscoClientCcxManuReporting, ciscoClientCcxOperReporting=ciscoClientCcxOperReporting, ciscoClientCcxProfileReporting=ciscoClientCcxProfileReporting, ciscoLwappDot11ClientCCXV5ReportingMIBCapabilityGroup=ciscoLwappDot11ClientCCXV5ReportingMIBCapabilityGroup, ciscoLwappDot11ClientCCXV5ReportingMIBCompliance=ciscoLwappDot11ClientCCXV5ReportingMIBCompliance, ciscoLwappDot11ClientCCXV5ReportingMIBCompliances=ciscoLwappDot11ClientCCXV5ReportingMIBCompliances, ciscoLwappDot11ClientCCXV5ReportingMIBGroups=ciscoLwappDot11ClientCCXV5ReportingMIBGroups, ciscoLwappDot11ClientCCXV5ReportingMIBManufacturerGroup=ciscoLwappDot11ClientCCXV5ReportingMIBManufacturerGroup, ciscoLwappDot11ClientCCXV5ReportingMIBOperParamsGroup=ciscoLwappDot11ClientCCXV5ReportingMIBOperParamsGroup, ciscoLwappDot11ClientCCXV5ReportingMIBProfileGroup=ciscoLwappDot11ClientCCXV5ReportingMIBProfileGroup, ciscoLwappDot11ClientCCXv5ReportingMIB=ciscoLwappDot11ClientCCXv5ReportingMIB, ciscoLwappDot11ClientCCXv5ReportingMIBObjects=ciscoLwappDot11ClientCCXv5ReportingMIBObjects, cldccCapabilityChRadioType=cldccCapabilityChRadioType, cldccCapabilityChannelsEntry=cldccCapabilityChannelsEntry, cldccCapabilityChannelsTable=cldccCapabilityChannelsTable, cldccCapabilityDataRateEntry=cldccCapabilityDataRateEntry, cldccCapabilityDataRateIndex=cldccCapabilityDataRateIndex, cldccCapabilityDataRateRadioType=cldccCapabilityDataRateRadioType, cldccCapabilityDataRateTable=cldccCapabilityDataRateTable, cldccCapabilityDataRates=cldccCapabilityDataRates, cldccCapabilityEntry=cldccCapabilityEntry, cldccCapabilityRadioChannels=cldccCapabilityRadioChannels, cldccCapabilityRadioIndex=cldccCapabilityRadioIndex, cldccCapabilityRadioType=cldccCapabilityRadioType, cldccCapabilityStatus=cldccCapabilityStatus, cldccCapabilityTable=cldccCapabilityTable, cldccCapabilityTxPower=cldccCapabilityTxPower, cldccCapabilityTxPowerEntry=cldccCapabilityTxPowerEntry, cldccCapabilityTxPowerIndex=cldccCapabilityTxPowerIndex, cldccCapabilityTxPowerMode=cldccCapabilityTxPowerMode, cldccCapabilityTxPowerRadioType=cldccCapabilityTxPowerRadioType, cldccCapabilityTxPowerTable=cldccCapabilityTxPowerTable, cldccManuRxSensEntry=cldccManuRxSensEntry, cldccManuRxSensMaxRssi=cldccManuRxSensMaxRssi, cldccManuRxSensMinRssi=cldccManuRxSensMinRssi, cldccManuRxSensRadioDataRate=cldccManuRxSensRadioDataRate, cldccManuRxSensRadioDataRateIndex=cldccManuRxSensRadioDataRateIndex, cldccManuRxSensRadioIndex=cldccManuRxSensRadioIndex, cldccManuRxSensRadioType=cldccManuRxSensRadioType, cldccManuRxSensTable=cldccManuRxSensTable, cldccManufacturerInfoAntennaGain=cldccManufacturerInfoAntennaGain, cldccManufacturerInfoAntennaType=cldccManufacturerInfoAntennaType, cldccManufacturerInfoEntry=cldccManufacturerInfoEntry, cldccManufacturerInfoID=cldccManufacturerInfoID, cldccManufacturerInfoMacAddress=cldccManufacturerInfoMacAddress, cldccManufacturerInfoModel=cldccManufacturerInfoModel, cldccManufacturerInfoOUI=cldccManufacturerInfoOUI, cldccManufacturerInfoRadioType=cldccManufacturerInfoRadioType, cldccManufacturerInfoSerialNum=cldccManufacturerInfoSerialNum, cldccManufacturerInfoStatus=cldccManufacturerInfoStatus, cldccManufacturerInfoTable=cldccManufacturerInfoTable, cldccOperChannelsEntry=cldccOperChannelsEntry, cldccOperChannelsTable=cldccOperChannelsTable, cldccOperDataRateEntry=cldccOperDataRateEntry, cldccOperDataRateIndex=cldccOperDataRateIndex, cldccOperDataRateRadioType=cldccOperDataRateRadioType, cldccOperDataRateTable=cldccOperDataRateTable, cldccOperDataRates=cldccOperDataRates, cldccOperParamsAuthMethod=cldccOperParamsAuthMethod, cldccOperParamsCellPhone=cldccOperParamsCellPhone, cldccOperParamsDNSEntry=cldccOperParamsDNSEntry, cldccOperParamsDNSServerAddress=cldccOperParamsDNSServerAddress, cldccOperParamsDNSServerIndex=cldccOperParamsDNSServerIndex, cldccOperParamsDNSTable=cldccOperParamsDNSTable, cldccOperParamsDefaultGateway=cldccOperParamsDefaultGateway, cldccOperParamsDeviceName=cldccOperParamsDeviceName, cldccOperParamsDeviceType=cldccOperParamsDeviceType, cldccOperParamsDot1xSecurity=cldccOperParamsDot1xSecurity, cldccOperParamsDriverVersion=cldccOperParamsDriverVersion, cldccOperParamsEncrMethod=cldccOperParamsEncrMethod, cldccOperParamsEntPhone=cldccOperParamsEntPhone, cldccOperParamsEntry=cldccOperParamsEntry, cldccOperParamsFirmwareVersion=cldccOperParamsFirmwareVersion, cldccOperParamsIpAddressMode=cldccOperParamsIpAddressMode, cldccOperParamsIpv4Address=cldccOperParamsIpv4Address, cldccOperParamsIpv4SubnetMask=cldccOperParamsIpv4SubnetMask, cldccOperParamsIpv6Address=cldccOperParamsIpv6Address, cldccOperParamsIpv6SubnetMask=cldccOperParamsIpv6SubnetMask, cldccOperParamsKeyMgmtMethod=cldccOperParamsKeyMgmtMethod, cldccOperParamsLocalization=cldccOperParamsLocalization, cldccOperParamsOSId=cldccOperParamsOSId, cldccOperParamsOSVersion=cldccOperParamsOSVersion, cldccOperParamsPowerSaveMode=cldccOperParamsPowerSaveMode, cldccOperParamsRadioType=cldccOperParamsRadioType, cldccOperParamsSSId=cldccOperParamsSSId, cldccOperParamsStatus=cldccOperParamsStatus, cldccOperParamsSysName=cldccOperParamsSysName, cldccOperParamsTable=cldccOperParamsTable, cldccOperParamsWINSEntry=cldccOperParamsWINSEntry, cldccOperParamsWINSServerAddress=cldccOperParamsWINSServerAddress, cldccOperParamsWINSServerIndex=cldccOperParamsWINSServerIndex, cldccOperParamsWINSTable=cldccOperParamsWINSTable, cldccOperRadioChannels=cldccOperRadioChannels, cldccOperRadioIndex=cldccOperRadioIndex, cldccOperRadioType=cldccOperRadioType, cldccOperTxPower=cldccOperTxPower, cldccOperTxPowerEntry=cldccOperTxPowerEntry, cldccOperTxPowerIndex=cldccOperTxPowerIndex, cldccOperTxPowerMode=cldccOperTxPowerMode, cldccOperTxPowerRadioType=cldccOperTxPowerRadioType, cldccOperTxPowerTable=cldccOperTxPowerTable, cldccProfileAPEntry=cldccProfileAPEntry, cldccProfileAPTable=cldccProfileAPTable, cldccProfileAuthMethod=cldccProfileAuthMethod, cldccProfileCCAMethod=cldccProfileCCAMethod, cldccProfileChRadioType=cldccProfileChRadioType, cldccProfileChannelEntry=cldccProfileChannelEntry, cldccProfileChannelIndex=cldccProfileChannelIndex, cldccProfileChannelTable=cldccProfileChannelTable, cldccProfileChannels=cldccProfileChannels, cldccProfileDataRateEntry=cldccProfileDataRateEntry, cldccProfileDataRateIndex=cldccProfileDataRateIndex, cldccProfileDataRateRadioType=cldccProfileDataRateRadioType, cldccProfileDataRateTable=cldccProfileDataRateTable, cldccProfileDataRates=cldccProfileDataRates, cldccProfileDataRetries=cldccProfileDataRetries, cldccProfileDot1xSecurity=cldccProfileDot1xSecurity, cldccProfileEncrMethod=cldccProfileEncrMethod, cldccProfileEntry=cldccProfileEntry, cldccProfileFragmentThreshold=cldccProfileFragmentThreshold, cldccProfileIndex=cldccProfileIndex, cldccProfileKeyMgmtMethod=cldccProfileKeyMgmtMethod, cldccProfileName=cldccProfileName, cldccProfilePowerSaveMode=cldccProfilePowerSaveMode, cldccProfilePreambleType=cldccProfilePreambleType, cldccProfilePreferredAP=cldccProfilePreferredAP, cldccProfilePreferredAPIndex=cldccProfilePreferredAPIndex, cldccProfileProprietaryOptionName=cldccProfileProprietaryOptionName, cldccProfileProprietaryOptionValue=cldccProfileProprietaryOptionValue, cldccProfileRadioOptionIndex=cldccProfileRadioOptionIndex, cldccProfileRadioOptionsEntry=cldccProfileRadioOptionsEntry, cldccProfileRadioOptionsRadioType=cldccProfileRadioOptionsRadioType, cldccProfileRadioOptionsTable=cldccProfileRadioOptionsTable, cldccProfileRadioType=cldccProfileRadioType, cldccProfileReqCurrentProfile=cldccProfileReqCurrentProfile, cldccProfileReqEntry=cldccProfileReqEntry, cldccProfileReqNumProfiles=cldccProfileReqNumProfiles, cldccProfileReqReportingStatus=cldccProfileReqReportingStatus, cldccProfileReqTable=cldccProfileReqTable, cldccProfileSSId=cldccProfileSSId, cldccProfileTable=cldccProfileTable, cldccProfileTxPower=cldccProfileTxPower, cldccProfileTxPowerEntry=cldccProfileTxPowerEntry, cldccProfileTxPowerIndex=cldccProfileTxPowerIndex, cldccProfileTxPowerMode=cldccProfileTxPowerMode, cldccProfileTxPowerRadioType=cldccProfileTxPowerRadioType, cldccProfileTxPowerTable=cldccProfileTxPowerTable, cldccServiceCapability=cldccServiceCapability)
